<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Week 4: Regression II (Model Specification) | Intermediate Quantitative Methods</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Week 4: Regression II (Model Specification) | Intermediate Quantitative Methods" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Week 4: Regression II (Model Specification) | Intermediate Quantitative Methods" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Lucas Lemmann" />


<meta name="date" content="2023-12-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-3-regression-i-prediction.html"/>
<link rel="next" href="week-5.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Intermediate Quantitative Methods</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#how-to-use-these-exercises"><i class="fa fa-check"></i><b>0.1</b> How to use these exercises?</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#schedule"><i class="fa fa-check"></i><b>0.2</b> Schedule</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html"><i class="fa fa-check"></i><b>1</b> Week 1: DIYS 1</a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html#aims"><i class="fa fa-check"></i><b>1.1</b> Aims:</a></li>
<li class="chapter" data-level="1.2" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html#first-part-repetition-rrstudio"><i class="fa fa-check"></i><b>1.2</b> First Part: REPETITION R/RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html#second-part-some-simple-analysis"><i class="fa fa-check"></i><b>1.3</b> Second Part: Some Simple Analysis</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html#first-adjust-the-data"><i class="fa fa-check"></i><b>1.3.1</b> First, adjust the data</a></li>
<li class="chapter" data-level="1.3.2" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html#second-answer-the-following-questions"><i class="fa fa-check"></i><b>1.3.2</b> Second, answer the following questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2.html"><a href="week-2.html"><i class="fa fa-check"></i><b>2</b> Week 2</a>
<ul>
<li class="chapter" data-level="2.1" data-path="week-2.html"><a href="week-2.html#exercise"><i class="fa fa-check"></i><b>2.1</b> Exercise</a></li>
<li class="chapter" data-level="2.2" data-path="week-2.html"><a href="week-2.html#solution"><i class="fa fa-check"></i><b>2.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html"><i class="fa fa-check"></i><b>3</b> Week 3: Regression I (Prediction)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#aims-1"><i class="fa fa-check"></i><b>3.1</b> Aims</a></li>
<li class="chapter" data-level="3.2" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#exercise-context-and-question"><i class="fa fa-check"></i><b>3.2</b> Exercise: Context and Question</a></li>
<li class="chapter" data-level="3.3" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#exercise-solution"><i class="fa fa-check"></i><b>3.3</b> Exercise: solution</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#real-data"><i class="fa fa-check"></i><b>3.3.1</b> Real data</a></li>
<li class="chapter" data-level="3.3.2" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#simulated-data"><i class="fa fa-check"></i><b>3.3.2</b> Simulated data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#appendix-getting-the-data-first"><i class="fa fa-check"></i><b>3.4</b> Appendix: Getting the data first</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html"><i class="fa fa-check"></i><b>4</b> Week 4: Regression II (Model Specification)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#aims-2"><i class="fa fa-check"></i><b>4.1</b> Aims</a></li>
<li class="chapter" data-level="4.2" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#exercise-context-and-questions"><i class="fa fa-check"></i><b>4.2</b> Exercise: Context and questions</a></li>
<li class="chapter" data-level="4.3" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#adjusting-the-data-first"><i class="fa fa-check"></i><b>4.3</b> Adjusting the data first</a></li>
<li class="chapter" data-level="4.4" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#exercise-solution-1"><i class="fa fa-check"></i><b>4.4</b> Exercise: solution</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#real-data-1"><i class="fa fa-check"></i><b>4.4.1</b> Real data</a></li>
<li class="chapter" data-level="4.4.2" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#simulated-data-1"><i class="fa fa-check"></i><b>4.4.2</b> Simulated data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-5.html"><a href="week-5.html"><i class="fa fa-check"></i><b>5</b> Week 5</a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-5.html"><a href="week-5.html#exercise-1"><i class="fa fa-check"></i><b>5.1</b> Exercise</a></li>
<li class="chapter" data-level="5.2" data-path="week-5.html"><a href="week-5.html#solution-1"><i class="fa fa-check"></i><b>5.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-6.html"><a href="week-6.html"><i class="fa fa-check"></i><b>6</b> Week 6</a>
<ul>
<li class="chapter" data-level="6.1" data-path="week-6.html"><a href="week-6.html#exercise-2"><i class="fa fa-check"></i><b>6.1</b> Exercise</a></li>
<li class="chapter" data-level="6.2" data-path="week-6.html"><a href="week-6.html#solution-2"><i class="fa fa-check"></i><b>6.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-7.html"><a href="week-7.html"><i class="fa fa-check"></i><b>7</b> Week 7</a>
<ul>
<li class="chapter" data-level="7.1" data-path="week-7.html"><a href="week-7.html#exercise-3"><i class="fa fa-check"></i><b>7.1</b> Exercise</a></li>
<li class="chapter" data-level="7.2" data-path="week-7.html"><a href="week-7.html#solution-3"><i class="fa fa-check"></i><b>7.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-8-causality-iii-observational-data.html"><a href="week-8-causality-iii-observational-data.html"><i class="fa fa-check"></i><b>8</b> Week 8: Causality III (Observational Data)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="week-8-causality-iii-observational-data.html"><a href="week-8-causality-iii-observational-data.html#aims-3"><i class="fa fa-check"></i><b>8.1</b> Aims</a></li>
<li class="chapter" data-level="8.2" data-path="week-8-causality-iii-observational-data.html"><a href="week-8-causality-iii-observational-data.html#exercise-4"><i class="fa fa-check"></i><b>8.2</b> Exercise</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="week-8-causality-iii-observational-data.html"><a href="week-8-causality-iii-observational-data.html#simulated-data-2"><i class="fa fa-check"></i><b>8.2.1</b> Simulated data</a></li>
<li class="chapter" data-level="8.2.2" data-path="week-8-causality-iii-observational-data.html"><a href="week-8-causality-iii-observational-data.html#real-data-2"><i class="fa fa-check"></i><b>8.2.2</b> Real data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-9.html"><a href="week-9.html"><i class="fa fa-check"></i><b>9</b> Week 9</a>
<ul>
<li class="chapter" data-level="9.1" data-path="week-9.html"><a href="week-9.html#exercise-5"><i class="fa fa-check"></i><b>9.1</b> Exercise</a></li>
<li class="chapter" data-level="9.2" data-path="week-9.html"><a href="week-9.html#solution-4"><i class="fa fa-check"></i><b>9.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="week-10.html"><a href="week-10.html"><i class="fa fa-check"></i><b>10</b> Week 10</a>
<ul>
<li class="chapter" data-level="10.1" data-path="week-10.html"><a href="week-10.html#exercise-6"><i class="fa fa-check"></i><b>10.1</b> Exercise</a></li>
<li class="chapter" data-level="10.2" data-path="week-10.html"><a href="week-10.html#solution-5"><i class="fa fa-check"></i><b>10.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="week-11.html"><a href="week-11.html"><i class="fa fa-check"></i><b>11</b> Week 11</a>
<ul>
<li class="chapter" data-level="11.1" data-path="week-11.html"><a href="week-11.html#exercise-7"><i class="fa fa-check"></i><b>11.1</b> Exercise</a></li>
<li class="chapter" data-level="11.2" data-path="week-11.html"><a href="week-11.html#solution-6"><i class="fa fa-check"></i><b>11.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="week-12.html"><a href="week-12.html"><i class="fa fa-check"></i><b>12</b> Week 12</a>
<ul>
<li class="chapter" data-level="12.1" data-path="week-12.html"><a href="week-12.html#exercise-8"><i class="fa fa-check"></i><b>12.1</b> Exercise</a></li>
<li class="chapter" data-level="12.2" data-path="week-12.html"><a href="week-12.html#solution-7"><i class="fa fa-check"></i><b>12.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="week-13.html"><a href="week-13.html"><i class="fa fa-check"></i><b>13</b> Week 13</a>
<ul>
<li class="chapter" data-level="13.1" data-path="week-13.html"><a href="week-13.html#exercise-9"><i class="fa fa-check"></i><b>13.1</b> Exercise</a></li>
<li class="chapter" data-level="13.2" data-path="week-13.html"><a href="week-13.html#solution-8"><i class="fa fa-check"></i><b>13.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="week-14.html"><a href="week-14.html"><i class="fa fa-check"></i><b>14</b> Week 14</a>
<ul>
<li class="chapter" data-level="14.1" data-path="week-14.html"><a href="week-14.html#exercise-10"><i class="fa fa-check"></i><b>14.1</b> Exercise</a></li>
<li class="chapter" data-level="14.2" data-path="week-14.html"><a href="week-14.html#solution-9"><i class="fa fa-check"></i><b>14.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="potentially-useful-exercises.html"><a href="potentially-useful-exercises.html"><i class="fa fa-check"></i><b>15</b> Potentially useful exercises</a>
<ul>
<li class="chapter" data-level="15.1" data-path="potentially-useful-exercises.html"><a href="potentially-useful-exercises.html#taken-out-from-week-3"><i class="fa fa-check"></i><b>15.1</b> Taken out from Week 3</a></li>
<li class="chapter" data-level="15.2" data-path="potentially-useful-exercises.html"><a href="potentially-useful-exercises.html#taken-out-from-week-4"><i class="fa fa-check"></i><b>15.2</b> Taken out from Week 4</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="potentially-useful-exercises.html"><a href="potentially-useful-exercises.html#simulated-data-3"><i class="fa fa-check"></i><b>15.2.1</b> Simulated data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>16</b> Data transformation</a>
<ul>
<li class="chapter" data-level="16.1" data-path="data-transformation.html"><a href="data-transformation.html#week-1-gorilla"><i class="fa fa-check"></i><b>16.1</b> Week 1: Gorilla</a></li>
<li class="chapter" data-level="16.2" data-path="data-transformation.html"><a href="data-transformation.html#week-4-restricted-variables-from-selects"><i class="fa fa-check"></i><b>16.2</b> Week 4: restricted variables from SELECTS</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published using bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Intermediate Quantitative Methods</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-4-regression-ii-model-specification" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Week 4: Regression II (Model Specification)<a href="week-4-regression-ii-model-specification.html#week-4-regression-ii-model-specification" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="aims-2" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Aims<a href="week-4-regression-ii-model-specification.html#aims-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Using multiple regressors and interaction terms in regression analysis for quantitative descriptive purposes with real data</li>
<li>Using simulation to instantiate how different properties of the data generating process alter or not metrics of goodness of fit</li>
</ol>
</div>
<div id="exercise-context-and-questions" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Exercise: Context and questions<a href="week-4-regression-ii-model-specification.html#exercise-context-and-questions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Currently led by <a href="https://forscenter.ch/staff/anke-tresch/">Prof. Anke Tresch</a>, “[t]he Swiss Election Study (Selects) has been investigating the electoral behaviour of Swiss citizens in national elections since 1995. The project sheds light on the dynamics of the citizens’ opinion formation as well as on the determinants of their political participation and voting choice for a specific candidate or party.” See more <a href="https://forscenter.ch/projects/selects/">here</a>.</p>
<p>In this exercise, you will use data for the year 2019. You will use it to answer the following questions:</p>
<ol style="list-style-type: decimal">
<li>Do older voters have stronger right leaning preferences than younger ones?</li>
<li>Do political preferences vary across sexes?</li>
<li>Do political preferences vary across the main language spoken at the respondent’s home?</li>
<li>Do differences in political preferences across sexes vary depending on the respondents’ age?</li>
<li>Do differences in political preferences across sexes vary depending on the respondents’ main language?</li>
<li>Do differences in political preferences across main languages vary depending on the respondents’ age?</li>
<li>Do differences in political preferences across sexes vary depending on the respondents’ age and main language?</li>
</ol>
</div>
<div id="adjusting-the-data-first" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Adjusting the data first<a href="week-4-regression-ii-model-specification.html#adjusting-the-data-first" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the folder <code>SELECTS 2019</code>, you can find the file <code>data.csv</code>. It is a version of the SELECTS data for 2019 only with the variables relevant for our exercise.</p>
<ol style="list-style-type: decimal">
<li>Open the file:</li>
</ol>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="week-4-regression-ii-model-specification.html#cb106-1" tabindex="-1"></a>selects19 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;Data/SELECTS 2019/data.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>In order to store information in smaller files, researchers use codebooks to numerically represent values that, otherwise, would be much more space consuming in their respective representation in text form. Use the file <code>Selects2019_Codebook_EN.pdf</code> to create the variable <code>LanguageHome</code> where the numerical values for the variable <code>f20221</code> (i.e., “Main language spoken in family or at home”) are preplaced with their respective text values.</li>
</ol>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="week-4-regression-ii-model-specification.html#cb107-1" tabindex="-1"></a>selects19 <span class="ot">&lt;-</span> selects19 <span class="sc">%&gt;%</span></span>
<span id="cb107-2"><a href="week-4-regression-ii-model-specification.html#cb107-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">LanguageHome =</span> <span class="fu">case_when</span>( <span class="co">#a new variable is created</span></span>
<span id="cb107-3"><a href="week-4-regression-ii-model-specification.html#cb107-3" tabindex="-1"></a><span class="co">#each numerical value in the codebook is replace with it&#39;s corresponding text value</span></span>
<span id="cb107-4"><a href="week-4-regression-ii-model-specification.html#cb107-4" tabindex="-1"></a>    f20221 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">&quot;German/Swiss German&quot;</span>, </span>
<span id="cb107-5"><a href="week-4-regression-ii-model-specification.html#cb107-5" tabindex="-1"></a>    f20221 <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">&quot;French&quot;</span>,</span>
<span id="cb107-6"><a href="week-4-regression-ii-model-specification.html#cb107-6" tabindex="-1"></a>    f20221 <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">&quot;Italian&quot;</span>,</span>
<span id="cb107-7"><a href="week-4-regression-ii-model-specification.html#cb107-7" tabindex="-1"></a>    f20221 <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">&quot;Romansh&quot;</span>,</span>
<span id="cb107-8"><a href="week-4-regression-ii-model-specification.html#cb107-8" tabindex="-1"></a>    f20221 <span class="sc">==</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">&quot;Other&quot;</span>))</span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>As we have seen in week 1, it is a good practice to name your variables so their interpretation is easy. For example, instead of using <code>sex</code> as a variable name, using <code>female</code> facilitates understanding that a zero represents <code>male</code> while a one represents <code>female</code>. Again, use the codebook to transform the variable <code>sex</code> into <code>female</code>.</li>
</ol>
<p>Relabel the <code>sex</code> variable:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="week-4-regression-ii-model-specification.html#cb108-1" tabindex="-1"></a>selects19 <span class="ot">&lt;-</span> selects19 <span class="sc">%&gt;%</span></span>
<span id="cb108-2"><a href="week-4-regression-ii-model-specification.html#cb108-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">case_when</span>(</span>
<span id="cb108-3"><a href="week-4-regression-ii-model-specification.html#cb108-3" tabindex="-1"></a>    sex <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb108-4"><a href="week-4-regression-ii-model-specification.html#cb108-4" tabindex="-1"></a>    sex <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">1</span>))</span></code></pre></div>
<p>Rename the variable <code>sex</code> as <code>female</code>. Take the chance and rename <code>f15200</code> (i.e., “Left-right placement - Self”) as <code>LeftToRight</code>.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="week-4-regression-ii-model-specification.html#cb109-1" tabindex="-1"></a>selects19 <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">rename</span>(selects19, <span class="at">LeftToRight =</span> f15200, <span class="at">female =</span> sex)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>Print the name of all the variables available so you can use them later on.</li>
</ol>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="week-4-regression-ii-model-specification.html#cb110-1" tabindex="-1"></a><span class="fu">names</span>(selects19)</span></code></pre></div>
<pre><code>## [1] &quot;female&quot;       &quot;age&quot;          &quot;LeftToRight&quot;  &quot;f20221&quot;       &quot;LanguageHome&quot;</code></pre>
</div>
<div id="exercise-solution-1" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Exercise: solution<a href="week-4-regression-ii-model-specification.html#exercise-solution-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Note:</strong> Remember that you can copy the code from one point to answer another point. Simply make the necessary adjustments.</p>
<div id="real-data-1" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Real data<a href="week-4-regression-ii-model-specification.html#real-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Graph age vs. political preferences. Use a linear regression line to describe how the variables relate to each other.</li>
</ol>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="week-4-regression-ii-model-specification.html#cb112-1" tabindex="-1"></a><span class="co">#Means for Y and X: to have a clearer notion on the center of mass of the data.</span></span>
<span id="cb112-2"><a href="week-4-regression-ii-model-specification.html#cb112-2" tabindex="-1"></a>mean_LeftRight <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>LeftToRight, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb112-3"><a href="week-4-regression-ii-model-specification.html#cb112-3" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb112-4"><a href="week-4-regression-ii-model-specification.html#cb112-4" tabindex="-1"></a></span>
<span id="cb112-5"><a href="week-4-regression-ii-model-specification.html#cb112-5" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb112-6"><a href="week-4-regression-ii-model-specification.html#cb112-6" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> LeftToRight)) <span class="sc">+</span></span>
<span id="cb112-7"><a href="week-4-regression-ii-model-specification.html#cb112-7" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb112-8"><a href="week-4-regression-ii-model-specification.html#cb112-8" tabindex="-1"></a>  <span class="co"># Adding the regression line</span></span>
<span id="cb112-9"><a href="week-4-regression-ii-model-specification.html#cb112-9" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  </span>
<span id="cb112-10"><a href="week-4-regression-ii-model-specification.html#cb112-10" tabindex="-1"></a>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb112-11"><a href="week-4-regression-ii-model-specification.html#cb112-11" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_LeftRight, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  </span>
<span id="cb112-12"><a href="week-4-regression-ii-model-specification.html#cb112-12" tabindex="-1"></a>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb112-13"><a href="week-4-regression-ii-model-specification.html#cb112-13" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_age, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  </span>
<span id="cb112-14"><a href="week-4-regression-ii-model-specification.html#cb112-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb112-15"><a href="week-4-regression-ii-model-specification.html#cb112-15" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb112-16"><a href="week-4-regression-ii-model-specification.html#cb112-16" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb112-17"><a href="week-4-regression-ii-model-specification.html#cb112-17" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb112-18"><a href="week-4-regression-ii-model-specification.html#cb112-18" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Political Preferences (left to right)&quot;</span>,</span>
<span id="cb112-19"><a href="week-4-regression-ii-model-specification.html#cb112-19" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot Age vs. Political Preferences&quot;</span></span>
<span id="cb112-20"><a href="week-4-regression-ii-model-specification.html#cb112-20" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-72-1.png" width="576" /></p>
<p>Therefore, we can say that, indeed, older voters have stronger right leaning preferences than younger ones.</p>
<ol start="2" style="list-style-type: decimal">
<li>Since the political preferences as well as years are defined in discrete values, many values can overlap for the same pair<code>(preference, age)</code>. Use the <code>ggridges</code> package to see how do preferences distribute across different age values.</li>
</ol>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="week-4-regression-ii-model-specification.html#cb113-1" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> <span class="fu">as.factor</span>(LeftToRight), <span class="at">fill =</span> <span class="fu">as.factor</span>(LeftToRight))) <span class="sc">+</span></span>
<span id="cb113-2"><a href="week-4-regression-ii-model-specification.html#cb113-2" tabindex="-1"></a>  <span class="co"># to show the age distribution for each level of political preference</span></span>
<span id="cb113-3"><a href="week-4-regression-ii-model-specification.html#cb113-3" tabindex="-1"></a>  <span class="fu">geom_density_ridges</span>() <span class="sc">+</span> </span>
<span id="cb113-4"><a href="week-4-regression-ii-model-specification.html#cb113-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> LeftToRight, <span class="at">group =</span> <span class="dv">1</span>), </span>
<span id="cb113-5"><a href="week-4-regression-ii-model-specification.html#cb113-5" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb113-6"><a href="week-4-regression-ii-model-specification.html#cb113-6" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_LeftRight, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span></span>
<span id="cb113-7"><a href="week-4-regression-ii-model-specification.html#cb113-7" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_age, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb113-8"><a href="week-4-regression-ii-model-specification.html#cb113-8" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb113-9"><a href="week-4-regression-ii-model-specification.html#cb113-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb113-10"><a href="week-4-regression-ii-model-specification.html#cb113-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb113-11"><a href="week-4-regression-ii-model-specification.html#cb113-11" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb113-12"><a href="week-4-regression-ii-model-specification.html#cb113-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb113-13"><a href="week-4-regression-ii-model-specification.html#cb113-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Political Preferences (left to right)&quot;</span>,</span>
<span id="cb113-14"><a href="week-4-regression-ii-model-specification.html#cb113-14" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Political preferences by age level&quot;</span>,</span>
<span id="cb113-15"><a href="week-4-regression-ii-model-specification.html#cb113-15" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;factor(LeftToRight)&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-73-1.png" width="576" /></p>
<ol start="3" style="list-style-type: decimal">
<li>Regress the political preferences on age. As we learnt in the exercises from last week, the regression with intercept fits data better in most cases: act accordingly. Report and interpret the parameters. Graph some of the main components of the regression output.</li>
</ol>
<ul>
<li>Write the regression here.</li>
</ul>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="week-4-regression-ii-model-specification.html#cb114-1" tabindex="-1"></a><span class="co">#regression</span></span>
<span id="cb114-2"><a href="week-4-regression-ii-model-specification.html#cb114-2" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(LeftToRight <span class="sc">~</span> age, <span class="at">data =</span> selects19)</span>
<span id="cb114-3"><a href="week-4-regression-ii-model-specification.html#cb114-3" tabindex="-1"></a><span class="fu">summary</span>(result)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = LeftToRight ~ age, data = selects19)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.9150 -2.0380 -0.0186  2.1958  5.5271 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 4.122055   0.106375  38.750   &lt;2e-16 ***
## age         0.019489   0.001979   9.846   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.649 on 5905 degrees of freedom
## Multiple R-squared:  0.01615,    Adjusted R-squared:  0.01598 
## F-statistic: 96.94 on 1 and 5905 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li>Report and interpret the parameters here.</li>
</ul>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="week-4-regression-ii-model-specification.html#cb116-1" tabindex="-1"></a>coeffs<span class="ot">&lt;-</span> <span class="fu">coef</span>(result)</span>
<span id="cb116-2"><a href="week-4-regression-ii-model-specification.html#cb116-2" tabindex="-1"></a>coeffs</span></code></pre></div>
<pre><code>## (Intercept)         age 
##  4.12205528  0.01948902</code></pre>
<p>The beta value for (Intercept) is 4.12, and for <code>r</code>names(coeffs[2])` is 0.02.</p>
<p>It means that, <em>given our model</em>, an increase of one year in age across the Swiss citizens is associated with an average increase in the <code>LeftToRight</code> self-declared scale of 0.02 ideological units. Likewise, , <em>given our model</em>, newborns can be expected to have an average ideological value of 4.12, while 100 year old citizens can be expected to have an average ideological value of 6.12. We must, nonetheless, remain cautious and keep our predictions as much as possible within the range of regressors our sample provides us with.</p>
<ul>
<li>Graph some of the main components of the regression output here.</li>
</ul>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="week-4-regression-ii-model-specification.html#cb118-1" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> LeftToRight)) <span class="sc">+</span>  <span class="co"># Removed selects19$ from aes(), not necessary</span></span>
<span id="cb118-2"><a href="week-4-regression-ii-model-specification.html#cb118-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.001</span>) <span class="sc">+</span></span>
<span id="cb118-3"><a href="week-4-regression-ii-model-specification.html#cb118-3" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]),</span>
<span id="cb118-4"><a href="week-4-regression-ii-model-specification.html#cb118-4" tabindex="-1"></a>                <span class="at">slope =</span> <span class="dv">0</span>, </span>
<span id="cb118-5"><a href="week-4-regression-ii-model-specification.html#cb118-5" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Newborn&quot;</span>)) <span class="sc">+</span></span>
<span id="cb118-6"><a href="week-4-regression-ii-model-specification.html#cb118-6" tabindex="-1"></a>  </span>
<span id="cb118-7"><a href="week-4-regression-ii-model-specification.html#cb118-7" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]),</span>
<span id="cb118-8"><a href="week-4-regression-ii-model-specification.html#cb118-8" tabindex="-1"></a>                <span class="at">slope =</span> <span class="fu">unname</span>(coeffs[<span class="dv">2</span>]), </span>
<span id="cb118-9"><a href="week-4-regression-ii-model-specification.html#cb118-9" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Average individual over time&quot;</span>)) <span class="sc">+</span></span>
<span id="cb118-10"><a href="week-4-regression-ii-model-specification.html#cb118-10" tabindex="-1"></a>  </span>
<span id="cb118-11"><a href="week-4-regression-ii-model-specification.html#cb118-11" tabindex="-1"></a>  <span class="co"># Define colors for the legend</span></span>
<span id="cb118-12"><a href="week-4-regression-ii-model-specification.html#cb118-12" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">&quot;Lines&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Newborn&quot;</span> <span class="ot">=</span> <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;Average individual over time&quot;</span> <span class="ot">=</span> <span class="st">&quot;red&quot;</span>)) <span class="sc">+</span></span>
<span id="cb118-13"><a href="week-4-regression-ii-model-specification.html#cb118-13" tabindex="-1"></a>  </span>
<span id="cb118-14"><a href="week-4-regression-ii-model-specification.html#cb118-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb118-15"><a href="week-4-regression-ii-model-specification.html#cb118-15" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb118-16"><a href="week-4-regression-ii-model-specification.html#cb118-16" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb118-17"><a href="week-4-regression-ii-model-specification.html#cb118-17" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb118-18"><a href="week-4-regression-ii-model-specification.html#cb118-18" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Political Preferences (left to right)&quot;</span>,</span>
<span id="cb118-19"><a href="week-4-regression-ii-model-specification.html#cb118-19" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relationship political preferences across ages&quot;</span></span>
<span id="cb118-20"><a href="week-4-regression-ii-model-specification.html#cb118-20" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-76-1.png" width="576" /></p>
<ol start="4" style="list-style-type: decimal">
<li>Now regress <code>LeftToRight</code> on <code>age</code> and <code>female</code>. do the same as in the previous point. Report and interpret the parameters. Graph some of the main components of the regression output.
Write the regression here.</li>
</ol>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="week-4-regression-ii-model-specification.html#cb119-1" tabindex="-1"></a><span class="co">#regression</span></span>
<span id="cb119-2"><a href="week-4-regression-ii-model-specification.html#cb119-2" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(LeftToRight <span class="sc">~</span> age <span class="sc">+</span> female, <span class="at">data =</span> selects19)</span>
<span id="cb119-3"><a href="week-4-regression-ii-model-specification.html#cb119-3" tabindex="-1"></a><span class="fu">summary</span>(result)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = LeftToRight ~ age + female, data = selects19)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.2108 -1.9784  0.0954  2.1145  5.8236 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.492964   0.112519  39.931   &lt;2e-16 ***
## age          0.018672   0.001966   9.496   &lt;2e-16 ***
## female      -0.652678   0.068477  -9.531   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.629 on 5904 degrees of freedom
## Multiple R-squared:  0.03106,    Adjusted R-squared:  0.03073 
## F-statistic: 94.63 on 2 and 5904 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Report and interpret the parameters here.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="week-4-regression-ii-model-specification.html#cb121-1" tabindex="-1"></a>coeffs<span class="ot">&lt;-</span> <span class="fu">coef</span>(result)</span>
<span id="cb121-2"><a href="week-4-regression-ii-model-specification.html#cb121-2" tabindex="-1"></a>coeffs</span></code></pre></div>
<pre><code>## (Intercept)         age      female 
##  4.49296422  0.01867214 -0.65267756</code></pre>
<p>The beta value for (Intercept), ’ is 4.49, for age, is 0.02, and for female is -0.65.</p>
<p>It means that, given our model, an increase of one year in age across the Swiss citizens is associated with an average increase in the LeftToRight self-declared scale of 0.02, <em>ideological units</em>. Likewise, male newborns can be expected to have an average ideological value of 4.49, while 100 year old male citizens can be expected to have an average ideological value of 6.49. Similarly, for each of those scenarios, should the individual be a female, it can be expected to have an average of 0.65 ideological units lower than a male individual under the same statistical circumstances. In other words, by design, our particular model only captures the average evolution of ideology over time but does not distinguish whether nor how it varies across sexes. Finally, just as in the previous point, we must remain cautious and keep our predictions as much as possible within the range of regressors our sample provides us with.</p>
<ul>
<li>Graph some of the main components of the regression output here.</li>
</ul>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="week-4-regression-ii-model-specification.html#cb123-1" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> LeftToRight)) <span class="sc">+</span> </span>
<span id="cb123-2"><a href="week-4-regression-ii-model-specification.html#cb123-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.001</span>) <span class="sc">+</span></span>
<span id="cb123-3"><a href="week-4-regression-ii-model-specification.html#cb123-3" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]), <span class="at">slope =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;Male newborn&quot;</span>)) <span class="sc">+</span></span>
<span id="cb123-4"><a href="week-4-regression-ii-model-specification.html#cb123-4" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">3</span>]), <span class="at">slope =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;Female newborn&quot;</span>)) <span class="sc">+</span></span>
<span id="cb123-5"><a href="week-4-regression-ii-model-specification.html#cb123-5" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]), <span class="at">slope =</span> <span class="fu">unname</span>(coeffs[<span class="dv">2</span>]), <span class="at">color =</span> <span class="st">&quot;Male over time&quot;</span>)) <span class="sc">+</span></span>
<span id="cb123-6"><a href="week-4-regression-ii-model-specification.html#cb123-6" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">3</span>]), <span class="at">slope =</span> <span class="fu">unname</span>(coeffs[<span class="dv">2</span>]), <span class="at">color =</span> <span class="st">&quot;Female over time&quot;</span>)) <span class="sc">+</span></span>
<span id="cb123-7"><a href="week-4-regression-ii-model-specification.html#cb123-7" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">&quot;Lines&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Male newborn&quot;</span> <span class="ot">=</span> <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;Female newborn&quot;</span> <span class="ot">=</span> <span class="st">&quot;red&quot;</span>, <span class="st">&quot;Male over time&quot;</span> <span class="ot">=</span> <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;Female over time&quot;</span> <span class="ot">=</span> <span class="st">&quot;purple&quot;</span>)) <span class="sc">+</span></span>
<span id="cb123-8"><a href="week-4-regression-ii-model-specification.html#cb123-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb123-9"><a href="week-4-regression-ii-model-specification.html#cb123-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb123-10"><a href="week-4-regression-ii-model-specification.html#cb123-10" tabindex="-1"></a></span>
<span id="cb123-11"><a href="week-4-regression-ii-model-specification.html#cb123-11" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb123-12"><a href="week-4-regression-ii-model-specification.html#cb123-12" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb123-13"><a href="week-4-regression-ii-model-specification.html#cb123-13" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Political Preferences (left to right)&quot;</span>,</span>
<span id="cb123-14"><a href="week-4-regression-ii-model-specification.html#cb123-14" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relationship political preferences across ages by sex </span><span class="sc">\n</span><span class="st">(without interaction)&quot;</span>,</span>
<span id="cb123-15"><a href="week-4-regression-ii-model-specification.html#cb123-15" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Line Type&quot;</span></span>
<span id="cb123-16"><a href="week-4-regression-ii-model-specification.html#cb123-16" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-79-1.png" width="576" /></p>
<ol start="5" style="list-style-type: decimal">
<li>You now remember that average political preferences across age can change across sexes: i.e., the average preferences across individuals in a same sex can change at different rates over time as well as begin from different departure points. Add the interaction <code>Age</code> and <code>female</code> and do the same as in the previous point.</li>
</ol>
<p>Write the regression here.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="week-4-regression-ii-model-specification.html#cb124-1" tabindex="-1"></a><span class="co">#regression</span></span>
<span id="cb124-2"><a href="week-4-regression-ii-model-specification.html#cb124-2" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(LeftToRight <span class="sc">~</span> age <span class="sc">*</span> female, <span class="at">data =</span> selects19)</span>
<span id="cb124-3"><a href="week-4-regression-ii-model-specification.html#cb124-3" tabindex="-1"></a><span class="fu">summary</span>(result)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = LeftToRight ~ age * female, data = selects19)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.9332 -2.0641  0.0372  2.1848  6.0372 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.847656   0.152489  31.790  &lt; 2e-16 ***
## age          0.011799   0.002801   4.213 2.56e-05 ***
## female      -1.340734   0.211254  -6.347 2.37e-10 ***
## age:female   0.013528   0.003930   3.443  0.00058 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.626 on 5903 degrees of freedom
## Multiple R-squared:  0.033,  Adjusted R-squared:  0.03251 
## F-statistic: 67.15 on 3 and 5903 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Report and interpret the parameters here.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="week-4-regression-ii-model-specification.html#cb126-1" tabindex="-1"></a>coeffs<span class="ot">&lt;-</span> <span class="fu">coef</span>(result)</span>
<span id="cb126-2"><a href="week-4-regression-ii-model-specification.html#cb126-2" tabindex="-1"></a>coeffs</span></code></pre></div>
<pre><code>## (Intercept)         age      female  age:female 
##  4.84765642  0.01179933 -1.34073442  0.01352810</code></pre>
<p>The beta value for (Intercept) is 4.85 for age is 0.01 for female is -1.34 and for age:female is 0.01.</p>
<p>It means that, <em>given our model</em>, an increase of one year in age across the male Swiss citizens is associated with an average increase in the LeftToRight self-declared scale of 0.01 ideological units. Likewise, while male newborns can be expected to have an average ideological value of 4.85, female newborns can be expected to have an average ideological value of 3.51. Also, while 100 year old male citizens can be expected to have an average ideological value of 5.85, 100 year old females can be expected to have an average ideological value of 5.51.</p>
<p>Finally, while, <em>given our model</em>, females have lower initial ideological initial values, the rate at which right leaning preferences increase among them over time is 0.01 ideological units per year higher than in males. Therefore, we can expect males’ and females’ average ideological values to converge when they are around 100 years old. Finally, just as in the previous point, we must remain cautious and keep our predictions as much as possible within the range of regressors our sample provides us with.</p>
<ul>
<li>Graph some of the main components of the regression output here.</li>
</ul>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="week-4-regression-ii-model-specification.html#cb128-1" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> LeftToRight)) <span class="sc">+</span> </span>
<span id="cb128-2"><a href="week-4-regression-ii-model-specification.html#cb128-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.001</span>) <span class="sc">+</span></span>
<span id="cb128-3"><a href="week-4-regression-ii-model-specification.html#cb128-3" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]), <span class="at">slope =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;Male newborn&quot;</span>)) <span class="sc">+</span></span>
<span id="cb128-4"><a href="week-4-regression-ii-model-specification.html#cb128-4" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">3</span>]), <span class="at">slope =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;Female newborn&quot;</span>)) <span class="sc">+</span></span>
<span id="cb128-5"><a href="week-4-regression-ii-model-specification.html#cb128-5" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]), <span class="at">slope =</span> <span class="fu">unname</span>(coeffs[<span class="dv">2</span>]), <span class="at">color =</span> <span class="st">&quot;Male over time&quot;</span>)) <span class="sc">+</span></span>
<span id="cb128-6"><a href="week-4-regression-ii-model-specification.html#cb128-6" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">3</span>]), <span class="at">slope =</span> <span class="fu">unname</span>(coeffs[<span class="dv">2</span>])<span class="sc">+</span><span class="fu">unname</span>(coeffs[<span class="dv">4</span>]), <span class="at">color =</span> <span class="st">&quot;Female over time&quot;</span>)) <span class="sc">+</span></span>
<span id="cb128-7"><a href="week-4-regression-ii-model-specification.html#cb128-7" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">&quot;Lines&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Male newborn&quot;</span> <span class="ot">=</span> <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;Female newborn&quot;</span> <span class="ot">=</span> <span class="st">&quot;red&quot;</span>, <span class="st">&quot;Male over time&quot;</span> <span class="ot">=</span> <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;Female over time&quot;</span> <span class="ot">=</span> <span class="st">&quot;purple&quot;</span>)) <span class="sc">+</span></span>
<span id="cb128-8"><a href="week-4-regression-ii-model-specification.html#cb128-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb128-9"><a href="week-4-regression-ii-model-specification.html#cb128-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb128-10"><a href="week-4-regression-ii-model-specification.html#cb128-10" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb128-11"><a href="week-4-regression-ii-model-specification.html#cb128-11" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb128-12"><a href="week-4-regression-ii-model-specification.html#cb128-12" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Political Preferences (left to right)&quot;</span>,</span>
<span id="cb128-13"><a href="week-4-regression-ii-model-specification.html#cb128-13" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relationship political preferences across ages by sex </span><span class="sc">\n</span><span class="st">(with interaction)&quot;</span></span>
<span id="cb128-14"><a href="week-4-regression-ii-model-specification.html#cb128-14" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-82-1.png" width="576" /></p>
<p>Unlike the previous point, in this point our model did not presume that the rate at which right leaning preferences increase among them over time is shared between males and females. Indeed, what the model shows is that both the intercepts and slopes are different for both groups. Particularly, <em>give our model</em>, the particular mix of intercepts and slopes allow females and males to converge on their average ideological values over time.</p>
<ol start="6" style="list-style-type: decimal">
<li>Following the same logic as in the previous point, you now add the <code>LanguageHome</code> categorical variable with the corresponding interactions. Do the same as in the previous point.</li>
</ol>
<p>Write the regression here.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="week-4-regression-ii-model-specification.html#cb129-1" tabindex="-1"></a><span class="co">#regression</span></span>
<span id="cb129-2"><a href="week-4-regression-ii-model-specification.html#cb129-2" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(LeftToRight <span class="sc">~</span> age <span class="sc">*</span> female <span class="sc">*</span> LanguageHome, <span class="at">data =</span> selects19)</span>
<span id="cb129-3"><a href="week-4-regression-ii-model-specification.html#cb129-3" tabindex="-1"></a><span class="fu">summary</span>(result)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = LeftToRight ~ age * female * LanguageHome, data = selects19)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.1650 -2.0129  0.0157  2.0714  6.1504 
## 
## Coefficients:
##                                              Estimate Std. Error t value
## (Intercept)                                 4.6522028  0.2598442  17.904
## age                                         0.0092259  0.0048428   1.905
## female                                     -1.2217711  0.3489102  -3.502
## LanguageHomeGerman/Swiss German             0.1982265  0.3407428   0.582
## LanguageHomeItalian                         0.8741812  0.4954660   1.764
## LanguageHomeOther                           0.5409228  0.7585873   0.713
## LanguageHomeRomansh                        -1.2787995  2.0100116  -0.636
## age:female                                  0.0140639  0.0065181   2.158
## age:LanguageHomeGerman/Swiss German         0.0055441  0.0062621   0.885
## age:LanguageHomeItalian                    -0.0030304  0.0092982  -0.326
## age:LanguageHomeOther                      -0.0095835  0.0145811  -0.657
## age:LanguageHomeRomansh                     0.0466591  0.0397951   1.172
## female:LanguageHomeGerman/Swiss German     -0.1885585  0.4684575  -0.403
## female:LanguageHomeItalian                  0.5629460  0.7043389   0.799
## female:LanguageHomeOther                   -1.6468317  0.9783983  -1.683
## female:LanguageHomeRomansh                 -1.0259620  4.0396347  -0.254
## age:female:LanguageHomeGerman/Swiss German -0.0002337  0.0086831  -0.027
## age:female:LanguageHomeItalian             -0.0124492  0.0133246  -0.934
## age:female:LanguageHomeOther                0.0265266  0.0193016   1.374
## age:female:LanguageHomeRomansh             -0.0041536  0.0833735  -0.050
##                                            Pr(&gt;|t|)    
## (Intercept)                                 &lt; 2e-16 ***
## age                                        0.056817 .  
## female                                     0.000466 ***
## LanguageHomeGerman/Swiss German            0.560759    
## LanguageHomeItalian                        0.077723 .  
## LanguageHomeOther                          0.475833    
## LanguageHomeRomansh                        0.524661    
## age:female                                 0.030994 *  
## age:LanguageHomeGerman/Swiss German        0.376011    
## age:LanguageHomeItalian                    0.744501    
## age:LanguageHomeOther                      0.511041    
## age:LanguageHomeRomansh                    0.241051    
## female:LanguageHomeGerman/Swiss German     0.687324    
## female:LanguageHomeItalian                 0.424175    
## female:LanguageHomeOther                   0.092391 .  
## female:LanguageHomeRomansh                 0.799525    
## age:female:LanguageHomeGerman/Swiss German 0.978527    
## age:female:LanguageHomeItalian             0.350189    
## age:female:LanguageHomeOther               0.169395    
## age:female:LanguageHomeRomansh             0.960268    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.615 on 5887 degrees of freedom
## Multiple R-squared:  0.04377,    Adjusted R-squared:  0.04068 
## F-statistic: 14.18 on 19 and 5887 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Report and interpret the parameters here.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="week-4-regression-ii-model-specification.html#cb131-1" tabindex="-1"></a>coeffs <span class="ot">&lt;-</span> <span class="fu">coef</span>(result)</span>
<span id="cb131-2"><a href="week-4-regression-ii-model-specification.html#cb131-2" tabindex="-1"></a>coeffs</span></code></pre></div>
<pre><code>##                                (Intercept) 
##                               4.6522027670 
##                                        age 
##                               0.0092259369 
##                                     female 
##                              -1.2217710646 
##            LanguageHomeGerman/Swiss German 
##                               0.1982265191 
##                        LanguageHomeItalian 
##                               0.8741812107 
##                          LanguageHomeOther 
##                               0.5409227964 
##                        LanguageHomeRomansh 
##                              -1.2787994823 
##                                 age:female 
##                               0.0140639403 
##        age:LanguageHomeGerman/Swiss German 
##                               0.0055440902 
##                    age:LanguageHomeItalian 
##                              -0.0030304217 
##                      age:LanguageHomeOther 
##                              -0.0095835495 
##                    age:LanguageHomeRomansh 
##                               0.0466590996 
##     female:LanguageHomeGerman/Swiss German 
##                              -0.1885585461 
##                 female:LanguageHomeItalian 
##                               0.5629459596 
##                   female:LanguageHomeOther 
##                              -1.6468317018 
##                 female:LanguageHomeRomansh 
##                              -1.0259619787 
## age:female:LanguageHomeGerman/Swiss German 
##                              -0.0002337215 
##             age:female:LanguageHomeItalian 
##                              -0.0124491713 
##               age:female:LanguageHomeOther 
##                               0.0265265501 
##             age:female:LanguageHomeRomansh 
##                              -0.0041536238</code></pre>
<p>Interpreting a regression with ever more interactions is <strong>exponentially harder!</strong> The reason is that the potential scenarios to evaluate must take into account the interaction between the categorical variables of sex (i.e., two potential values) and language (i.e., five potential values) as well as the continuous variable age. In our simplest model with no interaction in point 3 we had only two parameters, in point 4 we had three, in point 5 we had four parameters with one interaction. However, in point 6 we have <em>20</em> parameters. Consequently, below we present only some few cases aimed at signaling the general logic in the interpretation: we compare the male and female cases between French and Swiss German individuals.</p>
<p>First of all, the reference group are male newborns in French speaking households. For them, <em>given our model</em>, we can expect the average political preference to be 4.65. In contrast, male newborns in Swiss German speaking households can be expected to have 0.2 ideological units more than the reference group, i.e., 4.85. Female newborns in French speaking households can be expected to have -1.22 ideological units less than the reference group, i.e., 3.43. On the other hand, Female newborns in Swiss German speaking households can be expected to have -0.19 ideological units less than the reference group, i.e., 4.46.</p>
<p>Likewise, for 100 year old males from French speaking households, we can expect their average political preference value to be 5.57. On the contrary, 100 year old males from Swiss German speaking households can be expected to have 0.75 ideological units more than the reference group, i.e., 6.33. In the case of 100 year old females from French speaking households, we can expect their average political preference value to be 5.76, while for 100 year old females from Swiss German speaking households we can expect their average political preference value to be 5.75.</p>
<ul>
<li>Graph some of the main components of the regression output here.</li>
</ul>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="week-4-regression-ii-model-specification.html#cb133-1" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> LeftToRight)) <span class="sc">+</span></span>
<span id="cb133-2"><a href="week-4-regression-ii-model-specification.html#cb133-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.001</span>) <span class="sc">+</span></span>
<span id="cb133-3"><a href="week-4-regression-ii-model-specification.html#cb133-3" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]), <span class="at">slope =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;Male newborn French&quot;</span>), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb133-4"><a href="week-4-regression-ii-model-specification.html#cb133-4" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]), <span class="at">slope =</span> <span class="fu">unname</span>(coeffs[<span class="dv">2</span>]), <span class="at">color =</span> <span class="st">&quot;Male over time French&quot;</span>)) <span class="sc">+</span></span>
<span id="cb133-5"><a href="week-4-regression-ii-model-specification.html#cb133-5" tabindex="-1"></a></span>
<span id="cb133-6"><a href="week-4-regression-ii-model-specification.html#cb133-6" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">4</span>]), <span class="at">slope =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;Male newborn Swiss German&quot;</span>), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb133-7"><a href="week-4-regression-ii-model-specification.html#cb133-7" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">4</span>]), <span class="at">slope =</span> <span class="fu">unname</span>(coeffs[<span class="dv">2</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">9</span>]), <span class="at">color =</span> <span class="st">&quot;Male over time Swiss German&quot;</span>)) <span class="sc">+</span></span>
<span id="cb133-8"><a href="week-4-regression-ii-model-specification.html#cb133-8" tabindex="-1"></a></span>
<span id="cb133-9"><a href="week-4-regression-ii-model-specification.html#cb133-9" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">3</span>]), <span class="at">slope =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;Female newborn French&quot;</span>), <span class="at">size =</span> <span class="dv">2</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb133-10"><a href="week-4-regression-ii-model-specification.html#cb133-10" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">3</span>]), <span class="at">slope =</span> <span class="fu">unname</span>(coeffs[<span class="dv">2</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">8</span>]), <span class="at">color =</span> <span class="st">&quot;Female over time French&quot;</span>), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb133-11"><a href="week-4-regression-ii-model-specification.html#cb133-11" tabindex="-1"></a>  </span>
<span id="cb133-12"><a href="week-4-regression-ii-model-specification.html#cb133-12" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">3</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">4</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">13</span>]),</span>
<span id="cb133-13"><a href="week-4-regression-ii-model-specification.html#cb133-13" tabindex="-1"></a>                  <span class="at">slope =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;Female newborn Swiss German&quot;</span>), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb133-14"><a href="week-4-regression-ii-model-specification.html#cb133-14" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">3</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">4</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">13</span>]),</span>
<span id="cb133-15"><a href="week-4-regression-ii-model-specification.html#cb133-15" tabindex="-1"></a>                  <span class="at">slope =</span> <span class="fu">unname</span>(coeffs[<span class="dv">2</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">8</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">17</span>]), <span class="at">color =</span> <span class="st">&quot;Female over time Swiss German&quot;</span>)) <span class="sc">+</span></span>
<span id="cb133-16"><a href="week-4-regression-ii-model-specification.html#cb133-16" tabindex="-1"></a>  </span>
<span id="cb133-17"><a href="week-4-regression-ii-model-specification.html#cb133-17" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">&quot;Lines&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Male newborn French&quot;</span> <span class="ot">=</span> <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;Male over time French&quot;</span> <span class="ot">=</span> <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;Male newborn Swiss German&quot;</span> <span class="ot">=</span> <span class="st">&quot;red&quot;</span>, <span class="st">&quot;Male over time Swiss German&quot;</span> <span class="ot">=</span> <span class="st">&quot;red&quot;</span>, <span class="st">&quot;Female newborn French&quot;</span> <span class="ot">=</span> <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;Female over time French&quot;</span> <span class="ot">=</span> <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;Female newborn Swiss German&quot;</span><span class="ot">=</span> <span class="st">&quot;purple&quot;</span>, <span class="st">&quot;Female over time Swiss German&quot;</span><span class="ot">=</span> <span class="st">&quot;purple&quot;</span>)) <span class="sc">+</span></span>
<span id="cb133-18"><a href="week-4-regression-ii-model-specification.html#cb133-18" tabindex="-1"></a></span>
<span id="cb133-19"><a href="week-4-regression-ii-model-specification.html#cb133-19" tabindex="-1"></a>  <span class="fu">scale_linetype_manual</span>(<span class="at">name =</span> <span class="st">&quot;Lines&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Male newborn French&quot;</span> <span class="ot">=</span> <span class="st">&quot;dashed&quot;</span>, <span class="st">&quot;Male over time French&quot;</span> <span class="ot">=</span> <span class="st">&quot;solid&quot;</span>, <span class="st">&quot;Male newborn Swiss German&quot;</span> <span class="ot">=</span> <span class="st">&quot;dashed&quot;</span>, <span class="st">&quot;Male over time Swiss German&quot;</span> <span class="ot">=</span> <span class="st">&quot;solid&quot;</span>, <span class="st">&quot;Female newborn French&quot;</span> <span class="ot">=</span> <span class="st">&quot;dashed&quot;</span>, <span class="st">&quot;Female over time French&quot;</span> <span class="ot">=</span> <span class="st">&quot;solid&quot;</span>, <span class="st">&quot;Female newborn Swiss German&quot;</span> <span class="ot">=</span> <span class="st">&quot;dashed&quot;</span>, <span class="st">&quot;Female over time Swiss German&quot;</span> <span class="ot">=</span> <span class="st">&quot;solid&quot;</span>)) <span class="sc">+</span></span>
<span id="cb133-20"><a href="week-4-regression-ii-model-specification.html#cb133-20" tabindex="-1"></a></span>
<span id="cb133-21"><a href="week-4-regression-ii-model-specification.html#cb133-21" tabindex="-1"></a>  </span>
<span id="cb133-22"><a href="week-4-regression-ii-model-specification.html#cb133-22" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb133-23"><a href="week-4-regression-ii-model-specification.html#cb133-23" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb133-24"><a href="week-4-regression-ii-model-specification.html#cb133-24" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb133-25"><a href="week-4-regression-ii-model-specification.html#cb133-25" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb133-26"><a href="week-4-regression-ii-model-specification.html#cb133-26" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Political Preferences (left to right)&quot;</span>,</span>
<span id="cb133-27"><a href="week-4-regression-ii-model-specification.html#cb133-27" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relationship political preferences across ages by sex and language </span><span class="sc">\n</span><span class="st">(with interaction)&quot;</span></span>
<span id="cb133-28"><a href="week-4-regression-ii-model-specification.html#cb133-28" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-85-1.png" width="576" /></p>
</div>
<div id="simulated-data-1" class="section level3 hasAnchor" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> Simulated data<a href="week-4-regression-ii-model-specification.html#simulated-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>In order to see the logic behind the <span class="math inline">\(R^2\)</span>, you will simulate what happens to it under different circumstances. To begin with, generate a random normal distribution of <span class="math inline">\(X\)</span> and <span class="math inline">\(\epsilon\)</span> both with mean 0 and standard deviation of 1.</li>
</ol>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="week-4-regression-ii-model-specification.html#cb134-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># For reproducibility</span></span>
<span id="cb134-2"><a href="week-4-regression-ii-model-specification.html#cb134-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">X =</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>), <span class="at">epsilon =</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>))</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Generate values for <span class="math inline">\(Y\)</span> using the following data generating process. Graph it and regress <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span>.</li>
</ol>
<p><span class="math display">\[Y=1+2X+\epsilon\]</span></p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="week-4-regression-ii-model-specification.html#cb135-1" tabindex="-1"></a>df<span class="sc">$</span>Y <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>df<span class="sc">$</span>X<span class="sc">+</span>df<span class="sc">$</span>epsilon</span>
<span id="cb135-2"><a href="week-4-regression-ii-model-specification.html#cb135-2" tabindex="-1"></a></span>
<span id="cb135-3"><a href="week-4-regression-ii-model-specification.html#cb135-3" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> X, <span class="at">y =</span> Y)) <span class="sc">+</span></span>
<span id="cb135-4"><a href="week-4-regression-ii-model-specification.html#cb135-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x =</span> X, <span class="at">y =</span> Y), </span>
<span id="cb135-5"><a href="week-4-regression-ii-model-specification.html#cb135-5" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb135-6"><a href="week-4-regression-ii-model-specification.html#cb135-6" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-87-1.png" width="576" /></p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="week-4-regression-ii-model-specification.html#cb136-1" tabindex="-1"></a>result1 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Y <span class="sc">~</span> X, <span class="at">data =</span> df)</span>
<span id="cb136-2"><a href="week-4-regression-ii-model-specification.html#cb136-2" tabindex="-1"></a><span class="fu">coef</span>(result1)</span></code></pre></div>
<pre><code>## (Intercept)           X 
##    1.119243    2.043244</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Now generate the normally distributed residuals with mean zero and variance equal to 5, 4, 3, 2, 1/2, 1/3, 1/4, and 1/5. Use each residual to create a new <span class="math inline">\(Y\)</span>. Then, keeping the same <span class="math inline">\(X\)</span> unchanged, regress all the resulting <span class="math inline">\(Y\)</span>s on <span class="math inline">\(X\)</span>. Present all the resulting <span class="math inline">\(R^2\)</span> in a new dataframe to then graph the relation between the variance of the residual and the <span class="math inline">\(R^2\)</span>. What lesson do you take out of this graph?</li>
</ol>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="week-4-regression-ii-model-specification.html#cb138-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># For reproducibility</span></span>
<span id="cb138-2"><a href="week-4-regression-ii-model-specification.html#cb138-2" tabindex="-1"></a>df<span class="sc">$</span>ep5 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">5</span>)</span>
<span id="cb138-3"><a href="week-4-regression-ii-model-specification.html#cb138-3" tabindex="-1"></a>df<span class="sc">$</span>ep4 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">4</span>)</span>
<span id="cb138-4"><a href="week-4-regression-ii-model-specification.html#cb138-4" tabindex="-1"></a>df<span class="sc">$</span>ep3 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb138-5"><a href="week-4-regression-ii-model-specification.html#cb138-5" tabindex="-1"></a>df<span class="sc">$</span>ep2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb138-6"><a href="week-4-regression-ii-model-specification.html#cb138-6" tabindex="-1"></a>df<span class="sc">$</span>ep1_2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb138-7"><a href="week-4-regression-ii-model-specification.html#cb138-7" tabindex="-1"></a>df<span class="sc">$</span>ep1_3 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)</span>
<span id="cb138-8"><a href="week-4-regression-ii-model-specification.html#cb138-8" tabindex="-1"></a>df<span class="sc">$</span>ep1_4 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>)</span>
<span id="cb138-9"><a href="week-4-regression-ii-model-specification.html#cb138-9" tabindex="-1"></a>df<span class="sc">$</span>ep1_5 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>)</span>
<span id="cb138-10"><a href="week-4-regression-ii-model-specification.html#cb138-10" tabindex="-1"></a></span>
<span id="cb138-11"><a href="week-4-regression-ii-model-specification.html#cb138-11" tabindex="-1"></a>df<span class="sc">$</span>Y5 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>df<span class="sc">$</span>X<span class="sc">+</span>df<span class="sc">$</span>ep5</span>
<span id="cb138-12"><a href="week-4-regression-ii-model-specification.html#cb138-12" tabindex="-1"></a>df<span class="sc">$</span>Y4 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>df<span class="sc">$</span>X<span class="sc">+</span>df<span class="sc">$</span>ep4</span>
<span id="cb138-13"><a href="week-4-regression-ii-model-specification.html#cb138-13" tabindex="-1"></a>df<span class="sc">$</span>Y3 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>df<span class="sc">$</span>X<span class="sc">+</span>df<span class="sc">$</span>ep3</span>
<span id="cb138-14"><a href="week-4-regression-ii-model-specification.html#cb138-14" tabindex="-1"></a>df<span class="sc">$</span>Y2 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>df<span class="sc">$</span>X<span class="sc">+</span>df<span class="sc">$</span>ep2</span>
<span id="cb138-15"><a href="week-4-regression-ii-model-specification.html#cb138-15" tabindex="-1"></a>df<span class="sc">$</span>Y_2 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>df<span class="sc">$</span>X<span class="sc">+</span>df<span class="sc">$</span>ep1_2</span>
<span id="cb138-16"><a href="week-4-regression-ii-model-specification.html#cb138-16" tabindex="-1"></a>df<span class="sc">$</span>Y_3 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>df<span class="sc">$</span>X<span class="sc">+</span>df<span class="sc">$</span>ep1_3</span>
<span id="cb138-17"><a href="week-4-regression-ii-model-specification.html#cb138-17" tabindex="-1"></a>df<span class="sc">$</span>Y_4 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>df<span class="sc">$</span>X<span class="sc">+</span>df<span class="sc">$</span>ep1_4</span>
<span id="cb138-18"><a href="week-4-regression-ii-model-specification.html#cb138-18" tabindex="-1"></a>df<span class="sc">$</span>Y_5 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>df<span class="sc">$</span>X<span class="sc">+</span>df<span class="sc">$</span>ep1_5</span>
<span id="cb138-19"><a href="week-4-regression-ii-model-specification.html#cb138-19" tabindex="-1"></a></span>
<span id="cb138-20"><a href="week-4-regression-ii-model-specification.html#cb138-20" tabindex="-1"></a>result5 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Y5 <span class="sc">~</span> X, <span class="at">data =</span> df)</span>
<span id="cb138-21"><a href="week-4-regression-ii-model-specification.html#cb138-21" tabindex="-1"></a>result4 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Y4 <span class="sc">~</span> X, <span class="at">data =</span> df)</span>
<span id="cb138-22"><a href="week-4-regression-ii-model-specification.html#cb138-22" tabindex="-1"></a>result3 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Y3 <span class="sc">~</span> X, <span class="at">data =</span> df)</span>
<span id="cb138-23"><a href="week-4-regression-ii-model-specification.html#cb138-23" tabindex="-1"></a>result2 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Y2 <span class="sc">~</span> X, <span class="at">data =</span> df)</span>
<span id="cb138-24"><a href="week-4-regression-ii-model-specification.html#cb138-24" tabindex="-1"></a>result_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Y_2 <span class="sc">~</span> X, <span class="at">data =</span> df)</span>
<span id="cb138-25"><a href="week-4-regression-ii-model-specification.html#cb138-25" tabindex="-1"></a>result_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Y_3 <span class="sc">~</span> X, <span class="at">data =</span> df)</span>
<span id="cb138-26"><a href="week-4-regression-ii-model-specification.html#cb138-26" tabindex="-1"></a>result_4 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Y_4 <span class="sc">~</span> X, <span class="at">data =</span> df)</span>
<span id="cb138-27"><a href="week-4-regression-ii-model-specification.html#cb138-27" tabindex="-1"></a>result_5 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Y_5 <span class="sc">~</span> X, <span class="at">data =</span> df)</span>
<span id="cb138-28"><a href="week-4-regression-ii-model-specification.html#cb138-28" tabindex="-1"></a></span>
<span id="cb138-29"><a href="week-4-regression-ii-model-specification.html#cb138-29" tabindex="-1"></a>df_rsqrd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb138-30"><a href="week-4-regression-ii-model-specification.html#cb138-30" tabindex="-1"></a>  <span class="at">SD =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>),</span>
<span id="cb138-31"><a href="week-4-regression-ii-model-specification.html#cb138-31" tabindex="-1"></a>  <span class="at">R2 =</span> <span class="fu">c</span>(<span class="fu">summary</span>(result5)<span class="sc">$</span>r.squared,</span>
<span id="cb138-32"><a href="week-4-regression-ii-model-specification.html#cb138-32" tabindex="-1"></a>         <span class="fu">summary</span>(result4)<span class="sc">$</span>r.squared,</span>
<span id="cb138-33"><a href="week-4-regression-ii-model-specification.html#cb138-33" tabindex="-1"></a>         <span class="fu">summary</span>(result3)<span class="sc">$</span>r.squared,</span>
<span id="cb138-34"><a href="week-4-regression-ii-model-specification.html#cb138-34" tabindex="-1"></a>         <span class="fu">summary</span>(result2)<span class="sc">$</span>r.squared,</span>
<span id="cb138-35"><a href="week-4-regression-ii-model-specification.html#cb138-35" tabindex="-1"></a>         <span class="fu">summary</span>(result1)<span class="sc">$</span>r.squared,</span>
<span id="cb138-36"><a href="week-4-regression-ii-model-specification.html#cb138-36" tabindex="-1"></a>         <span class="fu">summary</span>(result_2)<span class="sc">$</span>r.squared,</span>
<span id="cb138-37"><a href="week-4-regression-ii-model-specification.html#cb138-37" tabindex="-1"></a>         <span class="fu">summary</span>(result_3)<span class="sc">$</span>r.squared,</span>
<span id="cb138-38"><a href="week-4-regression-ii-model-specification.html#cb138-38" tabindex="-1"></a>         <span class="fu">summary</span>(result_4)<span class="sc">$</span>r.squared,</span>
<span id="cb138-39"><a href="week-4-regression-ii-model-specification.html#cb138-39" tabindex="-1"></a>         <span class="fu">summary</span>(result_5)<span class="sc">$</span>r.squared)</span>
<span id="cb138-40"><a href="week-4-regression-ii-model-specification.html#cb138-40" tabindex="-1"></a>        )</span>
<span id="cb138-41"><a href="week-4-regression-ii-model-specification.html#cb138-41" tabindex="-1"></a></span>
<span id="cb138-42"><a href="week-4-regression-ii-model-specification.html#cb138-42" tabindex="-1"></a><span class="fu">ggplot</span>(df_rsqrd, <span class="fu">aes</span>(<span class="at">x =</span> SD, <span class="at">y =</span> R2)) <span class="sc">+</span></span>
<span id="cb138-43"><a href="week-4-regression-ii-model-specification.html#cb138-43" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> df_rsqrd, <span class="fu">aes</span>(<span class="at">x =</span> SD, <span class="at">y =</span> R2), </span>
<span id="cb138-44"><a href="week-4-regression-ii-model-specification.html#cb138-44" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb138-45"><a href="week-4-regression-ii-model-specification.html#cb138-45" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-89-1.png" width="576" /></p>
<p>As shown in <a href="https://en.wikipedia.org/wiki/Coefficient_of_determination">this</a> entry, the bigger the sum of squared residuals is as a share of the regressand’s variance, the less capable out model to capture the relation between our regressand and regressor. Thus, as the graph shows, the smaller variance of the residual, the higher the <span class="math inline">\(R^2\)</span>. In other words, the more dispersed observations are around <em>each section of the regression line</em>, the lower the goodness of fit our model has to describe our data.</p>
<ol start="3" style="list-style-type: decimal">
<li>In order to see the logic behind the <span class="math inline">\(R^2\)</span>, first estimate the linear regression of <code>LeftToRight</code> on <code>Age</code>. Generate the variable <code>predicted_LeftToRight</code> with the generated parameters using <a href="https://www.statology.org/r-lm-predict/"><code>predict()</code></a> from the point 3 of the previous section (i.e., the one using real data).Generate the graph <code>predicted_LeftToRight</code> vs <code>Age</code>.</li>
</ol>
<p>Report the regression here.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="week-4-regression-ii-model-specification.html#cb139-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(LeftToRight <span class="sc">~</span> age, <span class="at">data =</span> selects19)</span>
<span id="cb139-2"><a href="week-4-regression-ii-model-specification.html#cb139-2" tabindex="-1"></a>selects19<span class="sc">$</span>predicted_LeftToRight <span class="ot">&lt;-</span> <span class="fu">predict</span>(result)</span>
<span id="cb139-3"><a href="week-4-regression-ii-model-specification.html#cb139-3" tabindex="-1"></a></span>
<span id="cb139-4"><a href="week-4-regression-ii-model-specification.html#cb139-4" tabindex="-1"></a>coeffs1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(result)</span>
<span id="cb139-5"><a href="week-4-regression-ii-model-specification.html#cb139-5" tabindex="-1"></a>rsq_sd1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(result)<span class="sc">$</span>r.squared</span>
<span id="cb139-6"><a href="week-4-regression-ii-model-specification.html#cb139-6" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&#39;The R2 is: &#39;</span>, rsq_sd1, <span class="st">&#39;</span><span class="sc">\n\n</span><span class="st">Intercept:&#39;</span>,<span class="fu">unname</span>(coeffs1[<span class="dv">1</span>]), <span class="st">&#39;</span><span class="sc">\n\n</span><span class="st">Slope:&#39;</span>, <span class="fu">unname</span>(coeffs1[<span class="dv">2</span>]))</span></code></pre></div>
<pre><code>## The R2 is:  0.0161515 
## 
## Intercept: 4.122055 
## 
## Slope: 0.01948902</code></pre>
<p>Report the graph here.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="week-4-regression-ii-model-specification.html#cb141-1" tabindex="-1"></a><span class="co"># Calculate means for Y and X</span></span>
<span id="cb141-2"><a href="week-4-regression-ii-model-specification.html#cb141-2" tabindex="-1"></a>mean_LeftRight <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>LeftToRight, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb141-3"><a href="week-4-regression-ii-model-specification.html#cb141-3" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb141-4"><a href="week-4-regression-ii-model-specification.html#cb141-4" tabindex="-1"></a></span>
<span id="cb141-5"><a href="week-4-regression-ii-model-specification.html#cb141-5" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb141-6"><a href="week-4-regression-ii-model-specification.html#cb141-6" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> predicted_LeftToRight)) <span class="sc">+</span></span>
<span id="cb141-7"><a href="week-4-regression-ii-model-specification.html#cb141-7" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb141-8"><a href="week-4-regression-ii-model-specification.html#cb141-8" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_LeftRight, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb141-9"><a href="week-4-regression-ii-model-specification.html#cb141-9" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_age, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb141-10"><a href="week-4-regression-ii-model-specification.html#cb141-10" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb141-11"><a href="week-4-regression-ii-model-specification.html#cb141-11" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>),</span>
<span id="cb141-12"><a href="week-4-regression-ii-model-specification.html#cb141-12" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb141-13"><a href="week-4-regression-ii-model-specification.html#cb141-13" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb141-14"><a href="week-4-regression-ii-model-specification.html#cb141-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb141-15"><a href="week-4-regression-ii-model-specification.html#cb141-15" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb141-16"><a href="week-4-regression-ii-model-specification.html#cb141-16" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>), <span class="co"># Center the plot title</span></span>
<span id="cb141-17"><a href="week-4-regression-ii-model-specification.html#cb141-17" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">size =</span> <span class="fl">0.5</span>), <span class="co"># Style for major Y grid lines</span></span>
<span id="cb141-18"><a href="week-4-regression-ii-model-specification.html#cb141-18" tabindex="-1"></a>    <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>() <span class="co"># Remove minor Y grid lines</span></span>
<span id="cb141-19"><a href="week-4-regression-ii-model-specification.html#cb141-19" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb141-20"><a href="week-4-regression-ii-model-specification.html#cb141-20" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb141-21"><a href="week-4-regression-ii-model-specification.html#cb141-21" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb141-22"><a href="week-4-regression-ii-model-specification.html#cb141-22" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Political Preferences (left to right)&quot;</span>,</span>
<span id="cb141-23"><a href="week-4-regression-ii-model-specification.html#cb141-23" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot Age vs. Political Preferences (determ. sim.)&quot;</span></span>
<span id="cb141-24"><a href="week-4-regression-ii-model-specification.html#cb141-24" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-91-1.png" width="576" /></p>
<ol start="4" style="list-style-type: decimal">
<li>Now generate the normally distributed residuals with mean zero and the same variance as the residuals of the model from the previous point.</li>
</ol>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="week-4-regression-ii-model-specification.html#cb142-1" tabindex="-1"></a><span class="co"># Calculate the variance of the residuals</span></span>
<span id="cb142-2"><a href="week-4-regression-ii-model-specification.html#cb142-2" tabindex="-1"></a>selects19<span class="sc">$</span>residual <span class="ot">&lt;-</span> <span class="fu">resid</span>(result)</span>
<span id="cb142-3"><a href="week-4-regression-ii-model-specification.html#cb142-3" tabindex="-1"></a>residual_sd <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(<span class="fu">resid</span>(result)))</span>
<span id="cb142-4"><a href="week-4-regression-ii-model-specification.html#cb142-4" tabindex="-1"></a></span>
<span id="cb142-5"><a href="week-4-regression-ii-model-specification.html#cb142-5" tabindex="-1"></a><span class="co"># Set the seed for reproducibility</span></span>
<span id="cb142-6"><a href="week-4-regression-ii-model-specification.html#cb142-6" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0</span>)</span>
<span id="cb142-7"><a href="week-4-regression-ii-model-specification.html#cb142-7" tabindex="-1"></a>selects19<span class="sc">$</span>NormResiduals1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fu">nrow</span>(selects19), <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> residual_sd)</span></code></pre></div>
<ol start="5" style="list-style-type: decimal">
<li>Simulate new data using both the deterministic (i.e., the the parameters estimated immediately above) and stochastic component (i.e., the residuals form the previous point). Graph the simulated data.</li>
</ol>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="week-4-regression-ii-model-specification.html#cb143-1" tabindex="-1"></a>selects19<span class="sc">$</span>Sim_LeftToRight_Det_Stoch <span class="ot">&lt;-</span> selects19<span class="sc">$</span>predicted_LeftToRight <span class="sc">+</span> selects19<span class="sc">$</span>NormResiduals1</span>
<span id="cb143-2"><a href="week-4-regression-ii-model-specification.html#cb143-2" tabindex="-1"></a></span>
<span id="cb143-3"><a href="week-4-regression-ii-model-specification.html#cb143-3" tabindex="-1"></a><span class="co">#Means for Y and X</span></span>
<span id="cb143-4"><a href="week-4-regression-ii-model-specification.html#cb143-4" tabindex="-1"></a>mean_LeftRight <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>Sim_LeftToRight_Det_Stoch, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb143-5"><a href="week-4-regression-ii-model-specification.html#cb143-5" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb143-6"><a href="week-4-regression-ii-model-specification.html#cb143-6" tabindex="-1"></a></span>
<span id="cb143-7"><a href="week-4-regression-ii-model-specification.html#cb143-7" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb143-8"><a href="week-4-regression-ii-model-specification.html#cb143-8" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> Sim_LeftToRight_Det_Stoch)) <span class="sc">+</span></span>
<span id="cb143-9"><a href="week-4-regression-ii-model-specification.html#cb143-9" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb143-10"><a href="week-4-regression-ii-model-specification.html#cb143-10" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb143-11"><a href="week-4-regression-ii-model-specification.html#cb143-11" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_LeftRight, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb143-12"><a href="week-4-regression-ii-model-specification.html#cb143-12" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_age, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb143-13"><a href="week-4-regression-ii-model-specification.html#cb143-13" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb143-14"><a href="week-4-regression-ii-model-specification.html#cb143-14" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb143-15"><a href="week-4-regression-ii-model-specification.html#cb143-15" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb143-16"><a href="week-4-regression-ii-model-specification.html#cb143-16" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>),</span>
<span id="cb143-17"><a href="week-4-regression-ii-model-specification.html#cb143-17" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb143-18"><a href="week-4-regression-ii-model-specification.html#cb143-18" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb143-19"><a href="week-4-regression-ii-model-specification.html#cb143-19" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb143-20"><a href="week-4-regression-ii-model-specification.html#cb143-20" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>), <span class="co"># Center the plot title</span></span>
<span id="cb143-21"><a href="week-4-regression-ii-model-specification.html#cb143-21" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">size =</span> <span class="fl">0.5</span>), <span class="co"># Style for major Y grid lines</span></span>
<span id="cb143-22"><a href="week-4-regression-ii-model-specification.html#cb143-22" tabindex="-1"></a>    <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>() <span class="co"># Remove minor Y grid lines</span></span>
<span id="cb143-23"><a href="week-4-regression-ii-model-specification.html#cb143-23" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb143-24"><a href="week-4-regression-ii-model-specification.html#cb143-24" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb143-25"><a href="week-4-regression-ii-model-specification.html#cb143-25" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb143-26"><a href="week-4-regression-ii-model-specification.html#cb143-26" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Simulation: Political Preferences (left to right)&quot;</span>,</span>
<span id="cb143-27"><a href="week-4-regression-ii-model-specification.html#cb143-27" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot Age vs. Political Preferences </span><span class="sc">\n</span><span class="st">(determ.&amp; stoch. sim.)&quot;</span></span>
<span id="cb143-28"><a href="week-4-regression-ii-model-specification.html#cb143-28" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-93-1.png" width="576" /></p>
<ol start="5" style="list-style-type: decimal">
<li>Now, estimate the regression between the real <code>age</code> and simulated <code>Sim_LeftToRight_Det_Stoch</code>. Once you do that, generate the <span class="math inline">\(R^2\)</span> for the model.</li>
</ol>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="week-4-regression-ii-model-specification.html#cb144-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(LeftToRight <span class="sc">~</span> age, <span class="at">data =</span> selects19)</span>
<span id="cb144-2"><a href="week-4-regression-ii-model-specification.html#cb144-2" tabindex="-1"></a>rsq_sd1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(result)<span class="sc">$</span>r.squared</span>
<span id="cb144-3"><a href="week-4-regression-ii-model-specification.html#cb144-3" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&#39;The R2 is: &#39;</span>, rsq_sd1)</span></code></pre></div>
<pre><code>## The R2 is:  0.0161515</code></pre>
<ol start="7" style="list-style-type: decimal">
<li>Repeat the previous three points but use half the standard deviation of the model of point 1. Is the <span class="math inline">\(R^2\)</span> lower now? Why? See <a href="https://en.wikipedia.org/wiki/Coefficient_of_determination">this</a> entry to understand the intuition: pay special attention to the graph with the red and blue squares.</li>
</ol>
<p>Generate the residuals here.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="week-4-regression-ii-model-specification.html#cb146-1" tabindex="-1"></a><span class="co"># Set the seed for reproducibility</span></span>
<span id="cb146-2"><a href="week-4-regression-ii-model-specification.html#cb146-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0</span>)</span>
<span id="cb146-3"><a href="week-4-regression-ii-model-specification.html#cb146-3" tabindex="-1"></a>selects19<span class="sc">$</span>NormResiduals10 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fu">nrow</span>(selects19), <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> residual_sd<span class="sc">*</span><span class="fl">0.1</span>)</span></code></pre></div>
<p>Simulate new data and graph it here.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="week-4-regression-ii-model-specification.html#cb147-1" tabindex="-1"></a>selects19<span class="sc">$</span>Sim_LeftToRight_Det_Stoch_sd10 <span class="ot">&lt;-</span> selects19<span class="sc">$</span>predicted_LeftToRight <span class="sc">+</span> selects19<span class="sc">$</span>NormResiduals10</span>
<span id="cb147-2"><a href="week-4-regression-ii-model-specification.html#cb147-2" tabindex="-1"></a></span>
<span id="cb147-3"><a href="week-4-regression-ii-model-specification.html#cb147-3" tabindex="-1"></a><span class="co">#Means for Y and X</span></span>
<span id="cb147-4"><a href="week-4-regression-ii-model-specification.html#cb147-4" tabindex="-1"></a>mean_LeftRight <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>Sim_LeftToRight_Det_Stoch_sd10, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb147-5"><a href="week-4-regression-ii-model-specification.html#cb147-5" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb147-6"><a href="week-4-regression-ii-model-specification.html#cb147-6" tabindex="-1"></a></span>
<span id="cb147-7"><a href="week-4-regression-ii-model-specification.html#cb147-7" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb147-8"><a href="week-4-regression-ii-model-specification.html#cb147-8" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> Sim_LeftToRight_Det_Stoch_sd10)) <span class="sc">+</span></span>
<span id="cb147-9"><a href="week-4-regression-ii-model-specification.html#cb147-9" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb147-10"><a href="week-4-regression-ii-model-specification.html#cb147-10" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb147-11"><a href="week-4-regression-ii-model-specification.html#cb147-11" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_LeftRight, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb147-12"><a href="week-4-regression-ii-model-specification.html#cb147-12" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_age, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb147-13"><a href="week-4-regression-ii-model-specification.html#cb147-13" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb147-14"><a href="week-4-regression-ii-model-specification.html#cb147-14" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>),</span>
<span id="cb147-15"><a href="week-4-regression-ii-model-specification.html#cb147-15" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb147-16"><a href="week-4-regression-ii-model-specification.html#cb147-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb147-17"><a href="week-4-regression-ii-model-specification.html#cb147-17" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb147-18"><a href="week-4-regression-ii-model-specification.html#cb147-18" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb147-19"><a href="week-4-regression-ii-model-specification.html#cb147-19" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb147-20"><a href="week-4-regression-ii-model-specification.html#cb147-20" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Simulated data (half sd): Political Preferences (left to right)&quot;</span>,</span>
<span id="cb147-21"><a href="week-4-regression-ii-model-specification.html#cb147-21" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot Age vs. Political Preferences&quot;</span></span>
<span id="cb147-22"><a href="week-4-regression-ii-model-specification.html#cb147-22" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-96-1.png" width="576" /></p>
<p>Report the new <span class="math inline">\(R^2\)</span> here:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="week-4-regression-ii-model-specification.html#cb148-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sim_LeftToRight_Det_Stoch_sd10 <span class="sc">~</span> age, <span class="at">data =</span> selects19)</span>
<span id="cb148-2"><a href="week-4-regression-ii-model-specification.html#cb148-2" tabindex="-1"></a>rsq_sd10 <span class="ot">&lt;-</span> <span class="fu">summary</span>(result)<span class="sc">$</span>r.squared</span>
<span id="cb148-3"><a href="week-4-regression-ii-model-specification.html#cb148-3" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&#39;The R2 is: &#39;</span>, rsq_sd10)</span></code></pre></div>
<pre><code>## The R2 is:  0.625503</code></pre>
<ol start="8" style="list-style-type: decimal">
<li>Repeat the previous point but use a hundredth the standard deviation of the model of point 1. Is the <span class="math inline">\(R^2\)</span> lower now? Why?</li>
</ol>
<p>Generate the residuals here.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="week-4-regression-ii-model-specification.html#cb150-1" tabindex="-1"></a><span class="co"># Set the seed for reproducibility</span></span>
<span id="cb150-2"><a href="week-4-regression-ii-model-specification.html#cb150-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0</span>)</span>
<span id="cb150-3"><a href="week-4-regression-ii-model-specification.html#cb150-3" tabindex="-1"></a>selects19<span class="sc">$</span>NormResiduals100 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fu">nrow</span>(selects19), <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> residual_sd<span class="sc">*</span><span class="fl">0.01</span>)</span></code></pre></div>
<p>Simulate new data and graph it here.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="week-4-regression-ii-model-specification.html#cb151-1" tabindex="-1"></a>selects19<span class="sc">$</span>Sim_LeftToRight_Det_Stoch_hsd <span class="ot">&lt;-</span> selects19<span class="sc">$</span>predicted_LeftToRight <span class="sc">+</span> selects19<span class="sc">$</span>NormResiduals100</span>
<span id="cb151-2"><a href="week-4-regression-ii-model-specification.html#cb151-2" tabindex="-1"></a></span>
<span id="cb151-3"><a href="week-4-regression-ii-model-specification.html#cb151-3" tabindex="-1"></a><span class="co">#Means for Y and X</span></span>
<span id="cb151-4"><a href="week-4-regression-ii-model-specification.html#cb151-4" tabindex="-1"></a>mean_LeftRight <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>Sim_LeftToRight_Det_Stoch_hsd, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb151-5"><a href="week-4-regression-ii-model-specification.html#cb151-5" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb151-6"><a href="week-4-regression-ii-model-specification.html#cb151-6" tabindex="-1"></a></span>
<span id="cb151-7"><a href="week-4-regression-ii-model-specification.html#cb151-7" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb151-8"><a href="week-4-regression-ii-model-specification.html#cb151-8" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> Sim_LeftToRight_Det_Stoch_hsd)) <span class="sc">+</span></span>
<span id="cb151-9"><a href="week-4-regression-ii-model-specification.html#cb151-9" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb151-10"><a href="week-4-regression-ii-model-specification.html#cb151-10" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb151-11"><a href="week-4-regression-ii-model-specification.html#cb151-11" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_LeftRight, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb151-12"><a href="week-4-regression-ii-model-specification.html#cb151-12" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_age, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb151-13"><a href="week-4-regression-ii-model-specification.html#cb151-13" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb151-14"><a href="week-4-regression-ii-model-specification.html#cb151-14" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>),</span>
<span id="cb151-15"><a href="week-4-regression-ii-model-specification.html#cb151-15" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb151-16"><a href="week-4-regression-ii-model-specification.html#cb151-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb151-17"><a href="week-4-regression-ii-model-specification.html#cb151-17" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb151-18"><a href="week-4-regression-ii-model-specification.html#cb151-18" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb151-19"><a href="week-4-regression-ii-model-specification.html#cb151-19" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb151-20"><a href="week-4-regression-ii-model-specification.html#cb151-20" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Simulated data (half sd): Political Preferences (left to right)&quot;</span>,</span>
<span id="cb151-21"><a href="week-4-regression-ii-model-specification.html#cb151-21" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot Age vs. Political Preferences&quot;</span></span>
<span id="cb151-22"><a href="week-4-regression-ii-model-specification.html#cb151-22" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-99-1.png" width="576" /></p>
<p>Report the new <span class="math inline">\(R^2\)</span> here:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="week-4-regression-ii-model-specification.html#cb152-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sim_LeftToRight_Det_Stoch_hsd <span class="sc">~</span> age, <span class="at">data =</span> selects19)</span>
<span id="cb152-2"><a href="week-4-regression-ii-model-specification.html#cb152-2" tabindex="-1"></a>rsq_sd100 <span class="ot">&lt;-</span> <span class="fu">summary</span>(result)<span class="sc">$</span>r.squared</span>
<span id="cb152-3"><a href="week-4-regression-ii-model-specification.html#cb152-3" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&#39;The R2 is: &#39;</span>, rsq_sd100)</span></code></pre></div>
<pre><code>## The R2 is:  0.9939772</code></pre>
<ol start="9" style="list-style-type: decimal">
<li>Present in a table the <span class="math inline">\(R^2\)</span> for each value of the standard deviation.</li>
</ol>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="week-4-regression-ii-model-specification.html#cb154-1" tabindex="-1"></a>table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb154-2"><a href="week-4-regression-ii-model-specification.html#cb154-2" tabindex="-1"></a>  <span class="at">SD =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="fl">0.01</span>),</span>
<span id="cb154-3"><a href="week-4-regression-ii-model-specification.html#cb154-3" tabindex="-1"></a>  <span class="at">R2 =</span> <span class="fu">c</span>(rsq_sd1, rsq_sd10, rsq_sd100)    <span class="co"># Replace these with the actual R-squared values</span></span>
<span id="cb154-4"><a href="week-4-regression-ii-model-specification.html#cb154-4" tabindex="-1"></a>)</span>
<span id="cb154-5"><a href="week-4-regression-ii-model-specification.html#cb154-5" tabindex="-1"></a></span>
<span id="cb154-6"><a href="week-4-regression-ii-model-specification.html#cb154-6" tabindex="-1"></a><span class="fu">print</span>(table)</span></code></pre></div>
<pre><code>##     SD        R2
## 1 1.00 0.0161515
## 2 0.10 0.6255030
## 3 0.01 0.9939772</code></pre>
<ol start="10" style="list-style-type: decimal">
<li>Graph <span class="math inline">\(R^2\)</span> agains the standard deviation fraction. Fit a linear regression line.</li>
</ol>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="week-4-regression-ii-model-specification.html#cb156-1" tabindex="-1"></a><span class="fu">ggplot</span>(table, <span class="fu">aes</span>(<span class="at">x =</span> SD, <span class="at">y =</span> R2)) <span class="sc">+</span></span>
<span id="cb156-2"><a href="week-4-regression-ii-model-specification.html#cb156-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb156-3"><a href="week-4-regression-ii-model-specification.html#cb156-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>)<span class="sc">+</span></span>
<span id="cb156-4"><a href="week-4-regression-ii-model-specification.html#cb156-4" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb156-5"><a href="week-4-regression-ii-model-specification.html#cb156-5" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb156-6"><a href="week-4-regression-ii-model-specification.html#cb156-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb156-7"><a href="week-4-regression-ii-model-specification.html#cb156-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Fraction of standard deviation&quot;</span>,</span>
<span id="cb156-8"><a href="week-4-regression-ii-model-specification.html#cb156-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;R2&quot;</span>,</span>
<span id="cb156-9"><a href="week-4-regression-ii-model-specification.html#cb156-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relation between R2 and standard deviation of residuals&quot;</span></span>
<span id="cb156-10"><a href="week-4-regression-ii-model-specification.html#cb156-10" tabindex="-1"></a>  ) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-102-1.png" width="576" />
11. [Optional] Graph <span class="math inline">\(R^2\)</span> against the standard deviation fraction. Fit a regression line with a polynomial of degree 2. The regression line fits the data better. Is the polynomial regression more informative than the linear regression? Why? What lesson does this graph give you in terms of the importance of understanding the theoretical relations between variables beyond what an empirical approach could suggest? What does it teach you regarding the tension between under- and over-fitting data?</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="week-4-regression-ii-model-specification.html#cb157-1" tabindex="-1"></a><span class="fu">ggplot</span>(table, <span class="fu">aes</span>(<span class="at">x =</span> SD, <span class="at">y =</span> R2)) <span class="sc">+</span></span>
<span id="cb157-2"><a href="week-4-regression-ii-model-specification.html#cb157-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb157-3"><a href="week-4-regression-ii-model-specification.html#cb157-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">&#39;green&#39;</span>) <span class="sc">+</span></span>
<span id="cb157-4"><a href="week-4-regression-ii-model-specification.html#cb157-4" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb157-5"><a href="week-4-regression-ii-model-specification.html#cb157-5" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb157-6"><a href="week-4-regression-ii-model-specification.html#cb157-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb157-7"><a href="week-4-regression-ii-model-specification.html#cb157-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Fraction of standard deviation&quot;</span>,</span>
<span id="cb157-8"><a href="week-4-regression-ii-model-specification.html#cb157-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;R2&quot;</span>,</span>
<span id="cb157-9"><a href="week-4-regression-ii-model-specification.html#cb157-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relation between R2 and standard deviation of residuals&quot;</span></span>
<span id="cb157-10"><a href="week-4-regression-ii-model-specification.html#cb157-10" tabindex="-1"></a>  ) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-103-1.png" width="576" />
12. Print the parameters generated in the point 1. Generate the same predictions as in point 1 and 2 but this time multiply the slope’s parameter by 5, while keeping the intercept unchanged. Call the resulting predictions <code>predicted_LeftToRight_AdjSlope</code> Generate a graph with the regression line for <code>predicted_LeftToRight_AdjSlope</code> vs <code>Age</code> and compare it with the graph <code>predicted_LeftToRight</code> vs <code>Age</code> generated in point 1.</p>
<p>Print here</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="week-4-regression-ii-model-specification.html#cb158-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(LeftToRight <span class="sc">~</span> age, <span class="at">data =</span> selects19)</span>
<span id="cb158-2"><a href="week-4-regression-ii-model-specification.html#cb158-2" tabindex="-1"></a><span class="co"># summary(result)</span></span>
<span id="cb158-3"><a href="week-4-regression-ii-model-specification.html#cb158-3" tabindex="-1"></a>coeffs <span class="ot">&lt;-</span> <span class="fu">coef</span>(result)</span>
<span id="cb158-4"><a href="week-4-regression-ii-model-specification.html#cb158-4" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&#39;Intercept:&#39;</span>,<span class="fu">unname</span>(coeffs[<span class="dv">1</span>]), <span class="st">&#39;</span><span class="sc">\n\n</span><span class="st">Slope:&#39;</span>, <span class="fu">unname</span>(coeffs[<span class="dv">2</span>]))</span></code></pre></div>
<pre><code>## Intercept: 4.122055 
## 
## Slope: 0.01948902</code></pre>
<p>Predict with the adjusted slope here.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="week-4-regression-ii-model-specification.html#cb160-1" tabindex="-1"></a>selects19<span class="sc">$</span>predicted_LeftToRight_AdjSlope <span class="ot">&lt;-</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>])<span class="sc">+</span>(<span class="fu">unname</span>(coeffs[<span class="dv">2</span>])<span class="sc">*</span><span class="dv">5</span>)<span class="sc">*</span>selects19<span class="sc">$</span>age</span></code></pre></div>
<p>Generate the graph here.</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="week-4-regression-ii-model-specification.html#cb161-1" tabindex="-1"></a><span class="co">#Means for Y and X</span></span>
<span id="cb161-2"><a href="week-4-regression-ii-model-specification.html#cb161-2" tabindex="-1"></a>mean_LeftRight <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>predicted_LeftToRight_AdjSlope, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb161-3"><a href="week-4-regression-ii-model-specification.html#cb161-3" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb161-4"><a href="week-4-regression-ii-model-specification.html#cb161-4" tabindex="-1"></a></span>
<span id="cb161-5"><a href="week-4-regression-ii-model-specification.html#cb161-5" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb161-6"><a href="week-4-regression-ii-model-specification.html#cb161-6" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> predicted_LeftToRight_AdjSlope)) <span class="sc">+</span></span>
<span id="cb161-7"><a href="week-4-regression-ii-model-specification.html#cb161-7" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb161-8"><a href="week-4-regression-ii-model-specification.html#cb161-8" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_LeftRight, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb161-9"><a href="week-4-regression-ii-model-specification.html#cb161-9" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_age, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb161-10"><a href="week-4-regression-ii-model-specification.html#cb161-10" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb161-11"><a href="week-4-regression-ii-model-specification.html#cb161-11" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb161-12"><a href="week-4-regression-ii-model-specification.html#cb161-12" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb161-13"><a href="week-4-regression-ii-model-specification.html#cb161-13" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">15</span>),</span>
<span id="cb161-14"><a href="week-4-regression-ii-model-specification.html#cb161-14" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb161-15"><a href="week-4-regression-ii-model-specification.html#cb161-15" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb161-16"><a href="week-4-regression-ii-model-specification.html#cb161-16" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb161-17"><a href="week-4-regression-ii-model-specification.html#cb161-17" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>), <span class="co"># Center the plot title</span></span>
<span id="cb161-18"><a href="week-4-regression-ii-model-specification.html#cb161-18" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">size =</span> <span class="fl">0.5</span>), <span class="co"># Style for major Y grid lines</span></span>
<span id="cb161-19"><a href="week-4-regression-ii-model-specification.html#cb161-19" tabindex="-1"></a>    <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>() <span class="co"># Remove minor Y grid lines</span></span>
<span id="cb161-20"><a href="week-4-regression-ii-model-specification.html#cb161-20" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb161-21"><a href="week-4-regression-ii-model-specification.html#cb161-21" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb161-22"><a href="week-4-regression-ii-model-specification.html#cb161-22" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb161-23"><a href="week-4-regression-ii-model-specification.html#cb161-23" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Political Preferences (left to right)&quot;</span>,</span>
<span id="cb161-24"><a href="week-4-regression-ii-model-specification.html#cb161-24" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot Age vs. Political Preferences (adj. slope)&quot;</span></span>
<span id="cb161-25"><a href="week-4-regression-ii-model-specification.html#cb161-25" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-106-1.png" width="576" />
13. Add to the deterministic simulation the same stochastic component generated in point 2. Call that variable <code>predicted_LeftToRight_AdjSlope_Stoch</code>. Generate the graph <code>predicted_LeftToRight_AdjSlope_Stoch</code> vs <code>age</code> with a linear regression line. Generate the <span class="math inline">\(R^2\)</span> and compare it to the one generated in point 4. Why is the new <span class="math inline">\(R^2\)</span> higher than the one in point 4?</p>
<p>Report the simulation and the graph here.</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="week-4-regression-ii-model-specification.html#cb162-1" tabindex="-1"></a>selects19<span class="sc">$</span>predicted_LeftToRight_AdjSlope_Stoch <span class="ot">&lt;-</span> selects19<span class="sc">$</span>predicted_LeftToRight_AdjSlope <span class="sc">+</span> selects19<span class="sc">$</span>NormResiduals1</span>
<span id="cb162-2"><a href="week-4-regression-ii-model-specification.html#cb162-2" tabindex="-1"></a></span>
<span id="cb162-3"><a href="week-4-regression-ii-model-specification.html#cb162-3" tabindex="-1"></a><span class="co">#Means for Y and X</span></span>
<span id="cb162-4"><a href="week-4-regression-ii-model-specification.html#cb162-4" tabindex="-1"></a>mean_LeftRight <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>predicted_LeftToRight_AdjSlope_Stoch, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb162-5"><a href="week-4-regression-ii-model-specification.html#cb162-5" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb162-6"><a href="week-4-regression-ii-model-specification.html#cb162-6" tabindex="-1"></a></span>
<span id="cb162-7"><a href="week-4-regression-ii-model-specification.html#cb162-7" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb162-8"><a href="week-4-regression-ii-model-specification.html#cb162-8" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> predicted_LeftToRight_AdjSlope_Stoch)) <span class="sc">+</span></span>
<span id="cb162-9"><a href="week-4-regression-ii-model-specification.html#cb162-9" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb162-10"><a href="week-4-regression-ii-model-specification.html#cb162-10" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb162-11"><a href="week-4-regression-ii-model-specification.html#cb162-11" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_LeftRight, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb162-12"><a href="week-4-regression-ii-model-specification.html#cb162-12" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_age, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb162-13"><a href="week-4-regression-ii-model-specification.html#cb162-13" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb162-14"><a href="week-4-regression-ii-model-specification.html#cb162-14" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20</span>),</span>
<span id="cb162-15"><a href="week-4-regression-ii-model-specification.html#cb162-15" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb162-16"><a href="week-4-regression-ii-model-specification.html#cb162-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb162-17"><a href="week-4-regression-ii-model-specification.html#cb162-17" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb162-18"><a href="week-4-regression-ii-model-specification.html#cb162-18" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>), <span class="co"># Center the plot title</span></span>
<span id="cb162-19"><a href="week-4-regression-ii-model-specification.html#cb162-19" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">size =</span> <span class="fl">0.5</span>), <span class="co"># Style for major Y grid lines</span></span>
<span id="cb162-20"><a href="week-4-regression-ii-model-specification.html#cb162-20" tabindex="-1"></a>    <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>() <span class="co"># Remove minor Y grid lines</span></span>
<span id="cb162-21"><a href="week-4-regression-ii-model-specification.html#cb162-21" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb162-22"><a href="week-4-regression-ii-model-specification.html#cb162-22" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb162-23"><a href="week-4-regression-ii-model-specification.html#cb162-23" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb162-24"><a href="week-4-regression-ii-model-specification.html#cb162-24" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Simulation: Political Preferences (left to right)&quot;</span>,</span>
<span id="cb162-25"><a href="week-4-regression-ii-model-specification.html#cb162-25" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot Age vs. Political Preferences </span><span class="sc">\n</span><span class="st">(determ.&amp; stoch. sim. with adjusted slope)&quot;</span></span>
<span id="cb162-26"><a href="week-4-regression-ii-model-specification.html#cb162-26" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-107-1.png" width="576" /></p>
<p>Report the new <span class="math inline">\(R^2\)</span> here:</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="week-4-regression-ii-model-specification.html#cb163-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(predicted_LeftToRight_AdjSlope_Stoch <span class="sc">~</span> age, <span class="at">data =</span> selects19)</span>
<span id="cb163-2"><a href="week-4-regression-ii-model-specification.html#cb163-2" tabindex="-1"></a>rsq_sd1_AdjSlope <span class="ot">&lt;-</span> <span class="fu">summary</span>(result)<span class="sc">$</span>r.squared</span>
<span id="cb163-3"><a href="week-4-regression-ii-model-specification.html#cb163-3" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&#39;The R2 is: &#39;</span>, rsq_sd1_AdjSlope)</span></code></pre></div>
<pre><code>## The R2 is:  0.2973214</code></pre>
<p>Report why is the new <span class="math inline">\(R^2\)</span> higher than the one in point 4?</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="week-4-regression-ii-model-specification.html#cb165-1" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&#39;The reason the R2 increased is that, while the distance from each observation to the regression line remained unchainged (i.e., the residual was kept unchanged), by increasing the slope of the generating process, the average distance between each observation and the average observation increased (i.e., Y</span><span class="sc">\&#39;</span><span class="st">s variance increased). See the graph with the red and blue squares mentioned in point 5.&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;The reason the R2 increased is that, while the distance from each observation to the regression line remained unchainged (i.e., the residual was kept unchanged), by increasing the slope of the generating process, the average distance between each observation and the average observation increased (i.e., Y&#39;s variance increased). See the graph with the red and blue squares mentioned in point 5.&quot;</code></pre>
<p>333333333333</p>
<ol start="14" style="list-style-type: decimal">
<li>Print the parameters generated in the point 1. Generate the same predictions as in point 1 and 2 but this time increase in two units the <em>intercept’s</em> parameter (not the <em>slope’s</em> parameter as in the point 10), while keeping the slope unchanged. Call the resulting predictions <code>predicted_LeftToRight_AdjSlope</code> Generate a graph with the regression line for <code>predicted_LeftToRight_AdjSlope</code> vs <code>Age</code> and compare it with the graph <code>predicted_LeftToRight</code> vs <code>Age</code> generated in point 1.</li>
</ol>
<p>Print here</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="week-4-regression-ii-model-specification.html#cb167-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(predicted_LeftToRight_AdjSlope_Stoch <span class="sc">~</span> age, <span class="at">data =</span> selects19)</span>
<span id="cb167-2"><a href="week-4-regression-ii-model-specification.html#cb167-2" tabindex="-1"></a><span class="co"># summary(result)</span></span>
<span id="cb167-3"><a href="week-4-regression-ii-model-specification.html#cb167-3" tabindex="-1"></a>coeffs12 <span class="ot">&lt;-</span> <span class="fu">coef</span>(result)</span>
<span id="cb167-4"><a href="week-4-regression-ii-model-specification.html#cb167-4" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&#39;Intercept:&#39;</span>,<span class="fu">unname</span>(coeffs12[<span class="dv">1</span>]), <span class="st">&#39;</span><span class="sc">\n\n</span><span class="st">Slope:&#39;</span>, <span class="fu">unname</span>(coeffs12[<span class="dv">2</span>]))</span></code></pre></div>
<pre><code>## Intercept: 4.071965 
## 
## Slope: 0.09874777</code></pre>
<p>Predict with the adjusted slope here.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="week-4-regression-ii-model-specification.html#cb169-1" tabindex="-1"></a>selects19<span class="sc">$</span>predicted_LeftToRight_AdjIntecept <span class="ot">&lt;-</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]<span class="sc">+</span><span class="dv">2</span>)<span class="sc">+</span>(<span class="fu">unname</span>(coeffs[<span class="dv">2</span>]))<span class="sc">*</span>selects19<span class="sc">$</span>age</span></code></pre></div>
<p>Generate the graph here.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="week-4-regression-ii-model-specification.html#cb170-1" tabindex="-1"></a><span class="co">#Means for Y and X</span></span>
<span id="cb170-2"><a href="week-4-regression-ii-model-specification.html#cb170-2" tabindex="-1"></a>mean_LeftRight <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>predicted_LeftToRight_AdjIntecept, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb170-3"><a href="week-4-regression-ii-model-specification.html#cb170-3" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb170-4"><a href="week-4-regression-ii-model-specification.html#cb170-4" tabindex="-1"></a></span>
<span id="cb170-5"><a href="week-4-regression-ii-model-specification.html#cb170-5" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb170-6"><a href="week-4-regression-ii-model-specification.html#cb170-6" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> predicted_LeftToRight_AdjIntecept)) <span class="sc">+</span></span>
<span id="cb170-7"><a href="week-4-regression-ii-model-specification.html#cb170-7" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb170-8"><a href="week-4-regression-ii-model-specification.html#cb170-8" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_LeftRight, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb170-9"><a href="week-4-regression-ii-model-specification.html#cb170-9" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_age, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb170-10"><a href="week-4-regression-ii-model-specification.html#cb170-10" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb170-11"><a href="week-4-regression-ii-model-specification.html#cb170-11" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb170-12"><a href="week-4-regression-ii-model-specification.html#cb170-12" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb170-13"><a href="week-4-regression-ii-model-specification.html#cb170-13" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">15</span>),</span>
<span id="cb170-14"><a href="week-4-regression-ii-model-specification.html#cb170-14" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">15</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb170-15"><a href="week-4-regression-ii-model-specification.html#cb170-15" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb170-16"><a href="week-4-regression-ii-model-specification.html#cb170-16" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb170-17"><a href="week-4-regression-ii-model-specification.html#cb170-17" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>), <span class="co"># Center the plot title</span></span>
<span id="cb170-18"><a href="week-4-regression-ii-model-specification.html#cb170-18" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">size =</span> <span class="fl">0.5</span>), <span class="co"># Style for major Y grid lines</span></span>
<span id="cb170-19"><a href="week-4-regression-ii-model-specification.html#cb170-19" tabindex="-1"></a>    <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>() <span class="co"># Remove minor Y grid lines</span></span>
<span id="cb170-20"><a href="week-4-regression-ii-model-specification.html#cb170-20" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb170-21"><a href="week-4-regression-ii-model-specification.html#cb170-21" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb170-22"><a href="week-4-regression-ii-model-specification.html#cb170-22" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb170-23"><a href="week-4-regression-ii-model-specification.html#cb170-23" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Political Preferences (left to right)&quot;</span>,</span>
<span id="cb170-24"><a href="week-4-regression-ii-model-specification.html#cb170-24" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot Age vs. Political Preferences (adj. slope)&quot;</span></span>
<span id="cb170-25"><a href="week-4-regression-ii-model-specification.html#cb170-25" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-112-1.png" width="576" />
15. Add to the deterministic simulation the same stochastic component generated in point 2. Call that variable <code>predicted_LeftToRight_AdjIntercep_Stoch</code>. Generate the graph <code>predicted_LeftToRight_AdjIntecept</code> vs <code>age</code> with a linear regression line. Generate the <span class="math inline">\(R^2\)</span> and compare it to the one generated in point 4. Why is the new <span class="math inline">\(R^2\)</span> higher than the one in point 4?</p>
<p>Report the simulation and the graph here.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="week-4-regression-ii-model-specification.html#cb171-1" tabindex="-1"></a>selects19<span class="sc">$</span>predicted_LeftToRight_AdjIntercept_Stoch <span class="ot">&lt;-</span> selects19<span class="sc">$</span>predicted_LeftToRight_AdjIntecept <span class="sc">+</span> selects19<span class="sc">$</span>residual</span>
<span id="cb171-2"><a href="week-4-regression-ii-model-specification.html#cb171-2" tabindex="-1"></a></span>
<span id="cb171-3"><a href="week-4-regression-ii-model-specification.html#cb171-3" tabindex="-1"></a><span class="co">#Means for Y and X</span></span>
<span id="cb171-4"><a href="week-4-regression-ii-model-specification.html#cb171-4" tabindex="-1"></a>mean_LeftRight <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>predicted_LeftToRight_AdjIntercept_Stoch, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb171-5"><a href="week-4-regression-ii-model-specification.html#cb171-5" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(selects19<span class="sc">$</span>age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb171-6"><a href="week-4-regression-ii-model-specification.html#cb171-6" tabindex="-1"></a></span>
<span id="cb171-7"><a href="week-4-regression-ii-model-specification.html#cb171-7" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb171-8"><a href="week-4-regression-ii-model-specification.html#cb171-8" tabindex="-1"></a><span class="fu">ggplot</span>(selects19, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> predicted_LeftToRight_AdjIntercept_Stoch)) <span class="sc">+</span></span>
<span id="cb171-9"><a href="week-4-regression-ii-model-specification.html#cb171-9" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb171-10"><a href="week-4-regression-ii-model-specification.html#cb171-10" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb171-11"><a href="week-4-regression-ii-model-specification.html#cb171-11" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_LeftRight, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb171-12"><a href="week-4-regression-ii-model-specification.html#cb171-12" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_age, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb171-13"><a href="week-4-regression-ii-model-specification.html#cb171-13" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb171-14"><a href="week-4-regression-ii-model-specification.html#cb171-14" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">15</span>),</span>
<span id="cb171-15"><a href="week-4-regression-ii-model-specification.html#cb171-15" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">15</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb171-16"><a href="week-4-regression-ii-model-specification.html#cb171-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb171-17"><a href="week-4-regression-ii-model-specification.html#cb171-17" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb171-18"><a href="week-4-regression-ii-model-specification.html#cb171-18" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>), <span class="co"># Center the plot title</span></span>
<span id="cb171-19"><a href="week-4-regression-ii-model-specification.html#cb171-19" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;grey80&quot;</span>, <span class="at">size =</span> <span class="fl">0.5</span>), <span class="co"># Style for major Y grid lines</span></span>
<span id="cb171-20"><a href="week-4-regression-ii-model-specification.html#cb171-20" tabindex="-1"></a>    <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>() <span class="co"># Remove minor Y grid lines</span></span>
<span id="cb171-21"><a href="week-4-regression-ii-model-specification.html#cb171-21" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb171-22"><a href="week-4-regression-ii-model-specification.html#cb171-22" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb171-23"><a href="week-4-regression-ii-model-specification.html#cb171-23" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>,</span>
<span id="cb171-24"><a href="week-4-regression-ii-model-specification.html#cb171-24" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Simulation: Political Preferences (left to right)&quot;</span>,</span>
<span id="cb171-25"><a href="week-4-regression-ii-model-specification.html#cb171-25" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot Age vs. Political Preferences </span><span class="sc">\n</span><span class="st">(determ.&amp; stoch. sim. with adjusted intercept)&quot;</span></span>
<span id="cb171-26"><a href="week-4-regression-ii-model-specification.html#cb171-26" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-113-1.png" width="576" />
Regress the <code>predicted_LeftToRight_AdjIntercept_Stoch</code> on <code>age</code></p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="week-4-regression-ii-model-specification.html#cb172-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(predicted_LeftToRight_AdjIntercept_Stoch <span class="sc">~</span> age, <span class="at">data =</span> selects19)</span>
<span id="cb172-2"><a href="week-4-regression-ii-model-specification.html#cb172-2" tabindex="-1"></a>rsq_sd1_AdjIntercept <span class="ot">&lt;-</span> <span class="fu">summary</span>(result)<span class="sc">$</span>r.squared</span>
<span id="cb172-3"><a href="week-4-regression-ii-model-specification.html#cb172-3" tabindex="-1"></a>coeffs13 <span class="ot">&lt;-</span> <span class="fu">coef</span>(result)</span>
<span id="cb172-4"><a href="week-4-regression-ii-model-specification.html#cb172-4" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&#39;Intercept:&#39;</span>,<span class="fu">unname</span>(coeffs13[<span class="dv">1</span>]), <span class="st">&#39;</span><span class="sc">\n\n</span><span class="st">Slope:&#39;</span>, <span class="fu">unname</span>(coeffs13[<span class="dv">2</span>]))</span></code></pre></div>
<pre><code>## Intercept: 6.122055 
## 
## Slope: 0.01948902</code></pre>
<p>Report the <span class="math inline">\(R^2\)</span> generated in points 2, 11, and 13 here:</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="week-4-regression-ii-model-specification.html#cb174-1" tabindex="-1"></a>tableSD1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb174-2"><a href="week-4-regression-ii-model-specification.html#cb174-2" tabindex="-1"></a>  <span class="at">LookR2 =</span> <span class="fu">c</span>(<span class="st">&#39;Point 2&#39;</span>, <span class="st">&#39;Point 12&#39;</span>, <span class="st">&#39;Point 13&#39;</span>),</span>
<span id="cb174-3"><a href="week-4-regression-ii-model-specification.html#cb174-3" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">&#39;Unchanged&#39;</span>, <span class="st">&#39;P2 + (slope*5)&#39;</span>, <span class="st">&#39;P2+(intercept+2)&#39;</span>),</span>
<span id="cb174-4"><a href="week-4-regression-ii-model-specification.html#cb174-4" tabindex="-1"></a>  <span class="at">R2 =</span> <span class="fu">c</span>(rsq_sd1, rsq_sd1_AdjSlope, rsq_sd1_AdjIntercept),    </span>
<span id="cb174-5"><a href="week-4-regression-ii-model-specification.html#cb174-5" tabindex="-1"></a>  <span class="at">LookParams =</span> <span class="fu">c</span>(<span class="st">&#39;Point 1&#39;</span>, <span class="st">&#39;Point 12&#39;</span>, <span class="st">&#39;Point 13&#39;</span>),</span>
<span id="cb174-6"><a href="week-4-regression-ii-model-specification.html#cb174-6" tabindex="-1"></a>  <span class="at">Intercept =</span> <span class="fu">c</span>(<span class="fu">unname</span>(coeffs1[<span class="dv">1</span>]), <span class="fu">unname</span>(coeffs12[<span class="dv">1</span>]), <span class="fu">unname</span>(coeffs13[<span class="dv">1</span>])),    </span>
<span id="cb174-7"><a href="week-4-regression-ii-model-specification.html#cb174-7" tabindex="-1"></a>  <span class="at">Slope =</span> <span class="fu">c</span>(<span class="fu">unname</span>(coeffs1[<span class="dv">2</span>]), <span class="fu">unname</span>(coeffs12[<span class="dv">2</span>]), <span class="fu">unname</span>(coeffs13[<span class="dv">2</span>]))</span>
<span id="cb174-8"><a href="week-4-regression-ii-model-specification.html#cb174-8" tabindex="-1"></a>)</span>
<span id="cb174-9"><a href="week-4-regression-ii-model-specification.html#cb174-9" tabindex="-1"></a></span>
<span id="cb174-10"><a href="week-4-regression-ii-model-specification.html#cb174-10" tabindex="-1"></a></span>
<span id="cb174-11"><a href="week-4-regression-ii-model-specification.html#cb174-11" tabindex="-1"></a><span class="fu">print</span>(tableSD1)</span></code></pre></div>
<pre><code>##     LookR2            Model        R2 LookParams Intercept      Slope
## 1  Point 2        Unchanged 0.0161515    Point 1  4.122055 0.01948902
## 2 Point 12   P2 + (slope*5) 0.2973214   Point 12  4.071965 0.09874777
## 3 Point 13 P2+(intercept+2) 0.0161515   Point 13  6.122055 0.01948902</code></pre>
<ol start="16" style="list-style-type: decimal">
<li>Comparing the <span class="math inline">\(R^2\)</span> and the parameters across the models of points 1, 2, and 3 answer the following questions:</li>
</ol>
<ol style="list-style-type: lower-roman">
<li>What effect does increasing the slope of the data generating process (while keeping the residuals and intercept unchanged) have on the <span class="math inline">\(R^2\)</span>?</li>
</ol>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="week-4-regression-ii-model-specification.html#cb176-1" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&#39;The R2 increases as seen in point 13&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;The R2 increases as seen in point 13&quot;</code></pre>
<ol start="2" style="list-style-type: lower-roman">
<li>What effect does increasing the intercept of the data generating process (while keeping the residuals and slope unchanged) have on the <span class="math inline">\(R^2\)</span>?</li>
</ol>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="week-4-regression-ii-model-specification.html#cb178-1" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&#39;The R2 stays unchanged as the distance from each observation to the regression line remained unchainged (i.e., the residual was kept unchanged) as well as the average distance between each observation and the average observation remained unchainged (i.e., Y</span><span class="sc">\&#39;</span><span class="st">s variance was kept unchanged)&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;The R2 stays unchanged as the distance from each observation to the regression line remained unchainged (i.e., the residual was kept unchanged) as well as the average distance between each observation and the average observation remained unchainged (i.e., Y&#39;s variance was kept unchanged)&quot;</code></pre>
<ol start="3" style="list-style-type: lower-roman">
<li>What effect does increasing the slope of the data generating process (while keeping the residuals and intercept unchanged) have on the intercept and slope?</li>
</ol>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="week-4-regression-ii-model-specification.html#cb180-1" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&#39;It increases the estimated slope and decreases the intercept.&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;It increases the estimated slope and decreases the intercept.&quot;</code></pre>
<ol start="4" style="list-style-type: lower-roman">
<li>What effect does increasing the intercept of the data generating process (while keeping the residuals and slope unchanged) have on the intercept and slope?</li>
</ol>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="week-4-regression-ii-model-specification.html#cb182-1" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&#39;It keeps the estimated slope unchanged and the estimated intercept is the same as before the adjustment but increases by the same value that the whole data generating process was modified.&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;It keeps the estimated slope unchanged and the estimated intercept is the same as before the adjustment but increases by the same value that the whole data generating process was modified.&quot;</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-3-regression-i-prediction.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-5.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/04-Week4.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
