<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Week 3: Regression I (Prediction) | Intermediate Quantitative Methods</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Week 3: Regression I (Prediction) | Intermediate Quantitative Methods" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Week 3: Regression I (Prediction) | Intermediate Quantitative Methods" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Lucas Lemmann" />


<meta name="date" content="2023-12-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-2.html"/>
<link rel="next" href="week-4-regression-ii-model-specification.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Intermediate Quantitative Methods</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#how-to-use-these-exercises"><i class="fa fa-check"></i><b>0.1</b> How to use these exercises?</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#schedule"><i class="fa fa-check"></i><b>0.2</b> Schedule</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html"><i class="fa fa-check"></i><b>1</b> Week 1: DIYS 1</a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html#aims"><i class="fa fa-check"></i><b>1.1</b> Aims:</a></li>
<li class="chapter" data-level="1.2" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html#first-part-repetition-rrstudio"><i class="fa fa-check"></i><b>1.2</b> First Part: REPETITION R/RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html#second-part-some-simple-analysis"><i class="fa fa-check"></i><b>1.3</b> Second Part: Some Simple Analysis</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html#first-adjust-the-data"><i class="fa fa-check"></i><b>1.3.1</b> First, adjust the data</a></li>
<li class="chapter" data-level="1.3.2" data-path="week-1-diys-1.html"><a href="week-1-diys-1.html#second-answer-the-following-questions"><i class="fa fa-check"></i><b>1.3.2</b> Second, answer the following questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2.html"><a href="week-2.html"><i class="fa fa-check"></i><b>2</b> Week 2</a>
<ul>
<li class="chapter" data-level="2.1" data-path="week-2.html"><a href="week-2.html#exercise"><i class="fa fa-check"></i><b>2.1</b> Exercise</a></li>
<li class="chapter" data-level="2.2" data-path="week-2.html"><a href="week-2.html#solution"><i class="fa fa-check"></i><b>2.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html"><i class="fa fa-check"></i><b>3</b> Week 3: Regression I (Prediction)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#aims-1"><i class="fa fa-check"></i><b>3.1</b> Aims</a></li>
<li class="chapter" data-level="3.2" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#exercise-context-and-question"><i class="fa fa-check"></i><b>3.2</b> Exercise: Context and Question</a></li>
<li class="chapter" data-level="3.3" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#exercise-solution"><i class="fa fa-check"></i><b>3.3</b> Exercise: solution</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#real-data"><i class="fa fa-check"></i><b>3.3.1</b> Real data</a></li>
<li class="chapter" data-level="3.3.2" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#simulated-data"><i class="fa fa-check"></i><b>3.3.2</b> Simulated data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="week-3-regression-i-prediction.html"><a href="week-3-regression-i-prediction.html#appendix-getting-the-data-first"><i class="fa fa-check"></i><b>3.4</b> Appendix: Getting the data first</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html"><i class="fa fa-check"></i><b>4</b> Week 4: Regression II (Model Specification)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#aims-2"><i class="fa fa-check"></i><b>4.1</b> Aims</a></li>
<li class="chapter" data-level="4.2" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#exercise-context-and-questions"><i class="fa fa-check"></i><b>4.2</b> Exercise: Context and questions</a></li>
<li class="chapter" data-level="4.3" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#adjusting-the-data-first"><i class="fa fa-check"></i><b>4.3</b> Adjusting the data first</a></li>
<li class="chapter" data-level="4.4" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#exercise-solution-1"><i class="fa fa-check"></i><b>4.4</b> Exercise: solution</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#real-data-1"><i class="fa fa-check"></i><b>4.4.1</b> Real data</a></li>
<li class="chapter" data-level="4.4.2" data-path="week-4-regression-ii-model-specification.html"><a href="week-4-regression-ii-model-specification.html#simulated-data-1"><i class="fa fa-check"></i><b>4.4.2</b> Simulated data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-5.html"><a href="week-5.html"><i class="fa fa-check"></i><b>5</b> Week 5</a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-5.html"><a href="week-5.html#exercise-1"><i class="fa fa-check"></i><b>5.1</b> Exercise</a></li>
<li class="chapter" data-level="5.2" data-path="week-5.html"><a href="week-5.html#solution-1"><i class="fa fa-check"></i><b>5.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-6.html"><a href="week-6.html"><i class="fa fa-check"></i><b>6</b> Week 6</a>
<ul>
<li class="chapter" data-level="6.1" data-path="week-6.html"><a href="week-6.html#exercise-2"><i class="fa fa-check"></i><b>6.1</b> Exercise</a></li>
<li class="chapter" data-level="6.2" data-path="week-6.html"><a href="week-6.html#solution-2"><i class="fa fa-check"></i><b>6.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-7.html"><a href="week-7.html"><i class="fa fa-check"></i><b>7</b> Week 7</a>
<ul>
<li class="chapter" data-level="7.1" data-path="week-7.html"><a href="week-7.html#exercise-3"><i class="fa fa-check"></i><b>7.1</b> Exercise</a></li>
<li class="chapter" data-level="7.2" data-path="week-7.html"><a href="week-7.html#solution-3"><i class="fa fa-check"></i><b>7.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-8-causality-iii-observational-data.html"><a href="week-8-causality-iii-observational-data.html"><i class="fa fa-check"></i><b>8</b> Week 8: Causality III (Observational Data)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="week-8-causality-iii-observational-data.html"><a href="week-8-causality-iii-observational-data.html#aims-3"><i class="fa fa-check"></i><b>8.1</b> Aims</a></li>
<li class="chapter" data-level="8.2" data-path="week-8-causality-iii-observational-data.html"><a href="week-8-causality-iii-observational-data.html#exercise-4"><i class="fa fa-check"></i><b>8.2</b> Exercise</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="week-8-causality-iii-observational-data.html"><a href="week-8-causality-iii-observational-data.html#simulated-data-2"><i class="fa fa-check"></i><b>8.2.1</b> Simulated data</a></li>
<li class="chapter" data-level="8.2.2" data-path="week-8-causality-iii-observational-data.html"><a href="week-8-causality-iii-observational-data.html#real-data-2"><i class="fa fa-check"></i><b>8.2.2</b> Real data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-9.html"><a href="week-9.html"><i class="fa fa-check"></i><b>9</b> Week 9</a>
<ul>
<li class="chapter" data-level="9.1" data-path="week-9.html"><a href="week-9.html#exercise-5"><i class="fa fa-check"></i><b>9.1</b> Exercise</a></li>
<li class="chapter" data-level="9.2" data-path="week-9.html"><a href="week-9.html#solution-4"><i class="fa fa-check"></i><b>9.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="week-10.html"><a href="week-10.html"><i class="fa fa-check"></i><b>10</b> Week 10</a>
<ul>
<li class="chapter" data-level="10.1" data-path="week-10.html"><a href="week-10.html#exercise-6"><i class="fa fa-check"></i><b>10.1</b> Exercise</a></li>
<li class="chapter" data-level="10.2" data-path="week-10.html"><a href="week-10.html#solution-5"><i class="fa fa-check"></i><b>10.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="week-11.html"><a href="week-11.html"><i class="fa fa-check"></i><b>11</b> Week 11</a>
<ul>
<li class="chapter" data-level="11.1" data-path="week-11.html"><a href="week-11.html#exercise-7"><i class="fa fa-check"></i><b>11.1</b> Exercise</a></li>
<li class="chapter" data-level="11.2" data-path="week-11.html"><a href="week-11.html#solution-6"><i class="fa fa-check"></i><b>11.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="week-12.html"><a href="week-12.html"><i class="fa fa-check"></i><b>12</b> Week 12</a>
<ul>
<li class="chapter" data-level="12.1" data-path="week-12.html"><a href="week-12.html#exercise-8"><i class="fa fa-check"></i><b>12.1</b> Exercise</a></li>
<li class="chapter" data-level="12.2" data-path="week-12.html"><a href="week-12.html#solution-7"><i class="fa fa-check"></i><b>12.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="week-13.html"><a href="week-13.html"><i class="fa fa-check"></i><b>13</b> Week 13</a>
<ul>
<li class="chapter" data-level="13.1" data-path="week-13.html"><a href="week-13.html#exercise-9"><i class="fa fa-check"></i><b>13.1</b> Exercise</a></li>
<li class="chapter" data-level="13.2" data-path="week-13.html"><a href="week-13.html#solution-8"><i class="fa fa-check"></i><b>13.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="week-14.html"><a href="week-14.html"><i class="fa fa-check"></i><b>14</b> Week 14</a>
<ul>
<li class="chapter" data-level="14.1" data-path="week-14.html"><a href="week-14.html#exercise-10"><i class="fa fa-check"></i><b>14.1</b> Exercise</a></li>
<li class="chapter" data-level="14.2" data-path="week-14.html"><a href="week-14.html#solution-9"><i class="fa fa-check"></i><b>14.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="potentially-useful-exercises.html"><a href="potentially-useful-exercises.html"><i class="fa fa-check"></i><b>15</b> Potentially useful exercises</a>
<ul>
<li class="chapter" data-level="15.1" data-path="potentially-useful-exercises.html"><a href="potentially-useful-exercises.html#taken-out-from-week-3"><i class="fa fa-check"></i><b>15.1</b> Taken out from Week 3</a></li>
<li class="chapter" data-level="15.2" data-path="potentially-useful-exercises.html"><a href="potentially-useful-exercises.html#taken-out-from-week-4"><i class="fa fa-check"></i><b>15.2</b> Taken out from Week 4</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="potentially-useful-exercises.html"><a href="potentially-useful-exercises.html#simulated-data-3"><i class="fa fa-check"></i><b>15.2.1</b> Simulated data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>16</b> Data transformation</a>
<ul>
<li class="chapter" data-level="16.1" data-path="data-transformation.html"><a href="data-transformation.html#week-1-gorilla"><i class="fa fa-check"></i><b>16.1</b> Week 1: Gorilla</a></li>
<li class="chapter" data-level="16.2" data-path="data-transformation.html"><a href="data-transformation.html#week-4-restricted-variables-from-selects"><i class="fa fa-check"></i><b>16.2</b> Week 4: restricted variables from SELECTS</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published using bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Intermediate Quantitative Methods</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-3-regression-i-prediction" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Week 3: Regression I (Prediction)<a href="week-3-regression-i-prediction.html#week-3-regression-i-prediction" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="aims-1" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Aims<a href="week-3-regression-i-prediction.html#aims-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Using regression analysis for quantitative descriptive purposes with real data</li>
<li>Using simulation to instantiate how different properties of the data generating process alter the reliability of regression analysis</li>
</ol>
</div>
<div id="exercise-context-and-question" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Exercise: Context and Question<a href="week-3-regression-i-prediction.html#exercise-context-and-question" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As developed in the following <a href="https://de.wikipedia.org/wiki/Eidgen%C3%B6ssische_Abstimmung_%C3%BCber_die_Totalrevision_des_CO2-Gesetzes#:~:text=Die%20Eidgen%C3%B6ssische%20Abstimmung%20%C3%BCber%20die,von%2051%2C59%20%25%20abgelehnt.">entry</a>, a referendum took place in 2021 to assess whether Swiss citizens approved or not a bill aimed at reducing greenhouse gas emissions.</p>
<p>The bill was rejected by a narrow margin: 51.6% of votes went for the “No”, while 48.4% for the “Yes”. In the media, some analysts commented that a marked division or cleavage between rural and urban voters seems to have led to this result. According to their <strong>narrative</strong>, a specially high rural turn-out seems to underlie such result. As the analyst commented, most urban inhabitants liked the bill while most rural inhabitants disliked it.</p>
<p>Not satisfied with a simple impression, as a political scientist you want to quantitatively qualify your understanding about what happened in that election. Particularly, you want to know:</p>
<ol style="list-style-type: decimal">
<li>Given that more rural municipalities have smaller populations, was the turn-out higher in municipalities with smaller populations than in bigger ones?</li>
<li>Was the turn-out higher in more agricultural municipalities than in less agricultural ones?</li>
</ol>
<p>Thus, to analytically describe the voting results, you will perform some regressions using the following data.</p>
</div>
<div id="exercise-solution" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Exercise: solution<a href="week-3-regression-i-prediction.html#exercise-solution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Note:</strong> Remember that you can copy the code from one point to answer another point. Simply make the necessary adjustments.</p>
<div id="real-data" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Real data<a href="week-3-regression-i-prediction.html#real-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Open the file <code>CO2_land.csv</code>.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="week-3-regression-i-prediction.html#cb49-1" tabindex="-1"></a>CO2_land <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;Data/CO2_land.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><strong>Note</strong>: in the Appendix you can find how to get the data using APIs of the Swiss Federal Statistical Office.</p>
<p>Using such a file, you embark in doing the following to answer your two questions:</p>
<ol style="list-style-type: lower-roman">
<li>Since you want to describe the turn-out across municipalities with different population sizes, you initially think of regressing the turn-out on the population size. As you lack the municipal population, you use the number of eligible voters <code>anzahlStimmberechtigte</code> as a proxy. To have a preliminary notion on the relation between <code>stimmbeteiligungInProzent</code> (Turn-out in percent) on <code>anzahlStimmberechtigte</code> (number of eligible voters), generate a scatter plot and add as many straight lines as you want to visually guess which one would be the one that goes closest to each data point. <a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">This</a> entry could be of help. Remember that a straight line is defined in therms of its slope and intercept parameters. Begin with a slope of zero and an intercept equal to 50. Then, change only one parameter at a time.</li>
</ol>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="week-3-regression-i-prediction.html#cb50-1" tabindex="-1"></a>guess_int_1<span class="ot">=</span> <span class="dv">50</span></span>
<span id="cb50-2"><a href="week-3-regression-i-prediction.html#cb50-2" tabindex="-1"></a>guess_slope_1<span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb50-3"><a href="week-3-regression-i-prediction.html#cb50-3" tabindex="-1"></a>  </span>
<span id="cb50-4"><a href="week-3-regression-i-prediction.html#cb50-4" tabindex="-1"></a>guess_int_2<span class="ot">=</span> <span class="fu">mean</span>(CO2_land<span class="sc">$</span>stimmbeteiligungInProzent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb50-5"><a href="week-3-regression-i-prediction.html#cb50-5" tabindex="-1"></a></span>
<span id="cb50-6"><a href="week-3-regression-i-prediction.html#cb50-6" tabindex="-1"></a>guess_slope_3<span class="ot">=</span><span class="sc">-</span><span class="fl">0.01</span></span>
<span id="cb50-7"><a href="week-3-regression-i-prediction.html#cb50-7" tabindex="-1"></a>  </span>
<span id="cb50-8"><a href="week-3-regression-i-prediction.html#cb50-8" tabindex="-1"></a>guess_slope_4<span class="ot">=</span><span class="sc">-</span><span class="fl">0.0005</span></span>
<span id="cb50-9"><a href="week-3-regression-i-prediction.html#cb50-9" tabindex="-1"></a>  </span>
<span id="cb50-10"><a href="week-3-regression-i-prediction.html#cb50-10" tabindex="-1"></a>guess_slope_5<span class="ot">=</span><span class="sc">-</span><span class="fl">0.0003</span></span>
<span id="cb50-11"><a href="week-3-regression-i-prediction.html#cb50-11" tabindex="-1"></a></span>
<span id="cb50-12"><a href="week-3-regression-i-prediction.html#cb50-12" tabindex="-1"></a></span>
<span id="cb50-13"><a href="week-3-regression-i-prediction.html#cb50-13" tabindex="-1"></a></span>
<span id="cb50-14"><a href="week-3-regression-i-prediction.html#cb50-14" tabindex="-1"></a></span>
<span id="cb50-15"><a href="week-3-regression-i-prediction.html#cb50-15" tabindex="-1"></a><span class="fu">ggplot</span>(CO2_land, <span class="fu">aes</span>(<span class="at">x =</span> anzahlStimmberechtigte, <span class="at">y =</span> stimmbeteiligungInProzent)) <span class="sc">+</span></span>
<span id="cb50-16"><a href="week-3-regression-i-prediction.html#cb50-16" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb50-17"><a href="week-3-regression-i-prediction.html#cb50-17" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> guess_int_1,</span>
<span id="cb50-18"><a href="week-3-regression-i-prediction.html#cb50-18" tabindex="-1"></a>              <span class="at">slope =</span> guess_slope_1, <span class="at">color =</span> <span class="st">&quot;#FF0000&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co">#first guess</span></span>
<span id="cb50-19"><a href="week-3-regression-i-prediction.html#cb50-19" tabindex="-1"></a>  </span>
<span id="cb50-20"><a href="week-3-regression-i-prediction.html#cb50-20" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> guess_int_2,   </span>
<span id="cb50-21"><a href="week-3-regression-i-prediction.html#cb50-21" tabindex="-1"></a>              <span class="at">slope =</span> guess_slope_1, <span class="at">color =</span> <span class="st">&quot;#FF4500&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co">#a good guess, only changing intercept</span></span>
<span id="cb50-22"><a href="week-3-regression-i-prediction.html#cb50-22" tabindex="-1"></a>  </span>
<span id="cb50-23"><a href="week-3-regression-i-prediction.html#cb50-23" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> guess_int_2, </span>
<span id="cb50-24"><a href="week-3-regression-i-prediction.html#cb50-24" tabindex="-1"></a>              <span class="at">slope =</span> guess_slope_3, <span class="at">color =</span> <span class="st">&quot;#FFA500&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co">#decreasing the slope, keeping the intercept</span></span>
<span id="cb50-25"><a href="week-3-regression-i-prediction.html#cb50-25" tabindex="-1"></a>  </span>
<span id="cb50-26"><a href="week-3-regression-i-prediction.html#cb50-26" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> guess_int_2, </span>
<span id="cb50-27"><a href="week-3-regression-i-prediction.html#cb50-27" tabindex="-1"></a>              <span class="at">slope =</span> guess_slope_4, <span class="at">color =</span> <span class="st">&quot;#9ACD32&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co">#decreasing the slope, keeping the intercept</span></span>
<span id="cb50-28"><a href="week-3-regression-i-prediction.html#cb50-28" tabindex="-1"></a>  </span>
<span id="cb50-29"><a href="week-3-regression-i-prediction.html#cb50-29" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> guess_int_2,   </span>
<span id="cb50-30"><a href="week-3-regression-i-prediction.html#cb50-30" tabindex="-1"></a>              <span class="at">slope =</span> guess_slope_5, <span class="at">color =</span> <span class="st">&quot;#008000&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co">#best visual guess</span></span>
<span id="cb50-31"><a href="week-3-regression-i-prediction.html#cb50-31" tabindex="-1"></a></span>
<span id="cb50-32"><a href="week-3-regression-i-prediction.html#cb50-32" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(CO2_land<span class="sc">$</span>stimmbeteiligungInProzent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">+</span>  </span>
<span id="cb50-33"><a href="week-3-regression-i-prediction.html#cb50-33" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb50-34"><a href="week-3-regression-i-prediction.html#cb50-34" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb50-35"><a href="week-3-regression-i-prediction.html#cb50-35" tabindex="-1"></a></span>
<span id="cb50-36"><a href="week-3-regression-i-prediction.html#cb50-36" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb50-37"><a href="week-3-regression-i-prediction.html#cb50-37" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Number of eligible voters&quot;</span>,</span>
<span id="cb50-38"><a href="week-3-regression-i-prediction.html#cb50-38" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Turn-out (%)&quot;</span>,</span>
<span id="cb50-39"><a href="week-3-regression-i-prediction.html#cb50-39" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot with straight lines using the eye-meter&quot;</span></span>
<span id="cb50-40"><a href="week-3-regression-i-prediction.html#cb50-40" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-32-1.png" width="576" /></p>
<ol start="2" style="list-style-type: lower-roman">
<li>Add to the previous graph the linear regression line.</li>
</ol>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="week-3-regression-i-prediction.html#cb51-1" tabindex="-1"></a><span class="fu">ggplot</span>(CO2_land, <span class="fu">aes</span>(<span class="at">x =</span> anzahlStimmberechtigte, <span class="at">y =</span> stimmbeteiligungInProzent)) <span class="sc">+</span></span>
<span id="cb51-2"><a href="week-3-regression-i-prediction.html#cb51-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb51-3"><a href="week-3-regression-i-prediction.html#cb51-3" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> guess_int_1,</span>
<span id="cb51-4"><a href="week-3-regression-i-prediction.html#cb51-4" tabindex="-1"></a>              <span class="at">slope =</span> guess_slope_1, <span class="at">color =</span> <span class="st">&quot;#FF0000&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co">#first guess</span></span>
<span id="cb51-5"><a href="week-3-regression-i-prediction.html#cb51-5" tabindex="-1"></a>  </span>
<span id="cb51-6"><a href="week-3-regression-i-prediction.html#cb51-6" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> guess_int_2,   </span>
<span id="cb51-7"><a href="week-3-regression-i-prediction.html#cb51-7" tabindex="-1"></a>              <span class="at">slope =</span> guess_slope_1, <span class="at">color =</span> <span class="st">&quot;#FF4500&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co">#a good guess, only changing intercept</span></span>
<span id="cb51-8"><a href="week-3-regression-i-prediction.html#cb51-8" tabindex="-1"></a>  </span>
<span id="cb51-9"><a href="week-3-regression-i-prediction.html#cb51-9" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> guess_int_2, </span>
<span id="cb51-10"><a href="week-3-regression-i-prediction.html#cb51-10" tabindex="-1"></a>              <span class="at">slope =</span> guess_slope_3, <span class="at">color =</span> <span class="st">&quot;#FFA500&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co">#decreasing the slope, keeping the intercept</span></span>
<span id="cb51-11"><a href="week-3-regression-i-prediction.html#cb51-11" tabindex="-1"></a>  </span>
<span id="cb51-12"><a href="week-3-regression-i-prediction.html#cb51-12" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> guess_int_2, </span>
<span id="cb51-13"><a href="week-3-regression-i-prediction.html#cb51-13" tabindex="-1"></a>              <span class="at">slope =</span> guess_slope_4, <span class="at">color =</span> <span class="st">&quot;#9ACD32&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co">#decreasing the slope, keeping the intercept</span></span>
<span id="cb51-14"><a href="week-3-regression-i-prediction.html#cb51-14" tabindex="-1"></a>  </span>
<span id="cb51-15"><a href="week-3-regression-i-prediction.html#cb51-15" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> guess_int_2,   </span>
<span id="cb51-16"><a href="week-3-regression-i-prediction.html#cb51-16" tabindex="-1"></a>              <span class="at">slope =</span> guess_slope_5, <span class="at">color =</span> <span class="st">&quot;#008000&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co">#best visual guess</span></span>
<span id="cb51-17"><a href="week-3-regression-i-prediction.html#cb51-17" tabindex="-1"></a>  </span>
<span id="cb51-18"><a href="week-3-regression-i-prediction.html#cb51-18" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co">#mathematically estimated best possible parameters</span></span>
<span id="cb51-19"><a href="week-3-regression-i-prediction.html#cb51-19" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(CO2_land<span class="sc">$</span>stimmbeteiligungInProzent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">+</span>  </span>
<span id="cb51-20"><a href="week-3-regression-i-prediction.html#cb51-20" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb51-21"><a href="week-3-regression-i-prediction.html#cb51-21" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb51-22"><a href="week-3-regression-i-prediction.html#cb51-22" tabindex="-1"></a></span>
<span id="cb51-23"><a href="week-3-regression-i-prediction.html#cb51-23" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb51-24"><a href="week-3-regression-i-prediction.html#cb51-24" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Number of eligible voters&quot;</span>,</span>
<span id="cb51-25"><a href="week-3-regression-i-prediction.html#cb51-25" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Turn-out (%)&quot;</span>,</span>
<span id="cb51-26"><a href="week-3-regression-i-prediction.html#cb51-26" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot with straight lines using the eye-meter and the regression line&quot;</span></span>
<span id="cb51-27"><a href="week-3-regression-i-prediction.html#cb51-27" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-33-1.png" width="576" /></p>
<ol start="3" style="list-style-type: lower-roman">
<li>You have now instantiated the intuition behind the linear regression by forming different lines that are visually intuitive about the relation between our variables of interest. Since you know that the linear regression line is the straight line that is closest to all points, you want to go beyond your “eye-meter” and use a precise measurement. Regress <code>stimmbeteiligungInProzent</code> on <code>anzahlStimmberechtigte</code>. Report and interpret the parameters.</li>
</ol>
<p>Write the regression here.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="week-3-regression-i-prediction.html#cb52-1" tabindex="-1"></a>result1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(stimmbeteiligungInProzent <span class="sc">~</span> anzahlStimmberechtigte , <span class="at">data =</span> CO2_land)</span>
<span id="cb52-2"><a href="week-3-regression-i-prediction.html#cb52-2" tabindex="-1"></a><span class="fu">summary</span>(result1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = stimmbeteiligungInProzent ~ anzahlStimmberechtigte, 
##     data = CO2_land)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -26.173  -5.185   0.244   5.365  45.871 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             6.558e+01  1.832e-01 358.048   &lt;2e-16 ***
## anzahlStimmberechtigte -2.202e-04  2.408e-05  -9.146   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.98 on 2130 degrees of freedom
## Multiple R-squared:  0.03779,    Adjusted R-squared:  0.03734 
## F-statistic: 83.65 on 1 and 2130 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Report and interpret the parameters here:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="week-3-regression-i-prediction.html#cb54-1" tabindex="-1"></a>coeffs1<span class="ot">&lt;-</span> <span class="fu">coef</span>(result1)</span>
<span id="cb54-2"><a href="week-3-regression-i-prediction.html#cb54-2" tabindex="-1"></a>coeffs1</span></code></pre></div>
<pre><code>##            (Intercept) anzahlStimmberechtigte 
##          65.5802858731          -0.0002202479</code></pre>
<p>The estimated (Intercept) is 65.58, while the estimated slope for anzahlStimmberechtigte is -2.2^{-4}. It means that, across Swiss municipalities, an increase of a thousand voters was associated with an average decrease in the turn-out of -0.22 percentage points.</p>
<ol start="4" style="list-style-type: lower-roman">
<li>Since you don’t want to take for granted that the mathematically estimated parameters are the ones that generate the best possible fit for a straight line, you want to compare the Sum of Squared Residuals (SSR) across the lines that you generated in the previous point. Generate and compare the SSR for each of those lines. Are the parameters estimated by R the best among your estimations?</li>
</ol>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="week-3-regression-i-prediction.html#cb56-1" tabindex="-1"></a><span class="co"># It&#39;s easier to calculate the residuals simply using the model</span></span>
<span id="cb56-2"><a href="week-3-regression-i-prediction.html#cb56-2" tabindex="-1"></a>CO2_land<span class="sc">$</span>ResidRegression<span class="ot">&lt;-</span> <span class="fu">residuals</span>(result1)</span>
<span id="cb56-3"><a href="week-3-regression-i-prediction.html#cb56-3" tabindex="-1"></a>CO2_land<span class="sc">$</span>SqResidRegression<span class="ot">&lt;-</span> (<span class="fu">residuals</span>(result1))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb56-4"><a href="week-3-regression-i-prediction.html#cb56-4" tabindex="-1"></a>CO2_land<span class="sc">$</span>SumSqResidRegression<span class="ot">&lt;-</span> <span class="fu">sum</span>(CO2_land<span class="sc">$</span>SqResidRegression)</span>
<span id="cb56-5"><a href="week-3-regression-i-prediction.html#cb56-5" tabindex="-1"></a></span>
<span id="cb56-6"><a href="week-3-regression-i-prediction.html#cb56-6" tabindex="-1"></a><span class="co">#But it&#39;s also possible to easily calculate the squared residuals (SR) for each model</span></span>
<span id="cb56-7"><a href="week-3-regression-i-prediction.html#cb56-7" tabindex="-1"></a></span>
<span id="cb56-8"><a href="week-3-regression-i-prediction.html#cb56-8" tabindex="-1"></a>CO2_land<span class="sc">$</span>SR_Guess1<span class="ot">=</span> ((guess_int_1 <span class="sc">+</span> guess_slope_1 <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte)<span class="sc">-</span>CO2_land<span class="sc">$</span>stimmbeteiligungInProzent)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb56-9"><a href="week-3-regression-i-prediction.html#cb56-9" tabindex="-1"></a>CO2_land<span class="sc">$</span>SR_Guess2<span class="ot">=</span> ((guess_int_2 <span class="sc">+</span> guess_slope_1 <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte)<span class="sc">-</span>CO2_land<span class="sc">$</span>stimmbeteiligungInProzent)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb56-10"><a href="week-3-regression-i-prediction.html#cb56-10" tabindex="-1"></a>CO2_land<span class="sc">$</span>SR_Guess3<span class="ot">=</span> ((guess_int_1 <span class="sc">+</span> guess_slope_3 <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte)<span class="sc">-</span>CO2_land<span class="sc">$</span>stimmbeteiligungInProzent)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb56-11"><a href="week-3-regression-i-prediction.html#cb56-11" tabindex="-1"></a>CO2_land<span class="sc">$</span>SR_Guess4<span class="ot">=</span> ((guess_int_1 <span class="sc">+</span> guess_slope_4 <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte)<span class="sc">-</span>CO2_land<span class="sc">$</span>stimmbeteiligungInProzent)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb56-12"><a href="week-3-regression-i-prediction.html#cb56-12" tabindex="-1"></a>CO2_land<span class="sc">$</span>SR_Guess5<span class="ot">=</span> ((guess_int_1 <span class="sc">+</span> guess_slope_5 <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte)<span class="sc">-</span>CO2_land<span class="sc">$</span>stimmbeteiligungInProzent)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb56-13"><a href="week-3-regression-i-prediction.html#cb56-13" tabindex="-1"></a></span>
<span id="cb56-14"><a href="week-3-regression-i-prediction.html#cb56-14" tabindex="-1"></a><span class="co"># And sum of squared residuals (SSR)</span></span>
<span id="cb56-15"><a href="week-3-regression-i-prediction.html#cb56-15" tabindex="-1"></a>CO2_land<span class="sc">$</span>SSR_Guess1<span class="ot">=</span> <span class="fu">sum</span>(CO2_land<span class="sc">$</span>SR_Guess1)</span>
<span id="cb56-16"><a href="week-3-regression-i-prediction.html#cb56-16" tabindex="-1"></a>CO2_land<span class="sc">$</span>SSR_Guess2<span class="ot">=</span> <span class="fu">sum</span>(CO2_land<span class="sc">$</span>SR_Guess2)</span>
<span id="cb56-17"><a href="week-3-regression-i-prediction.html#cb56-17" tabindex="-1"></a>CO2_land<span class="sc">$</span>SSR_Guess3<span class="ot">=</span> <span class="fu">sum</span>(CO2_land<span class="sc">$</span>SR_Guess3)</span>
<span id="cb56-18"><a href="week-3-regression-i-prediction.html#cb56-18" tabindex="-1"></a>CO2_land<span class="sc">$</span>SSR_Guess4<span class="ot">=</span> <span class="fu">sum</span>(CO2_land<span class="sc">$</span>SR_Guess4)</span>
<span id="cb56-19"><a href="week-3-regression-i-prediction.html#cb56-19" tabindex="-1"></a>CO2_land<span class="sc">$</span>SSR_Guess5<span class="ot">=</span> <span class="fu">sum</span>(CO2_land<span class="sc">$</span>SR_Guess5)</span>
<span id="cb56-20"><a href="week-3-regression-i-prediction.html#cb56-20" tabindex="-1"></a></span>
<span id="cb56-21"><a href="week-3-regression-i-prediction.html#cb56-21" tabindex="-1"></a><span class="cf">if</span> ((CO2_land<span class="sc">$</span>SumSqResidRegression[<span class="dv">1</span>]<span class="sc">&lt;</span>CO2_land<span class="sc">$</span>SSR_Guess1[<span class="dv">1</span>]) <span class="sc">&amp;</span> (CO2_land<span class="sc">$</span>SumSqResidRegression[<span class="dv">1</span>]<span class="sc">&lt;</span>CO2_land<span class="sc">$</span>SSR_Guess2[<span class="dv">1</span>]) <span class="sc">&amp;</span> (CO2_land<span class="sc">$</span>SumSqResidRegression[<span class="dv">1</span>]<span class="sc">&lt;</span>CO2_land<span class="sc">$</span>SSR_Guess3[<span class="dv">1</span>]) <span class="sc">&amp;</span> (CO2_land<span class="sc">$</span>SumSqResidRegression[<span class="dv">1</span>]<span class="sc">&lt;</span>CO2_land<span class="sc">$</span>SSR_Guess4[<span class="dv">1</span>]) <span class="sc">&amp;</span> (CO2_land<span class="sc">$</span>SumSqResidRegression[<span class="dv">1</span>]<span class="sc">&lt;</span>CO2_land<span class="sc">$</span>SSR_Guess5[<span class="dv">1</span>])){</span>
<span id="cb56-22"><a href="week-3-regression-i-prediction.html#cb56-22" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;Yes, as it is mathematically necessary, the SSR for the mathematically estimated model is the lowest across all estimated scenarios! :)&quot;</span>)</span>
<span id="cb56-23"><a href="week-3-regression-i-prediction.html#cb56-23" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;Yes, as it is mathematically necessary, the SSR for the mathematically estimated model is the lowest across all estimated scenarios! :)&quot;</code></pre>
<ol start="22" style="list-style-type: lower-alpha">
<li>Notice that some few municipalities have numbers of voters that are very high compared to the typical values. As a consequence, the regression line is very influenced by those observations (i.e., small displacements in the area where there are many observations have a lower influence on the line than displacements of the same magnitude and direction in the area with few observations). As a consequence, you want to analyze how do the previous estimates change when you restrict your analysis to municipalities with less than 50K eligible voters. Estimate the regression and compare the respective parameters of the models. What slope is higher? What intercept is higher? How does obviating those observations influence our parameters?</li>
</ol>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="week-3-regression-i-prediction.html#cb58-1" tabindex="-1"></a>CO2_land_filtered <span class="ot">&lt;-</span> CO2_land <span class="sc">%&gt;%</span> </span>
<span id="cb58-2"><a href="week-3-regression-i-prediction.html#cb58-2" tabindex="-1"></a>  <span class="fu">filter</span>(anzahlStimmberechtigte <span class="sc">&lt;</span> <span class="dv">50000</span>)</span>
<span id="cb58-3"><a href="week-3-regression-i-prediction.html#cb58-3" tabindex="-1"></a></span>
<span id="cb58-4"><a href="week-3-regression-i-prediction.html#cb58-4" tabindex="-1"></a>result2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(stimmbeteiligungInProzent <span class="sc">~</span> anzahlStimmberechtigte , <span class="at">data =</span> CO2_land_filtered)</span>
<span id="cb58-5"><a href="week-3-regression-i-prediction.html#cb58-5" tabindex="-1"></a><span class="fu">summary</span>(result2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = stimmbeteiligungInProzent ~ anzahlStimmberechtigte, 
##     data = CO2_land_filtered)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -27.3197  -4.6709   0.2374   4.9221  29.8830 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             6.698e+01  1.997e-01   335.3   &lt;2e-16 ***
## anzahlStimmberechtigte -8.762e-04  5.093e-05   -17.2   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.62 on 2123 degrees of freedom
## Multiple R-squared:  0.1224, Adjusted R-squared:  0.122 
## F-statistic:   296 on 1 and 2123 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="week-3-regression-i-prediction.html#cb60-1" tabindex="-1"></a>coeffs2<span class="ot">&lt;-</span> <span class="fu">coef</span>(result2)</span>
<span id="cb60-2"><a href="week-3-regression-i-prediction.html#cb60-2" tabindex="-1"></a>coeffs2</span></code></pre></div>
<pre><code>##            (Intercept) anzahlStimmberechtigte 
##          66.9791169423          -0.0008762278</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="week-3-regression-i-prediction.html#cb62-1" tabindex="-1"></a><span class="cf">if</span> ((coeffs1[<span class="dv">1</span>]<span class="sc">&gt;</span>coeffs2[<span class="dv">1</span>]) <span class="sc">&amp;</span> (coeffs1[<span class="dv">1</span>]<span class="sc">!=</span>coeffs2[<span class="dv">1</span>])){</span>
<span id="cb62-2"><a href="week-3-regression-i-prediction.html#cb62-2" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;The original model has a higher intercept than the one only on the restricted observations.&quot;</span>)</span>
<span id="cb62-3"><a href="week-3-regression-i-prediction.html#cb62-3" tabindex="-1"></a>} <span class="cf">else</span>{</span>
<span id="cb62-4"><a href="week-3-regression-i-prediction.html#cb62-4" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;The model only on the restricted observations has a higher intercept than the original one.&quot;</span>)</span>
<span id="cb62-5"><a href="week-3-regression-i-prediction.html#cb62-5" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;The model only on the restricted observations has a higher intercept than the original one.&quot;</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="week-3-regression-i-prediction.html#cb64-1" tabindex="-1"></a><span class="cf">if</span> ((coeffs1[<span class="dv">2</span>]<span class="sc">&gt;</span>coeffs2[<span class="dv">2</span>]) <span class="sc">&amp;</span> (coeffs1[<span class="dv">2</span>]<span class="sc">!=</span>coeffs2[<span class="dv">2</span>])){</span>
<span id="cb64-2"><a href="week-3-regression-i-prediction.html#cb64-2" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;The original model has a higher slope than the one only on the restricted observations.&quot;</span>)</span>
<span id="cb64-3"><a href="week-3-regression-i-prediction.html#cb64-3" tabindex="-1"></a>} <span class="cf">else</span>{</span>
<span id="cb64-4"><a href="week-3-regression-i-prediction.html#cb64-4" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;The model only on the restricted observations has a higher slope than the original one.&quot;</span>)</span>
<span id="cb64-5"><a href="week-3-regression-i-prediction.html#cb64-5" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;The original model has a higher slope than the one only on the restricted observations.&quot;</code></pre>
<p>The reason the parameters changed is because the new model needs to fit data that is concentrated in a more clearly negative relation between our variables of interest.</p>
<ol start="6" style="list-style-type: lower-roman">
<li><p>[Optional] Modify slightly the parameters estimated using the linear regression. For example, keeping the intercept unchanged, increase or decrease the slope in 1 percent every time. Now, compare the sum of squared residuals. Do your experiments show smaller SSR? Is it possible?</p></li>
<li><p>Finally, you want to analyze a counterfactual scenario: What would have been the outcome of the referendum should the turn-out in each of the municipalities would have been as high as in Zurich?</p></li>
</ol>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="week-3-regression-i-prediction.html#cb66-1" tabindex="-1"></a>OriginalOutcome <span class="ot">=</span>  <span class="fu">sum</span>(CO2_land<span class="sc">$</span>jaStimmenAbsolut)<span class="sc">/</span>(<span class="fu">sum</span>(CO2_land<span class="sc">$</span>jaStimmenAbsolut)<span class="sc">+</span><span class="fu">sum</span>(CO2_land<span class="sc">$</span>neinStimmenAbsolut))</span>
<span id="cb66-2"><a href="week-3-regression-i-prediction.html#cb66-2" tabindex="-1"></a>CO2_land<span class="sc">$</span>Valid_TurnOut <span class="ot">=</span>CO2_land<span class="sc">$</span>gueltigeStimmen<span class="sc">/</span>CO2_land<span class="sc">$</span>anzahlStimmberechtigte</span>
<span id="cb66-3"><a href="week-3-regression-i-prediction.html#cb66-3" tabindex="-1"></a></span>
<span id="cb66-4"><a href="week-3-regression-i-prediction.html#cb66-4" tabindex="-1"></a>CO2_land<span class="sc">$</span>OriginalOutcome_test <span class="ot">=</span>  CO2_land<span class="sc">$</span>jaStimmenInProzent <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte <span class="sc">*</span> CO2_land<span class="sc">$</span>Valid_TurnOut <span class="sc">/</span><span class="dv">100</span></span>
<span id="cb66-5"><a href="week-3-regression-i-prediction.html#cb66-5" tabindex="-1"></a></span>
<span id="cb66-6"><a href="week-3-regression-i-prediction.html#cb66-6" tabindex="-1"></a></span>
<span id="cb66-7"><a href="week-3-regression-i-prediction.html#cb66-7" tabindex="-1"></a></span>
<span id="cb66-8"><a href="week-3-regression-i-prediction.html#cb66-8" tabindex="-1"></a><span class="co"># Min</span></span>
<span id="cb66-9"><a href="week-3-regression-i-prediction.html#cb66-9" tabindex="-1"></a>TurnOut_min<span class="ot">=</span> <span class="fu">min</span>(CO2_land<span class="sc">$</span>Valid_TurnOut)</span>
<span id="cb66-10"><a href="week-3-regression-i-prediction.html#cb66-10" tabindex="-1"></a>CO2_land<span class="sc">$</span>Yes_Conterfactual_min<span class="ot">=</span> CO2_land<span class="sc">$</span>jaStimmenInProzent <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte <span class="sc">*</span> TurnOut_min <span class="sc">/</span><span class="dv">100</span></span>
<span id="cb66-11"><a href="week-3-regression-i-prediction.html#cb66-11" tabindex="-1"></a>CO2_land<span class="sc">$</span>No_Conterfactual_min<span class="ot">=</span>  (<span class="dv">100</span><span class="sc">-</span>CO2_land<span class="sc">$</span>jaStimmenInProzent) <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte <span class="sc">*</span> TurnOut_min <span class="sc">/</span><span class="dv">100</span></span>
<span id="cb66-12"><a href="week-3-regression-i-prediction.html#cb66-12" tabindex="-1"></a>CounterfactualOutcome_min<span class="ot">=</span>  <span class="fu">sum</span>(CO2_land<span class="sc">$</span>Yes_Conterfactual_min)<span class="sc">/</span>(<span class="fu">sum</span>(CO2_land<span class="sc">$</span>Yes_Conterfactual_min)<span class="sc">+</span><span class="fu">sum</span>(CO2_land<span class="sc">$</span>No_Conterfactual_min))</span>
<span id="cb66-13"><a href="week-3-regression-i-prediction.html#cb66-13" tabindex="-1"></a></span>
<span id="cb66-14"><a href="week-3-regression-i-prediction.html#cb66-14" tabindex="-1"></a><span class="co"># Max</span></span>
<span id="cb66-15"><a href="week-3-regression-i-prediction.html#cb66-15" tabindex="-1"></a>TurnOut_max<span class="ot">=</span> <span class="fu">max</span>(CO2_land<span class="sc">$</span>Valid_TurnOut)</span>
<span id="cb66-16"><a href="week-3-regression-i-prediction.html#cb66-16" tabindex="-1"></a>CO2_land<span class="sc">$</span>Yes_Conterfactual_max<span class="ot">=</span> CO2_land<span class="sc">$</span>jaStimmenInProzent <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte <span class="sc">*</span> TurnOut_max </span>
<span id="cb66-17"><a href="week-3-regression-i-prediction.html#cb66-17" tabindex="-1"></a>CO2_land<span class="sc">$</span>No_Conterfactual_max<span class="ot">=</span>  (<span class="dv">100</span><span class="sc">-</span>CO2_land<span class="sc">$</span>jaStimmenInProzent) <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte <span class="sc">*</span> TurnOut_max </span>
<span id="cb66-18"><a href="week-3-regression-i-prediction.html#cb66-18" tabindex="-1"></a>CounterfactualOutcome_max<span class="ot">=</span>  <span class="fu">sum</span>(CO2_land<span class="sc">$</span>Yes_Conterfactual_max)<span class="sc">/</span>(<span class="fu">sum</span>(CO2_land<span class="sc">$</span>Yes_Conterfactual_max)<span class="sc">+</span><span class="fu">sum</span>(CO2_land<span class="sc">$</span>No_Conterfactual_max))</span>
<span id="cb66-19"><a href="week-3-regression-i-prediction.html#cb66-19" tabindex="-1"></a></span>
<span id="cb66-20"><a href="week-3-regression-i-prediction.html#cb66-20" tabindex="-1"></a><span class="co"># Zurich</span></span>
<span id="cb66-21"><a href="week-3-regression-i-prediction.html#cb66-21" tabindex="-1"></a>TurnOut_Zurich<span class="ot">=</span> CO2_land<span class="sc">$</span>Valid_TurnOut[CO2_land<span class="sc">$</span>mun_id<span class="sc">==</span><span class="dv">261</span>]</span>
<span id="cb66-22"><a href="week-3-regression-i-prediction.html#cb66-22" tabindex="-1"></a>CO2_land<span class="sc">$</span>Yes_Conterfactual_Zurich<span class="ot">=</span> CO2_land<span class="sc">$</span>jaStimmenInProzent <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte <span class="sc">*</span> TurnOut_Zurich </span>
<span id="cb66-23"><a href="week-3-regression-i-prediction.html#cb66-23" tabindex="-1"></a>CO2_land<span class="sc">$</span>No_Conterfactual_Zurich<span class="ot">=</span>  (<span class="dv">100</span><span class="sc">-</span>CO2_land<span class="sc">$</span>jaStimmenInProzent) <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte <span class="sc">*</span> TurnOut_Zurich </span>
<span id="cb66-24"><a href="week-3-regression-i-prediction.html#cb66-24" tabindex="-1"></a>CounterfactualOutcome_Zurich<span class="ot">=</span>  <span class="fu">sum</span>(CO2_land<span class="sc">$</span>Yes_Conterfactual_Zurich)<span class="sc">/</span>(<span class="fu">sum</span>(CO2_land<span class="sc">$</span>Yes_Conterfactual_Zurich)<span class="sc">+</span><span class="fu">sum</span>(CO2_land<span class="sc">$</span>No_Conterfactual_Zurich))</span>
<span id="cb66-25"><a href="week-3-regression-i-prediction.html#cb66-25" tabindex="-1"></a></span>
<span id="cb66-26"><a href="week-3-regression-i-prediction.html#cb66-26" tabindex="-1"></a><span class="co"># Luzern</span></span>
<span id="cb66-27"><a href="week-3-regression-i-prediction.html#cb66-27" tabindex="-1"></a>TurnOut_Luzern<span class="ot">=</span> CO2_land<span class="sc">$</span>Valid_TurnOut[CO2_land<span class="sc">$</span>mun_id<span class="sc">==</span><span class="dv">1061</span>]</span>
<span id="cb66-28"><a href="week-3-regression-i-prediction.html#cb66-28" tabindex="-1"></a>CO2_land<span class="sc">$</span>Yes_Conterfactual_Luzern<span class="ot">=</span> CO2_land<span class="sc">$</span>jaStimmenInProzent <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte <span class="sc">*</span> TurnOut_Luzern </span>
<span id="cb66-29"><a href="week-3-regression-i-prediction.html#cb66-29" tabindex="-1"></a>CO2_land<span class="sc">$</span>No_Conterfactual_Luzern<span class="ot">=</span>  (<span class="dv">100</span><span class="sc">-</span>CO2_land<span class="sc">$</span>jaStimmenInProzent) <span class="sc">*</span> CO2_land<span class="sc">$</span>anzahlStimmberechtigte <span class="sc">*</span> TurnOut_Luzern </span>
<span id="cb66-30"><a href="week-3-regression-i-prediction.html#cb66-30" tabindex="-1"></a>CounterfactualOutcome_Luzern<span class="ot">=</span>  <span class="fu">sum</span>(CO2_land<span class="sc">$</span>Yes_Conterfactual_Luzern)<span class="sc">/</span>(<span class="fu">sum</span>(CO2_land<span class="sc">$</span>Yes_Conterfactual_Luzern)<span class="sc">+</span><span class="fu">sum</span>(CO2_land<span class="sc">$</span>No_Conterfactual_Luzern))</span>
<span id="cb66-31"><a href="week-3-regression-i-prediction.html#cb66-31" tabindex="-1"></a></span>
<span id="cb66-32"><a href="week-3-regression-i-prediction.html#cb66-32" tabindex="-1"></a></span>
<span id="cb66-33"><a href="week-3-regression-i-prediction.html#cb66-33" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&#39;The original percentage for Yes was:&#39;</span>, OriginalOutcome, </span>
<span id="cb66-34"><a href="week-3-regression-i-prediction.html#cb66-34" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">The counterfactual using the minimum turnout would have been: &quot;</span>, CounterfactualOutcome_min,</span>
<span id="cb66-35"><a href="week-3-regression-i-prediction.html#cb66-35" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">The counterfactual using the maximum turnout would have been: &quot;</span>, CounterfactualOutcome_max,</span>
<span id="cb66-36"><a href="week-3-regression-i-prediction.html#cb66-36" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">The counterfactual using Zurich</span><span class="sc">\&#39;</span><span class="st">s turnout would have been: &quot;</span>, CounterfactualOutcome_Zurich,</span>
<span id="cb66-37"><a href="week-3-regression-i-prediction.html#cb66-37" tabindex="-1"></a>    <span class="st">&quot;</span><span class="sc">\n</span><span class="st">The counterfactual using Luzern</span><span class="sc">\&#39;</span><span class="st">s turnout would have been: &quot;</span>, CounterfactualOutcome_Luzern)</span></code></pre></div>
<pre><code>## The original percentage for Yes was: 0.4812683 
## The counterfactual using the minimum turnout would have been:  0.4854131 
## The counterfactual using the maximum turnout would have been:  0.4854131 
## The counterfactual using Zurich&#39;s turnout would have been:  0.4854131 
## The counterfactual using Luzern&#39;s turnout would have been:  0.4854131</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="week-3-regression-i-prediction.html#cb68-1" tabindex="-1"></a><span class="cf">if</span> ((CounterfactualOutcome_min <span class="sc">&gt;</span>.<span class="dv">5</span>) <span class="sc">|</span> (CounterfactualOutcome_max <span class="sc">&gt;</span>.<span class="dv">5</span>) <span class="sc">|</span> (CounterfactualOutcome_Zurich <span class="sc">&gt;</span>.<span class="dv">5</span>) <span class="sc">|</span> (CounterfactualOutcome_Luzern <span class="sc">&gt;</span>.<span class="dv">5</span>)){</span>
<span id="cb68-2"><a href="week-3-regression-i-prediction.html#cb68-2" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&#39;There is at least one counterfactual where the outcome changes&#39;</span>)</span>
<span id="cb68-3"><a href="week-3-regression-i-prediction.html#cb68-3" tabindex="-1"></a>}<span class="cf">else</span>{</span>
<span id="cb68-4"><a href="week-3-regression-i-prediction.html#cb68-4" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&#39;There is no counterfactual where the outcome changes&#39;</span>)</span>
<span id="cb68-5"><a href="week-3-regression-i-prediction.html#cb68-5" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;There is no counterfactual where the outcome changes&quot;</code></pre>
<ol start="8" style="list-style-type: lower-roman">
<li>Given your preliminary analysis, you find that, on average, municipalities with bigger populations had a lower turn-out than those with smaller ones. To bring some more nuance to your analysis and capture how rural a municipality is, you use the agricultural area of the municipality (<code>AgriculturalAreaHa</code>) as a regressor (aka. independent variable) for the same regressand (aka. dependent variable) of the previous point (i.e., Turn-out in percent). Report and interpret the parameter. Also present the corresponding graph.</li>
</ol>
<p>Write the regression here.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="week-3-regression-i-prediction.html#cb70-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">lm</span>(stimmbeteiligungInProzent <span class="sc">~</span> AgriculturalAreaHa , <span class="at">data =</span> CO2_land)</span>
<span id="cb70-2"><a href="week-3-regression-i-prediction.html#cb70-2" tabindex="-1"></a><span class="fu">summary</span>(result)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = stimmbeteiligungInProzent ~ AgriculturalAreaHa, 
##     data = CO2_land)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -25.189  -5.328   0.202   5.545  31.679 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        6.445e+01  2.128e-01 302.902  &lt; 2e-16 ***
## AgriculturalAreaHa 8.477e-04  1.772e-04   4.784 1.84e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.092 on 2130 degrees of freedom
## Multiple R-squared:  0.01063,    Adjusted R-squared:  0.01016 
## F-statistic: 22.88 on 1 and 2130 DF,  p-value: 1.84e-06</code></pre>
<p>Report and interpret the parameter here.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="week-3-regression-i-prediction.html#cb72-1" tabindex="-1"></a>coeffs<span class="ot">&lt;-</span> <span class="fu">coef</span>(result)</span>
<span id="cb72-2"><a href="week-3-regression-i-prediction.html#cb72-2" tabindex="-1"></a>coeffs</span></code></pre></div>
<pre><code>##        (Intercept) AgriculturalAreaHa 
##       6.444848e+01       8.476927e-04</code></pre>
<p>The estimated (Intercept) is 64.45, while the estimated slope for AgriculturalAreaHa is 0. It means that, across Swiss municipalities, an increase of a thousand voters was associated with an average decrease in the turn-out of 0.85 percentage points.</p>
<p>Present the graph here.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="week-3-regression-i-prediction.html#cb74-1" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb74-2"><a href="week-3-regression-i-prediction.html#cb74-2" tabindex="-1"></a><span class="fu">ggplot</span>(CO2_land, <span class="fu">aes</span>(<span class="at">x =</span> AgriculturalAreaHa, <span class="at">y =</span> stimmbeteiligungInProzent)) <span class="sc">+</span></span>
<span id="cb74-3"><a href="week-3-regression-i-prediction.html#cb74-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb74-4"><a href="week-3-regression-i-prediction.html#cb74-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x , <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;purple&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb74-5"><a href="week-3-regression-i-prediction.html#cb74-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb74-6"><a href="week-3-regression-i-prediction.html#cb74-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb74-7"><a href="week-3-regression-i-prediction.html#cb74-7" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb74-8"><a href="week-3-regression-i-prediction.html#cb74-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Agricultural Area (Ha)&quot;</span>,</span>
<span id="cb74-9"><a href="week-3-regression-i-prediction.html#cb74-9" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Turn-out (%)&quot;</span>,</span>
<span id="cb74-10"><a href="week-3-regression-i-prediction.html#cb74-10" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot with Linear Regression Line&quot;</span></span>
<span id="cb74-11"><a href="week-3-regression-i-prediction.html#cb74-11" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-44-1.png" width="576" /></p>
<ol start="9" style="list-style-type: lower-roman">
<li>The result from the previous point is consistent with the result of the vote given the urban-rural divide in preferences (i.e., municipalities with more agricultural area had higher participation rates). However, you notice that your comparisons across municipalities are not very rigorous because you are ignoring how important agricultural land is with respect to the whole municipality area. An implication of that is that two municipalities with the same agricultural area could be taken as equally rural while one could have a very big urban area (e.g., Zurich) and the other have a very small one.</li>
</ol>
<p>Thus to make your analysis across more comparable units, you transform the absolute value of the agricultural area to a relative one: the percentage of the municipal area that is agricultural. Create the variable <code>AgricAreaPercent</code> to represent those transformed values. Regress the turn-out on the newly created variable. Again, do the regression without intercept. Report and interpret the parameter. Also present the corresponding graph.</p>
<p>Write the regression here.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="week-3-regression-i-prediction.html#cb75-1" tabindex="-1"></a><span class="co">#Transform the units to make them comparable </span></span>
<span id="cb75-2"><a href="week-3-regression-i-prediction.html#cb75-2" tabindex="-1"></a>CO2_land <span class="ot">&lt;-</span> CO2_land <span class="sc">%&gt;%</span></span>
<span id="cb75-3"><a href="week-3-regression-i-prediction.html#cb75-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">AgricAreaPercent=</span> <span class="dv">100</span><span class="sc">*</span>AgriculturalAreaHa<span class="sc">/</span>TotalAreaHa)</span>
<span id="cb75-4"><a href="week-3-regression-i-prediction.html#cb75-4" tabindex="-1"></a></span>
<span id="cb75-5"><a href="week-3-regression-i-prediction.html#cb75-5" tabindex="-1"></a><span class="co">#regression</span></span>
<span id="cb75-6"><a href="week-3-regression-i-prediction.html#cb75-6" tabindex="-1"></a>result0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(stimmbeteiligungInProzent <span class="sc">~</span> AgricAreaPercent , <span class="at">data =</span> CO2_land)</span>
<span id="cb75-7"><a href="week-3-regression-i-prediction.html#cb75-7" tabindex="-1"></a><span class="fu">summary</span>(result0)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = stimmbeteiligungInProzent ~ AgricAreaPercent, data = CO2_land)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -19.971  -4.760  -0.270   4.314  39.145 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      55.189867   0.384603   143.5   &lt;2e-16 ***
## AgricAreaPercent  0.219491   0.007894    27.8   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.969 on 2130 degrees of freedom
## Multiple R-squared:  0.2663, Adjusted R-squared:  0.2659 
## F-statistic: 773.1 on 1 and 2130 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Report and interpret the parameter here.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="week-3-regression-i-prediction.html#cb77-1" tabindex="-1"></a>coeffs<span class="ot">&lt;-</span> <span class="fu">coef</span>(result0)</span>
<span id="cb77-2"><a href="week-3-regression-i-prediction.html#cb77-2" tabindex="-1"></a>coeffs</span></code></pre></div>
<pre><code>##      (Intercept) AgricAreaPercent 
##        55.189867         0.219491</code></pre>
<p>The estimated (Intercept) is 55.19, while the estimated slope for AgricAreaPercent is 0.22. It means that, across Swiss municipalities an increase of one percentage point in the share of agricultural land was associated with an average increase in the turn-out of 0.22 percentage points.</p>
<p>Present the graph here.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="week-3-regression-i-prediction.html#cb79-1" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb79-2"><a href="week-3-regression-i-prediction.html#cb79-2" tabindex="-1"></a><span class="fu">ggplot</span>(CO2_land, <span class="fu">aes</span>(<span class="at">x =</span> AgricAreaPercent, <span class="at">y =</span> stimmbeteiligungInProzent)) <span class="sc">+</span></span>
<span id="cb79-3"><a href="week-3-regression-i-prediction.html#cb79-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb79-4"><a href="week-3-regression-i-prediction.html#cb79-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;purple&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb79-5"><a href="week-3-regression-i-prediction.html#cb79-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb79-6"><a href="week-3-regression-i-prediction.html#cb79-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb79-7"><a href="week-3-regression-i-prediction.html#cb79-7" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb79-8"><a href="week-3-regression-i-prediction.html#cb79-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Agricultural Area (%)&quot;</span>,</span>
<span id="cb79-9"><a href="week-3-regression-i-prediction.html#cb79-9" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Turn-out (%)&quot;</span>,</span>
<span id="cb79-10"><a href="week-3-regression-i-prediction.html#cb79-10" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot with Linear Regression Line&quot;</span></span>
<span id="cb79-11"><a href="week-3-regression-i-prediction.html#cb79-11" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-47-1.png" width="576" /></p>
<ol start="24" style="list-style-type: lower-alpha">
<li>[Optional] While analyzing your results, you asked yourself: what would have happened with my regression if it is estimated without an intercept? In particular, you asked yourself: does the the distance from each data point to the regression line decrease when an intercept is used? See this <a href="https://en.wikipedia.org/wiki/Coefficient_of_determination">entry</a>, particularly the graph with the blue and red squares to understand the logic of the R^2 as a measure for goodness of fit. You want to compare both the regression lines with and without the intercept in one same graph. Do it. What lesson can you get from this comparison?</li>
</ol>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="week-3-regression-i-prediction.html#cb80-1" tabindex="-1"></a><span class="fu">ggplot</span>(CO2_land, <span class="fu">aes</span>(<span class="at">x =</span> AgricAreaPercent, <span class="at">y =</span> stimmbeteiligungInProzent)) <span class="sc">+</span></span>
<span id="cb80-2"><a href="week-3-regression-i-prediction.html#cb80-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb80-3"><a href="week-3-regression-i-prediction.html#cb80-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x<span class="dv">-1</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb80-4"><a href="week-3-regression-i-prediction.html#cb80-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;purple&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb80-5"><a href="week-3-regression-i-prediction.html#cb80-5" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="fu">max</span>(CO2_land<span class="sc">$</span>stimmbeteiligungInProzent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">+</span>  <span class="co">#</span></span>
<span id="cb80-6"><a href="week-3-regression-i-prediction.html#cb80-6" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb80-7"><a href="week-3-regression-i-prediction.html#cb80-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb80-8"><a href="week-3-regression-i-prediction.html#cb80-8" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb80-9"><a href="week-3-regression-i-prediction.html#cb80-9" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Agricultural Area (%)&quot;</span>,</span>
<span id="cb80-10"><a href="week-3-regression-i-prediction.html#cb80-10" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Turn-out (%)&quot;</span>,</span>
<span id="cb80-11"><a href="week-3-regression-i-prediction.html#cb80-11" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot with Linear Regression Line&quot;</span></span>
<span id="cb80-12"><a href="week-3-regression-i-prediction.html#cb80-12" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-48-1.png" width="576" /></p>
<p>The lesson is that using the intercept is always desirable as it can potentially improve the goodness of fit, while doesn’t worsen it (i.e., the optimal intercept could be estimated to be zero). As it is clear from the graph, not using the intercept provides less reliable predictions and general descriptions for the relation between our variables of interest.</p>
<ol start="11" style="list-style-type: lower-roman">
<li>[Optional] Now add a vertical line with the average for the agricultural area, and a horizontal one with the average turn-out. What does this new graph tell you about the descriptive performance of a regression with and without intercepts?</li>
</ol>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="week-3-regression-i-prediction.html#cb81-1" tabindex="-1"></a><span class="co">#Means for Y and X</span></span>
<span id="cb81-2"><a href="week-3-regression-i-prediction.html#cb81-2" tabindex="-1"></a>mean_AgricAreaPercent <span class="ot">&lt;-</span> <span class="fu">mean</span>(CO2_land<span class="sc">$</span>AgricAreaPercent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb81-3"><a href="week-3-regression-i-prediction.html#cb81-3" tabindex="-1"></a>mean_stimmbeteiligungInProzent <span class="ot">&lt;-</span> <span class="fu">mean</span>(CO2_land<span class="sc">$</span>stimmbeteiligungInProzent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb81-4"><a href="week-3-regression-i-prediction.html#cb81-4" tabindex="-1"></a></span>
<span id="cb81-5"><a href="week-3-regression-i-prediction.html#cb81-5" tabindex="-1"></a><span class="co"># Create a scatter plot</span></span>
<span id="cb81-6"><a href="week-3-regression-i-prediction.html#cb81-6" tabindex="-1"></a><span class="fu">ggplot</span>(CO2_land, <span class="fu">aes</span>(<span class="at">x =</span> AgricAreaPercent, <span class="at">y =</span> stimmbeteiligungInProzent)) <span class="sc">+</span></span>
<span id="cb81-7"><a href="week-3-regression-i-prediction.html#cb81-7" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb81-8"><a href="week-3-regression-i-prediction.html#cb81-8" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x <span class="sc">-</span> <span class="dv">1</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb81-9"><a href="week-3-regression-i-prediction.html#cb81-9" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;purple&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb81-10"><a href="week-3-regression-i-prediction.html#cb81-10" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_stimmbeteiligungInProzent, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb81-11"><a href="week-3-regression-i-prediction.html#cb81-11" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_AgricAreaPercent, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb81-12"><a href="week-3-regression-i-prediction.html#cb81-12" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="fu">max</span>(CO2_land<span class="sc">$</span>stimmbeteiligungInProzent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">+</span>  <span class="co">#</span></span>
<span id="cb81-13"><a href="week-3-regression-i-prediction.html#cb81-13" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb81-14"><a href="week-3-regression-i-prediction.html#cb81-14" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb81-15"><a href="week-3-regression-i-prediction.html#cb81-15" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb81-16"><a href="week-3-regression-i-prediction.html#cb81-16" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Agricultural Area (%)&quot;</span>,</span>
<span id="cb81-17"><a href="week-3-regression-i-prediction.html#cb81-17" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Turn-out (%)&quot;</span>,</span>
<span id="cb81-18"><a href="week-3-regression-i-prediction.html#cb81-18" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot with Linear Regression Line&quot;</span></span>
<span id="cb81-19"><a href="week-3-regression-i-prediction.html#cb81-19" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-49-1.png" width="576" />
The descriptive performance of a regression with an intercept is better than without it. As the graph shows, the vertical and horizontal lines for the averages of the dependent and independent variables overlap with each other in exactly the same place where the regression line with intercept goes through. This shows the capability of single linear regression to capture central tendency of the fitted data. On the contrary, the regression without intercept does not do that. Once again, this shows how the descriptive performance of a regression with intercept captures more intuitively the general relation between one variable and another.</p>
<ol start="12" style="list-style-type: lower-roman">
<li>Store the residuals as <code>residuals</code>. Plot the share of agricultural area against the residuals. What does it tell you regarding the ability of the model to describe the central tendency of the relationship across all values of the agricultural land share?</li>
</ol>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="week-3-regression-i-prediction.html#cb82-1" tabindex="-1"></a>residuals0 <span class="ot">&lt;-</span> <span class="fu">residuals</span>(result0)</span>
<span id="cb82-2"><a href="week-3-regression-i-prediction.html#cb82-2" tabindex="-1"></a></span>
<span id="cb82-3"><a href="week-3-regression-i-prediction.html#cb82-3" tabindex="-1"></a><span class="fu">ggplot</span>(CO2_land, <span class="fu">aes</span>(<span class="at">x =</span> AgricAreaPercent, <span class="at">y =</span> residuals0)) <span class="sc">+</span></span>
<span id="cb82-4"><a href="week-3-regression-i-prediction.html#cb82-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb82-5"><a href="week-3-regression-i-prediction.html#cb82-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x , <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>)<span class="sc">+</span>  <span class="co"># Adding the</span></span>
<span id="cb82-6"><a href="week-3-regression-i-prediction.html#cb82-6" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb82-7"><a href="week-3-regression-i-prediction.html#cb82-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb82-8"><a href="week-3-regression-i-prediction.html#cb82-8" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb82-9"><a href="week-3-regression-i-prediction.html#cb82-9" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Agricultural Area (%)&quot;</span>,</span>
<span id="cb82-10"><a href="week-3-regression-i-prediction.html#cb82-10" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Residuals (turn-out p.p.)&quot;</span>,</span>
<span id="cb82-11"><a href="week-3-regression-i-prediction.html#cb82-11" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot with Linear Regression Line&quot;</span></span>
<span id="cb82-12"><a href="week-3-regression-i-prediction.html#cb82-12" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-50-1.png" width="576" />
The existence of a horizontal slope between the residuals (i.e., the distance between the prediction and the real value) and the agricultural share suggests that our model has systematically captured the relation between our variables: the average error does not not change systematically across the values of the agricultural share.</p>
<ol start="13" style="list-style-type: lower-roman">
<li>[Optional] Repeat the previous point without the intercept. Does the linear regression remains a good tool for describing the central tendency of the relationship across all values of the agricultural land share?</li>
</ol>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="week-3-regression-i-prediction.html#cb83-1" tabindex="-1"></a><span class="co">#regression</span></span>
<span id="cb83-2"><a href="week-3-regression-i-prediction.html#cb83-2" tabindex="-1"></a>result1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(stimmbeteiligungInProzent <span class="sc">~</span> AgricAreaPercent <span class="sc">-</span><span class="dv">1</span> , <span class="at">data =</span> CO2_land)</span>
<span id="cb83-3"><a href="week-3-regression-i-prediction.html#cb83-3" tabindex="-1"></a><span class="fu">summary</span>(result1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = stimmbeteiligungInProzent ~ AgricAreaPercent - 1, 
##     data = CO2_land)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -42.102  -7.509   6.449  23.631  83.331 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## AgricAreaPercent  1.26144    0.01012   124.7   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 22.75 on 2131 degrees of freedom
## Multiple R-squared:  0.8795, Adjusted R-squared:  0.8794 
## F-statistic: 1.555e+04 on 1 and 2131 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="week-3-regression-i-prediction.html#cb85-1" tabindex="-1"></a>residuals1 <span class="ot">&lt;-</span> <span class="fu">residuals</span>(result1)</span>
<span id="cb85-2"><a href="week-3-regression-i-prediction.html#cb85-2" tabindex="-1"></a></span>
<span id="cb85-3"><a href="week-3-regression-i-prediction.html#cb85-3" tabindex="-1"></a><span class="fu">ggplot</span>(CO2_land, <span class="fu">aes</span>(<span class="at">x =</span> AgricAreaPercent, <span class="at">y =</span> residuals1)) <span class="sc">+</span></span>
<span id="cb85-4"><a href="week-3-regression-i-prediction.html#cb85-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb85-5"><a href="week-3-regression-i-prediction.html#cb85-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x , <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>)<span class="sc">+</span>  <span class="co"># Adding the</span></span>
<span id="cb85-6"><a href="week-3-regression-i-prediction.html#cb85-6" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb85-7"><a href="week-3-regression-i-prediction.html#cb85-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb85-8"><a href="week-3-regression-i-prediction.html#cb85-8" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb85-9"><a href="week-3-regression-i-prediction.html#cb85-9" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Agricultural Area (%)&quot;</span>,</span>
<span id="cb85-10"><a href="week-3-regression-i-prediction.html#cb85-10" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Residuals (turn-out p.p.)&quot;</span>,</span>
<span id="cb85-11"><a href="week-3-regression-i-prediction.html#cb85-11" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scatter plot with Linear Regression Line&quot;</span></span>
<span id="cb85-12"><a href="week-3-regression-i-prediction.html#cb85-12" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-51-1.png" width="576" /></p>
<p>Unlike the graph of the previous point showed that no systematic relation between the residual and our regressor was not captured by our model, the graph of this point shows a systematic behavior of the residuals. In this case, it is the fact that the model is too inflexible (i.e., the line must always go through the origin) which leads the model to predict the values of our regressand in a systematically mistaken way: the average error does change systematically across the values of the agricultural share, being systematically positive for lower age values, while systematically negative for high age values.</p>
</div>
<div id="simulated-data" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Simulated data<a href="week-3-regression-i-prediction.html#simulated-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: lower-roman">
<li>You will now simulate the relationship between turn-out and share of agricultural land. Assume the parameters estimated in the last regression (i.e., the <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>). Retrieve both parameters.</li>
</ol>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="week-3-regression-i-prediction.html#cb86-1" tabindex="-1"></a>coeffs<span class="ot">&lt;-</span> <span class="fu">coef</span>(result0)</span>
<span id="cb86-2"><a href="week-3-regression-i-prediction.html#cb86-2" tabindex="-1"></a><span class="fu">print</span>(coeffs)</span></code></pre></div>
<pre><code>##      (Intercept) AgricAreaPercent 
##        55.189867         0.219491</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="week-3-regression-i-prediction.html#cb88-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">unname</span>(coeffs[<span class="dv">1</span>]), <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 55</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="week-3-regression-i-prediction.html#cb90-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">unname</span>(coeffs[<span class="dv">2</span>]), <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.22</code></pre>
<ol start="2" style="list-style-type: lower-roman">
<li>Use the parameters to define the assumed data generating process. Assume that the process is deterministic (i.e., it has no stochastic component). Express the equation using mathematical notation.</li>
</ol>
<p><span class="math display">\[TurnOut_i = \beta_0 + \beta_1 * ShareAgriculturalLand\]</span></p>
<ol start="3" style="list-style-type: lower-roman">
<li>Generate a normal distribution that preserves the mean and standard deviation of the original data on share of agricultural land.</li>
</ol>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="week-3-regression-i-prediction.html#cb92-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># to ensure reproducibility: should different people use different random draws, the results won&#39;t be consistent. Thus, should all use the same random draw, all should have the same results.</span></span>
<span id="cb92-2"><a href="week-3-regression-i-prediction.html#cb92-2" tabindex="-1"></a>CO2_land<span class="sc">$</span>Sim_ShareAgric_norm <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fu">nrow</span>(CO2_land), <span class="at">mean =</span> mean_AgricAreaPercent, <span class="at">sd =</span> <span class="fu">sd</span>(CO2_land<span class="sc">$</span>AgricAreaPercent))</span>
<span id="cb92-3"><a href="week-3-regression-i-prediction.html#cb92-3" tabindex="-1"></a></span>
<span id="cb92-4"><a href="week-3-regression-i-prediction.html#cb92-4" tabindex="-1"></a><span class="fu">hist</span>(CO2_land<span class="sc">$</span>Sim_ShareAgric_norm, </span>
<span id="cb92-5"><a href="week-3-regression-i-prediction.html#cb92-5" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Histogram of Share of Simulated Agricultural Land&quot;</span>, </span>
<span id="cb92-6"><a href="week-3-regression-i-prediction.html#cb92-6" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Data Values&quot;</span>, </span>
<span id="cb92-7"><a href="week-3-regression-i-prediction.html#cb92-7" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Frequency&quot;</span>, </span>
<span id="cb92-8"><a href="week-3-regression-i-prediction.html#cb92-8" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, </span>
<span id="cb92-9"><a href="week-3-regression-i-prediction.html#cb92-9" tabindex="-1"></a>     <span class="at">border=</span><span class="st">&quot;black&quot;</span>)</span>
<span id="cb92-10"><a href="week-3-regression-i-prediction.html#cb92-10" tabindex="-1"></a></span>
<span id="cb92-11"><a href="week-3-regression-i-prediction.html#cb92-11" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span>mean_AgricAreaPercent, <span class="at">col=</span><span class="st">&quot;red&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-53-1.png" width="576" /></p>
<ol start="4" style="list-style-type: lower-roman">
<li>Predict the turn-out values given the simulated inputs on the share of agricultural land using the data generating process defined in point i). Graph relation between both variables using a liner regression line.</li>
</ol>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="week-3-regression-i-prediction.html#cb93-1" tabindex="-1"></a>CO2_land<span class="sc">$</span>Pred_TurnOut_Determ <span class="ot">&lt;-</span> <span class="fu">unname</span>(coeffs[<span class="dv">1</span>]) <span class="sc">+</span> <span class="fu">unname</span>(coeffs[<span class="dv">2</span>])<span class="sc">*</span>CO2_land<span class="sc">$</span>Sim_ShareAgric_norm</span>
<span id="cb93-2"><a href="week-3-regression-i-prediction.html#cb93-2" tabindex="-1"></a></span>
<span id="cb93-3"><a href="week-3-regression-i-prediction.html#cb93-3" tabindex="-1"></a></span>
<span id="cb93-4"><a href="week-3-regression-i-prediction.html#cb93-4" tabindex="-1"></a><span class="fu">ggplot</span>(CO2_land, <span class="fu">aes</span>(<span class="at">x =</span> Sim_ShareAgric_norm, <span class="at">y =</span> Pred_TurnOut_Determ)) <span class="sc">+</span></span>
<span id="cb93-5"><a href="week-3-regression-i-prediction.html#cb93-5" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb93-6"><a href="week-3-regression-i-prediction.html#cb93-6" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;purple&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb93-7"><a href="week-3-regression-i-prediction.html#cb93-7" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_stimmbeteiligungInProzent, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb93-8"><a href="week-3-regression-i-prediction.html#cb93-8" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_AgricAreaPercent, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb93-9"><a href="week-3-regression-i-prediction.html#cb93-9" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="fu">max</span>(CO2_land<span class="sc">$</span>stimmbeteiligungInProzent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">+</span>  <span class="co">#</span></span>
<span id="cb93-10"><a href="week-3-regression-i-prediction.html#cb93-10" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb93-11"><a href="week-3-regression-i-prediction.html#cb93-11" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb93-12"><a href="week-3-regression-i-prediction.html#cb93-12" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb93-13"><a href="week-3-regression-i-prediction.html#cb93-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Agricultural Area (%)&quot;</span>,</span>
<span id="cb93-14"><a href="week-3-regression-i-prediction.html#cb93-14" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Turn-out (%)&quot;</span>,</span>
<span id="cb93-15"><a href="week-3-regression-i-prediction.html#cb93-15" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Simulation: deterministic model&quot;</span></span>
<span id="cb93-16"><a href="week-3-regression-i-prediction.html#cb93-16" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-54-1.png" width="576" />
As expected, this deterministic model generates points on top of the regression line defined by the intercept and slope of the data generating process. Unlike in reality, we have no random errors generating random deviations from the regression line (i.e., we have no cloud of points, but they are all on top of the line).</p>
<ol start="22" style="list-style-type: lower-alpha">
<li>Generate a normal distribution with error distribution with mean zero and standard deviation equal to the standard deviation of the residual of the model with intercept.</li>
</ol>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="week-3-regression-i-prediction.html#cb94-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb94-2"><a href="week-3-regression-i-prediction.html#cb94-2" tabindex="-1"></a>CO2_land<span class="sc">$</span>Sim_resid_norm <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fu">nrow</span>(CO2_land), <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="fu">sd</span>(residuals0))</span>
<span id="cb94-3"><a href="week-3-regression-i-prediction.html#cb94-3" tabindex="-1"></a></span>
<span id="cb94-4"><a href="week-3-regression-i-prediction.html#cb94-4" tabindex="-1"></a><span class="fu">hist</span>(CO2_land<span class="sc">$</span>Sim_resid_norm, </span>
<span id="cb94-5"><a href="week-3-regression-i-prediction.html#cb94-5" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Histogram of Simulated Normal Residuals&quot;</span>, </span>
<span id="cb94-6"><a href="week-3-regression-i-prediction.html#cb94-6" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Data Values&quot;</span>, </span>
<span id="cb94-7"><a href="week-3-regression-i-prediction.html#cb94-7" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Frequency&quot;</span>, </span>
<span id="cb94-8"><a href="week-3-regression-i-prediction.html#cb94-8" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, </span>
<span id="cb94-9"><a href="week-3-regression-i-prediction.html#cb94-9" tabindex="-1"></a>     <span class="at">border=</span><span class="st">&quot;black&quot;</span>)</span>
<span id="cb94-10"><a href="week-3-regression-i-prediction.html#cb94-10" tabindex="-1"></a></span>
<span id="cb94-11"><a href="week-3-regression-i-prediction.html#cb94-11" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-55-1.png" width="576" /></p>
<ol start="6" style="list-style-type: lower-roman">
<li>Now add the stochastic element to the fully deterministic model of point iv). Graph the relation between both variables using a liner regression line.</li>
</ol>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="week-3-regression-i-prediction.html#cb95-1" tabindex="-1"></a>CO2_land<span class="sc">$</span>Pred_TurnOut_Stoch <span class="ot">&lt;-</span> CO2_land<span class="sc">$</span>Pred_TurnOut_Determ <span class="sc">+</span> CO2_land<span class="sc">$</span>Sim_resid_norm</span>
<span id="cb95-2"><a href="week-3-regression-i-prediction.html#cb95-2" tabindex="-1"></a></span>
<span id="cb95-3"><a href="week-3-regression-i-prediction.html#cb95-3" tabindex="-1"></a><span class="fu">ggplot</span>(CO2_land, <span class="fu">aes</span>(<span class="at">x =</span> Sim_ShareAgric_norm, <span class="at">y =</span> Pred_TurnOut_Stoch)) <span class="sc">+</span></span>
<span id="cb95-4"><a href="week-3-regression-i-prediction.html#cb95-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb95-5"><a href="week-3-regression-i-prediction.html#cb95-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;purple&quot;</span>) <span class="sc">+</span>  <span class="co"># Adding the regression line</span></span>
<span id="cb95-6"><a href="week-3-regression-i-prediction.html#cb95-6" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_stimmbeteiligungInProzent, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  <span class="co"># Horizontal line at the mean of y</span></span>
<span id="cb95-7"><a href="week-3-regression-i-prediction.html#cb95-7" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_AgricAreaPercent, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  <span class="co"># Vertical line at the mean of x</span></span>
<span id="cb95-8"><a href="week-3-regression-i-prediction.html#cb95-8" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="fu">max</span>(CO2_land<span class="sc">$</span>Sim_ShareAgric_norm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">+</span>  <span class="co">#</span></span>
<span id="cb95-9"><a href="week-3-regression-i-prediction.html#cb95-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb95-10"><a href="week-3-regression-i-prediction.html#cb95-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb95-11"><a href="week-3-regression-i-prediction.html#cb95-11" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb95-12"><a href="week-3-regression-i-prediction.html#cb95-12" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Agricultural Area (%)&quot;</span>,</span>
<span id="cb95-13"><a href="week-3-regression-i-prediction.html#cb95-13" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Turn-out (%)&quot;</span>,</span>
<span id="cb95-14"><a href="week-3-regression-i-prediction.html#cb95-14" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Simulation: deterministic and stochastic model&quot;</span></span>
<span id="cb95-15"><a href="week-3-regression-i-prediction.html#cb95-15" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-56-1.png" width="576" />
The previous graph presents the relation between our simulated independent variable and residual, both of which fully generate our dependent variable (i.e., only using the regression parameters to predict the observations over the line and then adding the residuals we can generate all the values for our dependent variable).</p>
<ol start="7" style="list-style-type: lower-roman">
<li>[Optional] Now repeat the same simulation but generating errors that distribute uniformly. Use the maximum, and minimum values of the residuals for the model with intercept to define the distribution of residuals.</li>
</ol>
<p>Uniform simulated residuals:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="week-3-regression-i-prediction.html#cb96-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb96-2"><a href="week-3-regression-i-prediction.html#cb96-2" tabindex="-1"></a>CO2_land<span class="sc">$</span>Sim_resid_unif <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="fu">nrow</span>(CO2_land), <span class="at">min =</span> <span class="fu">min</span>(residuals0), <span class="at">max =</span> <span class="fu">max</span>(residuals0))</span>
<span id="cb96-3"><a href="week-3-regression-i-prediction.html#cb96-3" tabindex="-1"></a></span>
<span id="cb96-4"><a href="week-3-regression-i-prediction.html#cb96-4" tabindex="-1"></a><span class="fu">hist</span>(CO2_land<span class="sc">$</span>Sim_resid_unif, </span>
<span id="cb96-5"><a href="week-3-regression-i-prediction.html#cb96-5" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Histogram of Simulated Uniform Residuals&quot;</span>, </span>
<span id="cb96-6"><a href="week-3-regression-i-prediction.html#cb96-6" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Data Values&quot;</span>, </span>
<span id="cb96-7"><a href="week-3-regression-i-prediction.html#cb96-7" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Frequency&quot;</span>, </span>
<span id="cb96-8"><a href="week-3-regression-i-prediction.html#cb96-8" tabindex="-1"></a>     <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, </span>
<span id="cb96-9"><a href="week-3-regression-i-prediction.html#cb96-9" tabindex="-1"></a>     <span class="at">border=</span><span class="st">&quot;black&quot;</span>)</span>
<span id="cb96-10"><a href="week-3-regression-i-prediction.html#cb96-10" tabindex="-1"></a></span>
<span id="cb96-11"><a href="week-3-regression-i-prediction.html#cb96-11" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-57-1.png" width="576" /></p>
<p>Data generating process with uniform residuals:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="week-3-regression-i-prediction.html#cb97-1" tabindex="-1"></a>CO2_land<span class="sc">$</span>Pred_TurnOut_Unif <span class="ot">&lt;-</span> CO2_land<span class="sc">$</span>Pred_TurnOut_Determ <span class="sc">+</span> CO2_land<span class="sc">$</span>Sim_resid_unif</span>
<span id="cb97-2"><a href="week-3-regression-i-prediction.html#cb97-2" tabindex="-1"></a></span>
<span id="cb97-3"><a href="week-3-regression-i-prediction.html#cb97-3" tabindex="-1"></a></span>
<span id="cb97-4"><a href="week-3-regression-i-prediction.html#cb97-4" tabindex="-1"></a></span>
<span id="cb97-5"><a href="week-3-regression-i-prediction.html#cb97-5" tabindex="-1"></a><span class="fu">ggplot</span>(CO2_land, <span class="fu">aes</span>(<span class="at">x =</span> Sim_ShareAgric_norm, <span class="at">y =</span> Pred_TurnOut_Unif)) <span class="sc">+</span></span>
<span id="cb97-6"><a href="week-3-regression-i-prediction.html#cb97-6" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb97-7"><a href="week-3-regression-i-prediction.html#cb97-7" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;purple&quot;</span>) <span class="sc">+</span> </span>
<span id="cb97-8"><a href="week-3-regression-i-prediction.html#cb97-8" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(CO2_land<span class="sc">$</span>Pred_TurnOut_Unif), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span>  </span>
<span id="cb97-9"><a href="week-3-regression-i-prediction.html#cb97-9" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_AgricAreaPercent, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span>  </span>
<span id="cb97-10"><a href="week-3-regression-i-prediction.html#cb97-10" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="fu">max</span>(CO2_land<span class="sc">$</span>Pred_TurnOut_Unif, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">+</span>  </span>
<span id="cb97-11"><a href="week-3-regression-i-prediction.html#cb97-11" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb97-12"><a href="week-3-regression-i-prediction.html#cb97-12" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb97-13"><a href="week-3-regression-i-prediction.html#cb97-13" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb97-14"><a href="week-3-regression-i-prediction.html#cb97-14" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Agricultural Area (%)&quot;</span>,</span>
<span id="cb97-15"><a href="week-3-regression-i-prediction.html#cb97-15" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Turn-out (%)&quot;</span>,</span>
<span id="cb97-16"><a href="week-3-regression-i-prediction.html#cb97-16" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Simulation: deterministic and stochastic model (uniform error)&quot;</span></span>
<span id="cb97-17"><a href="week-3-regression-i-prediction.html#cb97-17" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-58-1.png" width="576" /></p>
</div>
</div>
<div id="appendix-getting-the-data-first" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Appendix: Getting the data first<a href="week-3-regression-i-prediction.html#appendix-getting-the-data-first" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To get the data, you will use an API (application programming interface). Put plainly, for the sake of this exercise you can think of an API like a <a href="https://www.youtube.com/watch?v=s7wmiS2mSXY">waiter</a> to whom you make a request and who gets what ever you requested from the kitchen (a remote data source).</p>
<p>In this case, you will use two APIs: to get election results in Switzerland, <a href="https://politanch.github.io/swissdd/index.html"><code>swissdd</code></a>, and <a href="https://github.com/lgnbhl/BFS"><code>BFS</code></a> to get many other kinds of statistical information. Both APIs get information from the Federal Statistical Office (Bundesamt für Statistik).</p>
<p>Skimm the functions of the <a href="https://politanch.github.io/swissdd/reference/index.html">Swissdd</a> package. Then, inspect the <a href="https://swissvotes.ch/storage/b47562b197b7725fcfa45b3e5a4abad1b4cf14cd377136f87fd4473329a51114">codebook</a> to understand what for the columns and rows stand for. Do not use more than 5 minutes doing it.</p>
<p>To get the data, simply execute the following code. We present you with the code so, if you want, you can know how it works and you can play around with it on your own following the code’s logic.</p>
<p>Install the <code>Swissdd</code> package</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="week-3-regression-i-prediction.html#cb98-1" tabindex="-1"></a><span class="co">#First option  - from CRAN. If you install it from the github repository, make sure you have the `devtools` installed in advance.</span></span>
<span id="cb98-2"><a href="week-3-regression-i-prediction.html#cb98-2" tabindex="-1"></a><span class="co">#install.packages(&quot;swissdd&quot;)</span></span>
<span id="cb98-3"><a href="week-3-regression-i-prediction.html#cb98-3" tabindex="-1"></a></span>
<span id="cb98-4"><a href="week-3-regression-i-prediction.html#cb98-4" tabindex="-1"></a><span class="co">#Second option</span></span>
<span id="cb98-5"><a href="week-3-regression-i-prediction.html#cb98-5" tabindex="-1"></a><span class="co"># install.packages(&quot;devtools&quot;) # it is necessary to comment the install.packages so the book can be rendered</span></span>
<span id="cb98-6"><a href="week-3-regression-i-prediction.html#cb98-6" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;politanch/swissdd&quot;</span>, <span class="at">force =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## ── R CMD build ─────────────────────────────────────────────────────────────────
## * checking for file ‘/private/var/folders/fg/p53z0kxs5g35bp_2wq9x5vfdsyrmgw/T/Rtmp8kAvOf/remotesc83113cf314/politanch-swissdd-04bb42c/DESCRIPTION’ ... OK
## * preparing ‘swissdd’:
## * checking DESCRIPTION meta-information ... OK
## * checking for LF line-endings in source and make files and shell scripts
## * checking for empty or unneeded directories
## * building ‘swissdd_1.1.5.tar.gz’
## Warning: invalid uid value replaced by that for user &#39;nobody&#39;
## Warning: invalid gid value replaced by that for user &#39;nobody&#39;</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="week-3-regression-i-prediction.html#cb100-1" tabindex="-1"></a><span class="co"># library(swissdd)</span></span></code></pre></div>
<p>Retrieve the <a href="https://swissvotes.ch/vote/644.00">CO2 Act</a> information using <code>get_nationalvotes</code>. The vote took place in 13/06/2021.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="week-3-regression-i-prediction.html#cb101-1" tabindex="-1"></a>CO2<span class="ot">&lt;-</span><span class="fu">get_nationalvotes</span>(<span class="at">votedates =</span> <span class="st">&quot;2021-06-13&quot;</span>)</span></code></pre></div>
<p>As the same day of the CO2 Act vote more initiatives were voted, keep only the one we care about for this exercise. Notice that each initiative has a numerical identifier called <code>id</code>. <a href="https://swissvotes.ch/vote/644.00">Here</a> you can find the numerical identifier under <code>Vote Nº</code>. Keep in mind that, the variable <code>id</code> has the same number as in <code>Vote Nº</code> with an additional zero to the right.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="week-3-regression-i-prediction.html#cb102-1" tabindex="-1"></a>CO2<span class="ot">&lt;-</span> CO2 <span class="sc">%&gt;%</span></span>
<span id="cb102-2"><a href="week-3-regression-i-prediction.html#cb102-2" tabindex="-1"></a>  <span class="fu">filter</span>(id<span class="sc">==</span><span class="dv">6440</span>)</span></code></pre></div>
<p>The resulting data frame contains rows representing the results for a particular vote in a particular municipality. The columns qualify that vote. Use the <code>colnames()</code> function to see the names of the columns. Keep only those that might be relevant for your analysis.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="week-3-regression-i-prediction.html#cb103-1" tabindex="-1"></a>CO2<span class="ot">&lt;-</span> CO2 <span class="sc">%&gt;%</span></span>
<span id="cb103-2"><a href="week-3-regression-i-prediction.html#cb103-2" tabindex="-1"></a>  <span class="fu">select</span>(canton_id, canton_name, mun_id, mun_name, jaStimmenInProzent, jaStimmenAbsolut, neinStimmenAbsolut, stimmbeteiligungInProzent, eingelegteStimmzettel, anzahlStimmberechtigte, gueltigeStimmen)</span></code></pre></div>
<p>Finally, as you want to see the turn-out differences between municipalities with different degrees of agriculture intensity you need to get some additional data. Run the following code.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="week-3-regression-i-prediction.html#cb104-1" tabindex="-1"></a><span class="co"># install.packages(&quot;BFS&quot;)</span></span>
<span id="cb104-2"><a href="week-3-regression-i-prediction.html#cb104-2" tabindex="-1"></a><span class="co"># library(BFS)</span></span>
<span id="cb104-3"><a href="week-3-regression-i-prediction.html#cb104-3" tabindex="-1"></a><span class="co">#To see the information available in German</span></span>
<span id="cb104-4"><a href="week-3-regression-i-prediction.html#cb104-4" tabindex="-1"></a><span class="co"># catalog_data_de &lt;- bfs_get_catalog_data(language = &quot;de&quot;)</span></span>
<span id="cb104-5"><a href="week-3-regression-i-prediction.html#cb104-5" tabindex="-1"></a></span>
<span id="cb104-6"><a href="week-3-regression-i-prediction.html#cb104-6" tabindex="-1"></a><span class="co">#To see the information available in English</span></span>
<span id="cb104-7"><a href="week-3-regression-i-prediction.html#cb104-7" tabindex="-1"></a><span class="co">#catalog_data_en &lt;- bfs_get_catalog_data(language = &quot;en&quot;)</span></span>
<span id="cb104-8"><a href="week-3-regression-i-prediction.html#cb104-8" tabindex="-1"></a></span>
<span id="cb104-9"><a href="week-3-regression-i-prediction.html#cb104-9" tabindex="-1"></a><span class="co">#To see the information available in German that contains a particular word in the title</span></span>
<span id="cb104-10"><a href="week-3-regression-i-prediction.html#cb104-10" tabindex="-1"></a><span class="co">#catalog_data_de &lt;- bfs_get_catalog_data(language = &quot;de&quot;, title=&quot;Gemeinde&quot;)</span></span>
<span id="cb104-11"><a href="week-3-regression-i-prediction.html#cb104-11" tabindex="-1"></a></span>
<span id="cb104-12"><a href="week-3-regression-i-prediction.html#cb104-12" tabindex="-1"></a><span class="co">#To get the asset number (i.e., numerical id for a data set)</span></span>
<span id="cb104-13"><a href="week-3-regression-i-prediction.html#cb104-13" tabindex="-1"></a><span class="co"># asset_number &lt;- catalog_data_de %&gt;%</span></span>
<span id="cb104-14"><a href="week-3-regression-i-prediction.html#cb104-14" tabindex="-1"></a><span class="co">#   filter(title == &quot;Arealstatistik: Standardnomenklatur (NOAS04) nach Bezirk und Gemeinde, in Hektaren&quot;) %&gt;%</span></span>
<span id="cb104-15"><a href="week-3-regression-i-prediction.html#cb104-15" tabindex="-1"></a><span class="co">#   pull(number_asset)</span></span>
<span id="cb104-16"><a href="week-3-regression-i-prediction.html#cb104-16" tabindex="-1"></a></span>
<span id="cb104-17"><a href="week-3-regression-i-prediction.html#cb104-17" tabindex="-1"></a><span class="co">#Using that asset number, the metadata (i.e., data that describes the data set) can be accessed.</span></span>
<span id="cb104-18"><a href="week-3-regression-i-prediction.html#cb104-18" tabindex="-1"></a><span class="co">#asset_meta &lt;- bfs_get_asset_metadata(number_asset = asset_number)</span></span>
<span id="cb104-19"><a href="week-3-regression-i-prediction.html#cb104-19" tabindex="-1"></a></span>
<span id="cb104-20"><a href="week-3-regression-i-prediction.html#cb104-20" tabindex="-1"></a><span class="co">#From the metadata, the bfs number (i.e., a alphanumeric id for the data set) can be accessed.</span></span>
<span id="cb104-21"><a href="week-3-regression-i-prediction.html#cb104-21" tabindex="-1"></a><span class="co">#bfs_number &lt;- asset_meta$shop$orderNr</span></span>
<span id="cb104-22"><a href="week-3-regression-i-prediction.html#cb104-22" tabindex="-1"></a></span>
<span id="cb104-23"><a href="week-3-regression-i-prediction.html#cb104-23" tabindex="-1"></a><span class="co">#Finally, using the bfs number the data set can be accessed.</span></span>
<span id="cb104-24"><a href="week-3-regression-i-prediction.html#cb104-24" tabindex="-1"></a><span class="co">#LandUse &lt;- bfs_get_data(number_bfs = bfs_number)</span></span>
<span id="cb104-25"><a href="week-3-regression-i-prediction.html#cb104-25" tabindex="-1"></a></span>
<span id="cb104-26"><a href="week-3-regression-i-prediction.html#cb104-26" tabindex="-1"></a><span class="co">#If there is a “Too Many Requests” error message, you can follow this (https://github.com/lgnbhl/BFS#too-many-requests-error-message) </span></span>
<span id="cb104-27"><a href="week-3-regression-i-prediction.html#cb104-27" tabindex="-1"></a><span class="co">#or download the PX file from here https://www.bfs.admin.ch/bfs/de/home/statistiken/kataloge-datenbanken/daten.assetdetail.24865343.html</span></span>
<span id="cb104-28"><a href="week-3-regression-i-prediction.html#cb104-28" tabindex="-1"></a><span class="co">#install.packages(&quot;pxR&quot;)</span></span>
<span id="cb104-29"><a href="week-3-regression-i-prediction.html#cb104-29" tabindex="-1"></a><span class="co"># library(pxR)</span></span>
<span id="cb104-30"><a href="week-3-regression-i-prediction.html#cb104-30" tabindex="-1"></a><span class="co">#Open data</span></span>
<span id="cb104-31"><a href="week-3-regression-i-prediction.html#cb104-31" tabindex="-1"></a>LandUse <span class="ot">&lt;-</span> <span class="fu">read.px</span>(<span class="st">&#39;Data/px-x-0202020000_102.px&#39;</span>, <span class="at">encoding =</span> <span class="st">&quot;UTF-8&quot;</span>)</span>
<span id="cb104-32"><a href="week-3-regression-i-prediction.html#cb104-32" tabindex="-1"></a>LandUseData<span class="ot">&lt;-</span> LandUse<span class="sc">$</span>DATA<span class="sc">$</span>value</span>
<span id="cb104-33"><a href="week-3-regression-i-prediction.html#cb104-33" tabindex="-1"></a></span>
<span id="cb104-34"><a href="week-3-regression-i-prediction.html#cb104-34" tabindex="-1"></a><span class="co">#Rename variable</span></span>
<span id="cb104-35"><a href="week-3-regression-i-prediction.html#cb104-35" tabindex="-1"></a>LandUseData <span class="ot">&lt;-</span> LandUseData <span class="sc">%&gt;%</span></span>
<span id="cb104-36"><a href="week-3-regression-i-prediction.html#cb104-36" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="sc">~</span> <span class="st">&#39;mun_name&#39;</span>, <span class="dv">3</span>)</span>
<span id="cb104-37"><a href="week-3-regression-i-prediction.html#cb104-37" tabindex="-1"></a></span>
<span id="cb104-38"><a href="week-3-regression-i-prediction.html#cb104-38" tabindex="-1"></a><span class="co">#Keep the data relevant for my analysis</span></span>
<span id="cb104-39"><a href="week-3-regression-i-prediction.html#cb104-39" tabindex="-1"></a>LandUseData<span class="ot">&lt;-</span> LandUseData <span class="sc">%&gt;%</span></span>
<span id="cb104-40"><a href="week-3-regression-i-prediction.html#cb104-40" tabindex="-1"></a>  <span class="fu">filter</span>(Periode <span class="sc">==</span> <span class="st">&quot;2013/18&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb104-41"><a href="week-3-regression-i-prediction.html#cb104-41" tabindex="-1"></a>  <span class="fu">filter</span>(Standardnomenklatur..NOAS04.<span class="sc">==</span><span class="st">&quot;-b Landwirtschaftsflächen&quot;</span> <span class="sc">|</span> Standardnomenklatur..NOAS04.<span class="sc">==</span><span class="st">&quot;Fläche Total&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb104-42"><a href="week-3-regression-i-prediction.html#cb104-42" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_starts</span>(<span class="fu">str_trim</span>(mun_name), <span class="fu">fixed</span>(<span class="st">&quot;.&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb104-43"><a href="week-3-regression-i-prediction.html#cb104-43" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mun_name =</span> <span class="fu">str_replace_all</span>(mun_name, <span class="fu">fixed</span>(<span class="st">&quot;......&quot;</span>), <span class="st">&quot;&quot;</span>))</span>
<span id="cb104-44"><a href="week-3-regression-i-prediction.html#cb104-44" tabindex="-1"></a></span>
<span id="cb104-45"><a href="week-3-regression-i-prediction.html#cb104-45" tabindex="-1"></a><span class="co"># install.packages(&quot;tidyverse&quot;)</span></span>
<span id="cb104-46"><a href="week-3-regression-i-prediction.html#cb104-46" tabindex="-1"></a><span class="co">#Adjust data from long to wide</span></span>
<span id="cb104-47"><a href="week-3-regression-i-prediction.html#cb104-47" tabindex="-1"></a>LandUseData <span class="ot">&lt;-</span> LandUseData <span class="sc">%&gt;%</span></span>
<span id="cb104-48"><a href="week-3-regression-i-prediction.html#cb104-48" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Standardnomenklatur..NOAS04., <span class="at">values_from =</span> value)</span>
<span id="cb104-49"><a href="week-3-regression-i-prediction.html#cb104-49" tabindex="-1"></a></span>
<span id="cb104-50"><a href="week-3-regression-i-prediction.html#cb104-50" tabindex="-1"></a><span class="co">#Rename variables</span></span>
<span id="cb104-51"><a href="week-3-regression-i-prediction.html#cb104-51" tabindex="-1"></a>LandUseData <span class="ot">&lt;-</span> LandUseData <span class="sc">%&gt;%</span></span>
<span id="cb104-52"><a href="week-3-regression-i-prediction.html#cb104-52" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="sc">~</span> <span class="st">&#39;TotalAreaHa&#39;</span>, <span class="dv">3</span>) <span class="sc">%&gt;%</span></span>
<span id="cb104-53"><a href="week-3-regression-i-prediction.html#cb104-53" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="sc">~</span> <span class="st">&#39;AgriculturalAreaHa&#39;</span>, <span class="dv">4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb104-54"><a href="week-3-regression-i-prediction.html#cb104-54" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Periode)</span></code></pre></div>
<p>Using the additional data, you can now merge both data sets so you can know how did voters behave in more agricultural areas. Use the <code>inner_join</code> function. The numerical IDs are available in <code>LandUseData</code> but not in <code>CO2</code>. However, as both sources share the <code>mun_name</code>, you use that variable to match them.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="week-3-regression-i-prediction.html#cb105-1" tabindex="-1"></a>CO2 <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(CO2, LandUseData, <span class="at">by=</span><span class="st">&quot;mun_name&quot;</span>)  </span>
<span id="cb105-2"><a href="week-3-regression-i-prediction.html#cb105-2" tabindex="-1"></a></span>
<span id="cb105-3"><a href="week-3-regression-i-prediction.html#cb105-3" tabindex="-1"></a><span class="fu">write.csv</span>(CO2, <span class="st">&quot;Data/CO2_land.csv&quot;</span>)</span></code></pre></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-4-regression-ii-model-specification.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/03-Week3.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
